-- Seed file for grammar topics
-- Run this file to populate the grammar_topics table with example data

INSERT INTO grammar_topics (name, category, explanation, explanation_portuguese, examples, difficulty, order_index) VALUES
('Present Simple', 'Verb Tenses', 'The Present Simple is used to describe habits, routines, general truths, and permanent situations. It is formed with the base form of the verb (add -s/-es for third person singular).', 'O Present Simple é usado para descrever hábitos, rotinas, verdades gerais e situações permanentes. É formado com a forma base do verbo (adiciona-se -s/-es para a terceira pessoa do singular).', '[{"en": "I work every day.", "pt": "Eu trabalho todos os dias."}, {"en": "She plays tennis on Saturdays.", "pt": "Ela joga ténis aos sábados."}, {"en": "The sun rises in the east.", "pt": "O sol nasce no leste."}, {"en": "He doesn''t like coffee.", "pt": "Ele não gosta de café."}, {"en": "Do you speak English?", "pt": "Você fala inglês?"}]', 'beginner', 1),

('Present Continuous', 'Verb Tenses', 'The Present Continuous describes actions happening now, temporary situations, and future arrangements. It is formed with am/is/are + verb-ing.', 'O Present Continuous descreve ações que estão a acontecer agora, situações temporárias e planos futuros. É formado com am/is/are + verbo-ing.', '[{"en": "I am reading a book.", "pt": "Estou a ler um livro."}, {"en": "She is working from home today.", "pt": "Ela está a trabalhar de casa hoje."}, {"en": "They are meeting us tomorrow.", "pt": "Eles vão encontrar-se connosco amanhã."}, {"en": "Are you listening to me?", "pt": "Estás a ouvir-me?"}]', 'beginner', 2),

('Past Simple', 'Verb Tenses', 'The Past Simple is used for completed actions in the past. Regular verbs add -ed; irregular verbs have special forms. Use did/didn''t for questions and negatives.', 'O Past Simple é usado para ações completas no passado. Verbos regulares adicionam -ed; verbos irregulares têm formas especiais. Usa-se did/didn''t para perguntas e negativas.', '[{"en": "I visited London last year.", "pt": "Visitei Londres no ano passado."}, {"en": "She went to the cinema yesterday.", "pt": "Ela foi ao cinema ontem."}, {"en": "They didn''t arrive on time.", "pt": "Eles não chegaram a tempo."}, {"en": "Did you see the movie?", "pt": "Viste o filme?"}]', 'beginner', 3),

('Present Perfect', 'Verb Tenses', 'The Present Perfect connects past actions to the present. It is used for experiences, recent events, and unfinished time periods. Formed with have/has + past participle.', 'O Present Perfect conecta ações passadas ao presente. É usado para experiências, eventos recentes e períodos de tempo não terminados. Forma-se com have/has + particípio passado.', '[{"en": "I have visited Paris three times.", "pt": "Visitei Paris três vezes."}, {"en": "She has just finished her homework.", "pt": "Ela acabou de terminar os trabalhos de casa."}, {"en": "Have you ever tried sushi?", "pt": "Já experimentaste sushi?"}, {"en": "They haven''t seen that movie yet.", "pt": "Eles ainda não viram esse filme."}]', 'intermediate', 4),

('Future with Will', 'Verb Tenses', 'Will is used for predictions, spontaneous decisions, promises, and offers. It is formed with will + base verb. The negative is won''t (will not).', 'Will é usado para previsões, decisões espontâneas, promessas e ofertas. Forma-se com will + verbo base. A negativa é won''t (will not).', '[{"en": "I think it will rain tomorrow.", "pt": "Acho que vai chover amanhã."}, {"en": "I''ll help you with that.", "pt": "Eu ajudo-te com isso."}, {"en": "She won''t forget your birthday.", "pt": "Ela não vai esquecer o teu aniversário."}, {"en": "Will you come to the party?", "pt": "Vais à festa?"}]', 'beginner', 5),

('Conditionals - Zero and First', 'Conditionals', 'Zero Conditional expresses general truths (If + present, present). First Conditional expresses real possibilities in the future (If + present, will + verb).', 'O Condicional Zero expressa verdades gerais (If + presente, presente). O Primeiro Condicional expressa possibilidades reais no futuro (If + presente, will + verbo).', '[{"en": "If you heat water, it boils.", "pt": "Se aqueceres água, ela ferve."}, {"en": "If it rains, I will stay home.", "pt": "Se chover, fico em casa."}, {"en": "If you study hard, you will pass the exam.", "pt": "Se estudares muito, passas no exame."}]', 'intermediate', 6),

('Second Conditional', 'Conditionals', 'The Second Conditional expresses unreal or hypothetical situations in the present or future. Structure: If + past simple, would + base verb.', 'O Segundo Condicional expressa situações irreais ou hipotéticas no presente ou futuro. Estrutura: If + past simple, would + verbo base.', '[{"en": "If I won the lottery, I would travel the world.", "pt": "Se ganhasse a lotaria, viajaria pelo mundo."}, {"en": "If she spoke French, she would move to Paris.", "pt": "Se ela falasse francês, mudava-se para Paris."}, {"en": "What would you do if you were rich?", "pt": "O que farias se fosses rico?"}]', 'intermediate', 7),

('Passive Voice', 'Voice', 'The Passive Voice emphasizes the action or the receiver rather than the doer. It is formed with be + past participle. Use ''by'' to mention the agent.', 'A Voz Passiva enfatiza a ação ou o recetor em vez de quem faz. Forma-se com be + particípio passado. Usa-se ''by'' para mencionar o agente.', '[{"en": "The book was written by Shakespeare.", "pt": "O livro foi escrito por Shakespeare."}, {"en": "The window was broken.", "pt": "A janela foi partida."}, {"en": "English is spoken worldwide.", "pt": "O inglês é falado mundialmente."}, {"en": "The project will be completed next week.", "pt": "O projeto será concluído na próxima semana."}]', 'intermediate', 8),

('Reported Speech', 'Speech', 'Reported Speech (Indirect Speech) is used to tell someone what another person said. The tense usually shifts back, and pronouns/time references change.', 'O Discurso Indireto é usado para dizer a alguém o que outra pessoa disse. O tempo verbal geralmente recua, e pronomes/referências temporais mudam.', '[{"en": "She said she was tired.", "pt": "Ela disse que estava cansada."}, {"en": "He told me he would call later.", "pt": "Ele disse-me que ligaria mais tarde."}, {"en": "They asked if I wanted coffee.", "pt": "Eles perguntaram se eu queria café."}]', 'advanced', 9),

('Modal Verbs', 'Modals', 'Modal verbs (can, could, may, might, must, should, will, would) express ability, possibility, permission, obligation, or advice. They are followed by the base form of the verb.', 'Os verbos modais (can, could, may, might, must, should, will, would) expressam capacidade, possibilidade, permissão, obrigação ou conselho. São seguidos pela forma base do verbo.', '[{"en": "I can swim.", "pt": "Eu sei nadar."}, {"en": "You should see a doctor.", "pt": "Devias ir ao médico."}, {"en": "She must study for the exam.", "pt": "Ela tem de estudar para o exame."}, {"en": "May I use your phone?", "pt": "Posso usar o teu telemóvel?"}]', 'beginner', 10),

('Relative Clauses', 'Clauses', 'Relative clauses give extra information about nouns using relative pronouns: who (people), which (things), that (both), where (places), whose (possession).', 'As orações relativas dão informação extra sobre substantivos usando pronomes relativos: who (pessoas), which (coisas), that (ambos), where (lugares), whose (posse).', '[{"en": "The man who called you is my uncle.", "pt": "O homem que te ligou é meu tio."}, {"en": "The book which I bought is interesting.", "pt": "O livro que comprei é interessante."}, {"en": "This is the house where I grew up.", "pt": "Esta é a casa onde cresci."}]', 'intermediate', 11),

('Articles (A, An, The)', 'Determiners', 'Use ''a'' before consonant sounds and ''an'' before vowel sounds for singular countable nouns. Use ''the'' for specific things. No article for general plurals and uncountables.', 'Usa-se ''a'' antes de sons consonantais e ''an'' antes de sons vocálicos para substantivos contáveis singulares. Usa-se ''the'' para coisas específicas. Sem artigo para plurais gerais e incontáveis.', '[{"en": "I saw a cat in the garden.", "pt": "Vi um gato no jardim."}, {"en": "She is an engineer.", "pt": "Ela é engenheira."}, {"en": "The sun is shining.", "pt": "O sol está a brilhar."}, {"en": "I love music.", "pt": "Adoro música."}]', 'beginner', 12)
ON CONFLICT DO NOTHING;
