-- Seed file for beginner level texts
-- Run this file to populate the texts table with beginner example data

INSERT INTO texts (title, content, content_portuguese, category, difficulty, word_count) VALUES
('My Daily Routine', 'I wake up at seven o''clock every morning. First, I brush my teeth and take a shower. Then, I have breakfast with my family. I usually eat toast and drink orange juice. After breakfast, I go to work by bus. I work from nine to five. In the evening, I watch TV and read books. I go to bed at eleven o''clock.', 'Acordo às sete horas todas as manhãs. Primeiro, lavo os dentes e tomo um duche. Depois, tomo o pequeno-almoço com a minha família. Normalmente como torradas e bebo sumo de laranja. Depois do pequeno-almoço, vou trabalhar de autocarro. Trabalho das nove às cinco. À noite, vejo televisão e leio livros. Vou para a cama às onze horas.', 'Daily Life', 'beginner', 85),

('The Weather Today', 'Today is a beautiful sunny day. The sky is blue and there are no clouds. It is warm outside, about twenty-five degrees. Many people are in the park. Some children are playing football. Others are having a picnic with their families. In summer, I love to go to the beach. But today, I will stay in the park and enjoy the sunshine.', 'Hoje é um lindo dia de sol. O céu está azul e não há nuvens. Está quente lá fora, cerca de vinte e cinco graus. Muitas pessoas estão no parque. Algumas crianças estão a jogar futebol. Outras estão a fazer piqueniques com as suas famílias. No verão, adoro ir à praia. Mas hoje, vou ficar no parque e aproveitar o sol.', 'Weather', 'beginner', 78),

('My Family', 'I have a small family. There are four people: my father, my mother, my sister, and me. My father is a teacher. He works at a school near our house. My mother is a nurse. She helps sick people at the hospital. My sister is ten years old. She likes to draw and paint. We live in a nice apartment in the city center.', 'Tenho uma família pequena. Somos quatro pessoas: o meu pai, a minha mãe, a minha irmã e eu. O meu pai é professor. Ele trabalha numa escola perto da nossa casa. A minha mãe é enfermeira. Ela ajuda pessoas doentes no hospital. A minha irmã tem dez anos. Ela gosta de desenhar e pintar. Vivemos num apartamento agradável no centro da cidade.', 'Family', 'beginner', 82),

('At the Restaurant', 'Last night, I went to a restaurant with my friends. The restaurant was Italian. We sat at a table near the window. The waiter gave us the menu. I ordered pasta with tomato sauce. My friend ordered pizza. For dessert, we had ice cream. The food was delicious! We paid the bill and left a tip. It was a great evening.', 'Ontem à noite, fui a um restaurante com os meus amigos. O restaurante era italiano. Sentámo-nos a uma mesa perto da janela. O empregado deu-nos o menu. Eu pedi massa com molho de tomate. O meu amigo pediu pizza. Para sobremesa, comemos gelado. A comida estava deliciosa! Pagámos a conta e deixámos gorjeta. Foi uma ótima noite.', 'Food', 'beginner', 79),

('Shopping for Clothes', 'Today I went shopping for new clothes. I need a new jacket for winter. I went to a big shopping center. There are many shops there. I found a beautiful blue jacket. I tried it on in the fitting room. It was the right size! The jacket cost fifty euros. I paid with my credit card. I am very happy with my new jacket.', 'Hoje fui às compras de roupa nova. Preciso de um casaco novo para o inverno. Fui a um grande centro comercial. Há muitas lojas lá. Encontrei um lindo casaco azul. Experimentei-o no provador. Era o tamanho certo! O casaco custou cinquenta euros. Paguei com o meu cartão de crédito. Estou muito feliz com o meu novo casaco.', 'Shopping', 'beginner', 80),

('My Hobbies', 'I have many hobbies. My favorite hobby is reading. I read books every night before I sleep. I also like cooking. On weekends, I cook dinner for my family. Sometimes I play video games with my brother. In summer, I go swimming at the local pool. I want to learn to play the guitar next year. Hobbies make life interesting!', 'Tenho muitos passatempos. O meu passatempo favorito é ler. Leio livros todas as noites antes de dormir. Também gosto de cozinhar. Aos fins de semana, cozinho o jantar para a minha família. Às vezes jogo videojogos com o meu irmão. No verão, vou nadar à piscina local. Quero aprender a tocar guitarra no próximo ano. Os passatempos tornam a vida interessante!', 'Hobbies', 'beginner', 77),

('A Trip to the Zoo', 'Yesterday, my class went to the zoo. We saw many animals. The elephants were very big. The monkeys were funny - they jumped everywhere! I liked the penguins best. They walked in a funny way. We also saw lions, tigers, and bears. At lunchtime, we ate sandwiches in the picnic area. It was a fun school trip!', 'Ontem, a minha turma foi ao jardim zoológico. Vimos muitos animais. Os elefantes eram muito grandes. Os macacos eram engraçados - saltavam para todo o lado! Gostei mais dos pinguins. Eles andavam de uma forma engraçada. Também vimos leões, tigres e ursos. À hora do almoço, comemos sanduíches na área de piquenique. Foi uma excursão escolar divertida!', 'Travel', 'beginner', 75),

('The Supermarket', 'I go to the supermarket every Saturday. I take a shopping list with me. Today I need milk, bread, eggs, and fruit. The supermarket is very big. There are many aisles with different products. I put the items in my shopping cart. At the checkout, I pay for everything. The total is thirty euros. I carry the bags home.', 'Vou ao supermercado todos os sábados. Levo uma lista de compras comigo. Hoje preciso de leite, pão, ovos e fruta. O supermercado é muito grande. Há muitos corredores com produtos diferentes. Ponho os artigos no meu carrinho de compras. Na caixa, pago tudo. O total é trinta euros. Levo os sacos para casa.', 'Shopping', 'beginner', 73),

('My Best Friend', 'My best friend is called Maria. We met at school five years ago. She is kind and funny. We like to do many things together. We watch movies, go shopping, and eat pizza. Maria lives near my house, so we see each other often. She has a dog called Max. I love playing with Max. Maria is like a sister to me.', 'A minha melhor amiga chama-se Maria. Conhecemo-nos na escola há cinco anos. Ela é simpática e engraçada. Gostamos de fazer muitas coisas juntas. Vemos filmes, vamos às compras e comemos pizza. A Maria mora perto da minha casa, por isso vemo-nos frequentemente. Ela tem um cão chamado Max. Adoro brincar com o Max. A Maria é como uma irmã para mim.', 'Relationships', 'beginner', 78),

('Learning English', 'I am learning English. It is not easy, but it is fun! I study English every day. I use a special app on my phone. I also watch movies in English with subtitles. My teacher says my pronunciation is getting better. I want to visit England one day. I dream of speaking English fluently. Practice makes perfect!', 'Estou a aprender inglês. Não é fácil, mas é divertido! Estudo inglês todos os dias. Uso uma aplicação especial no meu telemóvel. Também vejo filmes em inglês com legendas. A minha professora diz que a minha pronúncia está a melhorar. Quero visitar a Inglaterra um dia. Sonho em falar inglês fluentemente. A prática leva à perfeição!', 'Education', 'beginner', 72)
ON CONFLICT DO NOTHING;
