-- Base Vocabulary - Beginner Level (Part 1: 200 words)
-- Essential everyday vocabulary for English learners

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- Greetings & Basic Phrases
('hello', 'olá', 'greetings', 'beginner', '/həˈloʊ/', 'A greeting used when meeting someone', 'Hello, how are you?', 'Olá, como está?'),
('goodbye', 'adeus', 'greetings', 'beginner', '/ɡʊdˈbaɪ/', 'A farewell expression', 'Goodbye, see you tomorrow!', 'Adeus, até amanhã!'),
('please', 'por favor', 'greetings', 'beginner', '/pliːz/', 'Used to make a polite request', 'Please help me.', 'Por favor, ajude-me.'),
('thank you', 'obrigado', 'greetings', 'beginner', '/θæŋk juː/', 'Expression of gratitude', 'Thank you for your help.', 'Obrigado pela sua ajuda.'),
('sorry', 'desculpe', 'greetings', 'beginner', '/ˈsɒri/', 'Expression of apology', 'I am sorry for being late.', 'Desculpe por estar atrasado.'),
('yes', 'sim', 'greetings', 'beginner', '/jes/', 'Affirmative response', 'Yes, I understand.', 'Sim, eu entendo.'),
('no', 'não', 'greetings', 'beginner', '/noʊ/', 'Negative response', 'No, thank you.', 'Não, obrigado.'),
('excuse me', 'com licença', 'greetings', 'beginner', '/ɪkˈskjuːz miː/', 'Used to get attention or apologize', 'Excuse me, where is the station?', 'Com licença, onde fica a estação?'),
('welcome', 'bem-vindo', 'greetings', 'beginner', '/ˈwelkəm/', 'Greeting for someone arriving', 'Welcome to our home!', 'Bem-vindo à nossa casa!'),
('good morning', 'bom dia', 'greetings', 'beginner', '/ɡʊd ˈmɔːrnɪŋ/', 'Morning greeting', 'Good morning, everyone!', 'Bom dia a todos!'),
('good afternoon', 'boa tarde', 'greetings', 'beginner', '/ɡʊd ˌæftərˈnuːn/', 'Afternoon greeting', 'Good afternoon, sir.', 'Boa tarde, senhor.'),
('good evening', 'boa noite', 'greetings', 'beginner', '/ɡʊd ˈiːvnɪŋ/', 'Evening greeting', 'Good evening, ladies.', 'Boa noite, senhoras.'),
('good night', 'boa noite (despedida)', 'greetings', 'beginner', '/ɡʊd naɪt/', 'Farewell at night', 'Good night, sleep well.', 'Boa noite, durma bem.'),

-- Numbers
('one', 'um', 'numbers', 'beginner', '/wʌn/', 'The number 1', 'I have one apple.', 'Eu tenho uma maçã.'),
('two', 'dois', 'numbers', 'beginner', '/tuː/', 'The number 2', 'Two plus two equals four.', 'Dois mais dois é igual a quatro.'),
('three', 'três', 'numbers', 'beginner', '/θriː/', 'The number 3', 'There are three cats.', 'Há três gatos.'),
('four', 'quatro', 'numbers', 'beginner', '/fɔːr/', 'The number 4', 'I have four brothers.', 'Eu tenho quatro irmãos.'),
('five', 'cinco', 'numbers', 'beginner', '/faɪv/', 'The number 5', 'Five minutes please.', 'Cinco minutos, por favor.'),
('six', 'seis', 'numbers', 'beginner', '/sɪks/', 'The number 6', 'She is six years old.', 'Ela tem seis anos.'),
('seven', 'sete', 'numbers', 'beginner', '/ˈsevən/', 'The number 7', 'Seven days a week.', 'Sete dias por semana.'),
('eight', 'oito', 'numbers', 'beginner', '/eɪt/', 'The number 8', 'The class starts at eight.', 'A aula começa às oito.'),
('nine', 'nove', 'numbers', 'beginner', '/naɪn/', 'The number 9', 'Nine is my lucky number.', 'Nove é o meu número da sorte.'),
('ten', 'dez', 'numbers', 'beginner', '/ten/', 'The number 10', 'I need ten euros.', 'Preciso de dez euros.'),
('eleven', 'onze', 'numbers', 'beginner', '/ɪˈlevən/', 'The number 11', 'The meeting is at eleven.', 'A reunião é às onze.'),
('twelve', 'doze', 'numbers', 'beginner', '/twelv/', 'The number 12', 'There are twelve months.', 'Há doze meses.'),
('twenty', 'vinte', 'numbers', 'beginner', '/ˈtwenti/', 'The number 20', 'I am twenty years old.', 'Eu tenho vinte anos.'),
('hundred', 'cem', 'numbers', 'beginner', '/ˈhʌndrəd/', 'The number 100', 'One hundred percent sure.', 'Cem por cento de certeza.'),
('thousand', 'mil', 'numbers', 'beginner', '/ˈθaʊzənd/', 'The number 1000', 'A thousand thanks!', 'Mil obrigados!'),
('first', 'primeiro', 'numbers', 'beginner', '/fɜːrst/', 'Coming before all others', 'This is my first day.', 'Este é o meu primeiro dia.'),
('second', 'segundo', 'numbers', 'beginner', '/ˈsekənd/', 'Coming after the first', 'Wait a second please.', 'Espere um segundo, por favor.'),
('third', 'terceiro', 'numbers', 'beginner', '/θɜːrd/', 'Coming after the second', 'The third floor.', 'O terceiro andar.'),

-- Colors
('red', 'vermelho', 'colors', 'beginner', '/red/', 'The color of blood', 'The apple is red.', 'A maçã é vermelha.'),
('blue', 'azul', 'colors', 'beginner', '/bluː/', 'The color of the sky', 'The sky is blue today.', 'O céu está azul hoje.'),
('green', 'verde', 'colors', 'beginner', '/ɡriːn/', 'The color of grass', 'The grass is green.', 'A relva é verde.'),
('yellow', 'amarelo', 'colors', 'beginner', '/ˈjeloʊ/', 'The color of the sun', 'The sun is yellow.', 'O sol é amarelo.'),
('black', 'preto', 'colors', 'beginner', '/blæk/', 'The darkest color', 'My car is black.', 'O meu carro é preto.'),
('white', 'branco', 'colors', 'beginner', '/waɪt/', 'The lightest color', 'Snow is white.', 'A neve é branca.'),
('orange', 'laranja', 'colors', 'beginner', '/ˈɔːrɪndʒ/', 'A color between red and yellow', 'Oranges are orange.', 'As laranjas são cor de laranja.'),
('purple', 'roxo', 'colors', 'beginner', '/ˈpɜːrpəl/', 'A color between red and blue', 'She loves purple flowers.', 'Ela adora flores roxas.'),
('pink', 'rosa', 'colors', 'beginner', '/pɪŋk/', 'A light red color', 'Her dress is pink.', 'O vestido dela é rosa.'),
('brown', 'castanho', 'colors', 'beginner', '/braʊn/', 'The color of chocolate', 'The dog is brown.', 'O cão é castanho.'),
('grey', 'cinzento', 'colors', 'beginner', '/ɡreɪ/', 'A color between black and white', 'The elephant is grey.', 'O elefante é cinzento.'),

-- Family
('family', 'família', 'family', 'beginner', '/ˈfæməli/', 'A group of related people', 'My family is big.', 'A minha família é grande.'),
('mother', 'mãe', 'family', 'beginner', '/ˈmʌðər/', 'Female parent', 'My mother is a teacher.', 'A minha mãe é professora.'),
('father', 'pai', 'family', 'beginner', '/ˈfɑːðər/', 'Male parent', 'My father works hard.', 'O meu pai trabalha muito.'),
('parents', 'pais', 'family', 'beginner', '/ˈperənts/', 'Mother and father', 'My parents live in Lisbon.', 'Os meus pais vivem em Lisboa.'),
('brother', 'irmão', 'family', 'beginner', '/ˈbrʌðər/', 'Male sibling', 'I have one brother.', 'Eu tenho um irmão.'),
('sister', 'irmã', 'family', 'beginner', '/ˈsɪstər/', 'Female sibling', 'My sister is younger.', 'A minha irmã é mais nova.'),
('son', 'filho', 'family', 'beginner', '/sʌn/', 'Male child', 'He has a son.', 'Ele tem um filho.'),
('daughter', 'filha', 'family', 'beginner', '/ˈdɔːtər/', 'Female child', 'She has two daughters.', 'Ela tem duas filhas.'),
('grandmother', 'avó', 'family', 'beginner', '/ˈɡrænˌmʌðər/', 'Mother of a parent', 'My grandmother makes cookies.', 'A minha avó faz bolachas.'),
('grandfather', 'avô', 'family', 'beginner', '/ˈɡrænˌfɑːðər/', 'Father of a parent', 'My grandfather tells stories.', 'O meu avô conta histórias.'),
('uncle', 'tio', 'family', 'beginner', '/ˈʌŋkəl/', 'Brother of a parent', 'My uncle lives abroad.', 'O meu tio vive no estrangeiro.'),
('aunt', 'tia', 'family', 'beginner', '/ænt/', 'Sister of a parent', 'My aunt is visiting us.', 'A minha tia está a visitar-nos.'),
('cousin', 'primo/prima', 'family', 'beginner', '/ˈkʌzən/', 'Child of aunt or uncle', 'I have many cousins.', 'Eu tenho muitos primos.'),
('husband', 'marido', 'family', 'beginner', '/ˈhʌzbənd/', 'Married male partner', 'Her husband is a doctor.', 'O marido dela é médico.'),
('wife', 'esposa', 'family', 'beginner', '/waɪf/', 'Married female partner', 'His wife is an engineer.', 'A esposa dele é engenheira.'),
('baby', 'bebé', 'family', 'beginner', '/ˈbeɪbi/', 'Very young child', 'The baby is sleeping.', 'O bebé está a dormir.'),
('child', 'criança', 'family', 'beginner', '/tʃaɪld/', 'Young person', 'The child is playing.', 'A criança está a brincar.'),
('children', 'crianças', 'family', 'beginner', '/ˈtʃɪldrən/', 'Plural of child', 'The children are at school.', 'As crianças estão na escola.'),

-- Body Parts
('head', 'cabeça', 'body', 'beginner', '/hed/', 'Top part of the body', 'My head hurts.', 'A minha cabeça dói.'),
('hair', 'cabelo', 'body', 'beginner', '/her/', 'Grows on top of the head', 'She has long hair.', 'Ela tem cabelo comprido.'),
('face', 'rosto', 'body', 'beginner', '/feɪs/', 'Front of the head', 'Wash your face.', 'Lava o rosto.'),
('eye', 'olho', 'body', 'beginner', '/aɪ/', 'Organ for seeing', 'She has blue eyes.', 'Ela tem olhos azuis.'),
('ear', 'orelha', 'body', 'beginner', '/ɪr/', 'Organ for hearing', 'My ear is cold.', 'A minha orelha está fria.'),
('nose', 'nariz', 'body', 'beginner', '/noʊz/', 'Organ for smelling', 'Touch your nose.', 'Toca no teu nariz.'),
('mouth', 'boca', 'body', 'beginner', '/maʊθ/', 'Opening for eating and speaking', 'Open your mouth.', 'Abre a boca.'),
('tooth', 'dente', 'body', 'beginner', '/tuːθ/', 'Hard structure in the mouth', 'Brush your teeth.', 'Escova os dentes.'),
('tongue', 'língua', 'body', 'beginner', '/tʌŋ/', 'Muscle in the mouth', 'Show me your tongue.', 'Mostra-me a língua.'),
('neck', 'pescoço', 'body', 'beginner', '/nek/', 'Connects head to body', 'My neck is stiff.', 'O meu pescoço está rígido.'),
('shoulder', 'ombro', 'body', 'beginner', '/ˈʃoʊldər/', 'Top of the arm', 'He shrugged his shoulders.', 'Ele encolheu os ombros.'),
('arm', 'braço', 'body', 'beginner', '/ɑːrm/', 'Limb from shoulder to hand', 'Raise your arm.', 'Levanta o braço.'),
('hand', 'mão', 'body', 'beginner', '/hænd/', 'End of the arm', 'Wash your hands.', 'Lava as mãos.'),
('finger', 'dedo', 'body', 'beginner', '/ˈfɪŋɡər/', 'Part of the hand', 'I cut my finger.', 'Cortei o dedo.'),
('leg', 'perna', 'body', 'beginner', '/leɡ/', 'Limb for walking', 'My leg is tired.', 'A minha perna está cansada.'),
('knee', 'joelho', 'body', 'beginner', '/niː/', 'Joint in the middle of the leg', 'Bend your knee.', 'Dobra o joelho.'),
('foot', 'pé', 'body', 'beginner', '/fʊt/', 'End of the leg', 'My foot hurts.', 'O meu pé dói.'),
('heart', 'coração', 'body', 'beginner', '/hɑːrt/', 'Organ that pumps blood', 'Listen to your heart.', 'Ouve o teu coração.'),
('stomach', 'estômago', 'body', 'beginner', '/ˈstʌmək/', 'Digestive organ', 'My stomach is empty.', 'O meu estômago está vazio.'),
('back', 'costas', 'body', 'beginner', '/bæk/', 'Rear of the body', 'My back aches.', 'As minhas costas doem.'),

-- Food & Drinks
('food', 'comida', 'food', 'beginner', '/fuːd/', 'What we eat', 'The food is delicious.', 'A comida está deliciosa.'),
('water', 'água', 'food', 'beginner', '/ˈwɔːtər/', 'Clear liquid to drink', 'Drink more water.', 'Bebe mais água.'),
('bread', 'pão', 'food', 'beginner', '/bred/', 'Baked food from flour', 'I buy bread every day.', 'Compro pão todos os dias.'),
('milk', 'leite', 'food', 'beginner', '/mɪlk/', 'White drink from cows', 'Children need milk.', 'As crianças precisam de leite.'),
('egg', 'ovo', 'food', 'beginner', '/eɡ/', 'Laid by chickens', 'I eat eggs for breakfast.', 'Como ovos ao pequeno-almoço.'),
('meat', 'carne', 'food', 'beginner', '/miːt/', 'Flesh of animals', 'He does not eat meat.', 'Ele não come carne.'),
('fish', 'peixe', 'food', 'beginner', '/fɪʃ/', 'Animal that lives in water', 'Fish is healthy food.', 'Peixe é comida saudável.'),
('chicken', 'frango', 'food', 'beginner', '/ˈtʃɪkɪn/', 'Common poultry', 'Grilled chicken is tasty.', 'Frango grelhado é saboroso.'),
('rice', 'arroz', 'food', 'beginner', '/raɪs/', 'White grain food', 'Rice with beans is typical.', 'Arroz com feijão é típico.'),
('fruit', 'fruta', 'food', 'beginner', '/fruːt/', 'Sweet food from plants', 'Eat more fruit.', 'Come mais fruta.'),
('apple', 'maçã', 'food', 'beginner', '/ˈæpəl/', 'Round red or green fruit', 'An apple a day.', 'Uma maçã por dia.'),
('banana', 'banana', 'food', 'beginner', '/bəˈnænə/', 'Yellow curved fruit', 'Monkeys love bananas.', 'Os macacos adoram bananas.'),
('orange', 'laranja', 'food', 'beginner', '/ˈɔːrɪndʒ/', 'Citrus fruit', 'Orange juice is fresh.', 'Sumo de laranja é fresco.'),
('vegetable', 'vegetal', 'food', 'beginner', '/ˈvedʒtəbəl/', 'Plant food', 'Eat your vegetables.', 'Come os vegetais.'),
('potato', 'batata', 'food', 'beginner', '/pəˈteɪtoʊ/', 'Starchy vegetable', 'Mashed potatoes are soft.', 'Puré de batata é macio.'),
('tomato', 'tomate', 'food', 'beginner', '/təˈmeɪtoʊ/', 'Red fruit used as vegetable', 'Tomato sauce is popular.', 'Molho de tomate é popular.'),
('cheese', 'queijo', 'food', 'beginner', '/tʃiːz/', 'Made from milk', 'I love cheese.', 'Adoro queijo.'),
('butter', 'manteiga', 'food', 'beginner', '/ˈbʌtər/', 'Yellow spread', 'Butter on bread.', 'Manteiga no pão.'),
('sugar', 'açúcar', 'food', 'beginner', '/ˈʃʊɡər/', 'Sweet substance', 'No sugar for me.', 'Sem açúcar para mim.'),
('salt', 'sal', 'food', 'beginner', '/sɔːlt/', 'White seasoning', 'Add some salt.', 'Adiciona um pouco de sal.'),
('coffee', 'café', 'food', 'beginner', '/ˈkɔːfi/', 'Hot dark drink', 'I need coffee in the morning.', 'Preciso de café de manhã.'),
('tea', 'chá', 'food', 'beginner', '/tiː/', 'Hot drink from leaves', 'Would you like some tea?', 'Gostaria de chá?'),
('juice', 'sumo', 'food', 'beginner', '/dʒuːs/', 'Drink from fruit', 'Fresh orange juice.', 'Sumo de laranja fresco.'),
('soup', 'sopa', 'food', 'beginner', '/suːp/', 'Liquid food', 'Hot soup is comforting.', 'Sopa quente é reconfortante.'),
('salad', 'salada', 'food', 'beginner', '/ˈsæləd/', 'Mixed raw vegetables', 'A fresh green salad.', 'Uma salada verde fresca.'),
('cake', 'bolo', 'food', 'beginner', '/keɪk/', 'Sweet baked dessert', 'Birthday cake is sweet.', 'Bolo de aniversário é doce.'),
('ice cream', 'gelado', 'food', 'beginner', '/aɪs kriːm/', 'Frozen dessert', 'Children love ice cream.', 'As crianças adoram gelado.'),
('chocolate', 'chocolate', 'food', 'beginner', '/ˈtʃɔːklət/', 'Sweet brown food', 'Dark chocolate is healthy.', 'Chocolate negro é saudável.'),
('breakfast', 'pequeno-almoço', 'food', 'beginner', '/ˈbrekfəst/', 'Morning meal', 'Breakfast is important.', 'O pequeno-almoço é importante.'),
('lunch', 'almoço', 'food', 'beginner', '/lʌntʃ/', 'Midday meal', 'Lunch is at noon.', 'O almoço é ao meio-dia.'),
('dinner', 'jantar', 'food', 'beginner', '/ˈdɪnər/', 'Evening meal', 'Dinner is ready.', 'O jantar está pronto.'),

-- Basic Verbs
('be', 'ser/estar', 'verbs', 'beginner', '/biː/', 'To exist', 'I want to be happy.', 'Quero ser feliz.'),
('have', 'ter', 'verbs', 'beginner', '/hæv/', 'To possess', 'I have a car.', 'Eu tenho um carro.'),
('do', 'fazer', 'verbs', 'beginner', '/duː/', 'To perform an action', 'What do you do?', 'O que é que fazes?'),
('go', 'ir', 'verbs', 'beginner', '/ɡoʊ/', 'To move to a place', 'Let us go home.', 'Vamos para casa.'),
('come', 'vir', 'verbs', 'beginner', '/kʌm/', 'To move toward', 'Please come here.', 'Por favor, venha cá.'),
('see', 'ver', 'verbs', 'beginner', '/siː/', 'To perceive with eyes', 'I see a bird.', 'Vejo um pássaro.'),
('know', 'saber', 'verbs', 'beginner', '/noʊ/', 'To have information', 'I know the answer.', 'Sei a resposta.'),
('get', 'obter', 'verbs', 'beginner', '/ɡet/', 'To obtain', 'I need to get food.', 'Preciso de obter comida.'),
('make', 'fazer/fabricar', 'verbs', 'beginner', '/meɪk/', 'To create', 'I make dinner every day.', 'Faço o jantar todos os dias.'),
('take', 'levar/tomar', 'verbs', 'beginner', '/teɪk/', 'To grasp', 'Take your time.', 'Não te apresses.'),
('give', 'dar', 'verbs', 'beginner', '/ɡɪv/', 'To transfer to someone', 'Give me a chance.', 'Dá-me uma oportunidade.'),
('think', 'pensar', 'verbs', 'beginner', '/θɪŋk/', 'To use the mind', 'I think you are right.', 'Acho que tens razão.'),
('say', 'dizer', 'verbs', 'beginner', '/seɪ/', 'To speak words', 'What did you say?', 'O que é que disseste?'),
('tell', 'contar', 'verbs', 'beginner', '/tel/', 'To communicate', 'Tell me a story.', 'Conta-me uma história.'),
('ask', 'perguntar', 'verbs', 'beginner', '/æsk/', 'To request information', 'Can I ask a question?', 'Posso fazer uma pergunta?'),
('want', 'querer', 'verbs', 'beginner', '/wɑːnt/', 'To desire', 'I want to learn.', 'Quero aprender.'),
('need', 'precisar', 'verbs', 'beginner', '/niːd/', 'To require', 'I need help.', 'Preciso de ajuda.'),
('like', 'gostar', 'verbs', 'beginner', '/laɪk/', 'To enjoy', 'I like music.', 'Gosto de música.'),
('love', 'amar', 'verbs', 'beginner', '/lʌv/', 'To feel deep affection', 'I love my family.', 'Amo a minha família.'),
('eat', 'comer', 'verbs', 'beginner', '/iːt/', 'To consume food', 'Let us eat lunch.', 'Vamos almoçar.'),
('drink', 'beber', 'verbs', 'beginner', '/drɪŋk/', 'To consume liquid', 'Drink some water.', 'Bebe um pouco de água.'),
('sleep', 'dormir', 'verbs', 'beginner', '/sliːp/', 'To rest at night', 'I need to sleep.', 'Preciso de dormir.'),
('walk', 'andar', 'verbs', 'beginner', '/wɔːk/', 'To move on foot', 'I walk to work.', 'Vou a pé para o trabalho.'),
('run', 'correr', 'verbs', 'beginner', '/rʌn/', 'To move fast', 'He runs every morning.', 'Ele corre todas as manhãs.'),
('work', 'trabalhar', 'verbs', 'beginner', '/wɜːrk/', 'To do a job', 'I work hard.', 'Trabalho muito.'),
('play', 'brincar/jogar', 'verbs', 'beginner', '/pleɪ/', 'To have fun', 'Children play outside.', 'As crianças brincam lá fora.'),
('read', 'ler', 'verbs', 'beginner', '/riːd/', 'To look at words', 'I read books.', 'Leio livros.'),
('write', 'escrever', 'verbs', 'beginner', '/raɪt/', 'To form letters', 'Write your name.', 'Escreve o teu nome.'),
('speak', 'falar', 'verbs', 'beginner', '/spiːk/', 'To talk', 'Do you speak English?', 'Fala inglês?'),
('listen', 'ouvir', 'verbs', 'beginner', '/ˈlɪsən/', 'To pay attention to sound', 'Listen carefully.', 'Ouve com atenção.'),
('look', 'olhar', 'verbs', 'beginner', '/lʊk/', 'To direct eyes at', 'Look at me.', 'Olha para mim.'),
('watch', 'assistir', 'verbs', 'beginner', '/wɑːtʃ/', 'To observe', 'Watch this video.', 'Assiste a este vídeo.'),
('wait', 'esperar', 'verbs', 'beginner', '/weɪt/', 'To stay for something', 'Wait for me.', 'Espera por mim.'),
('try', 'tentar', 'verbs', 'beginner', '/traɪ/', 'To attempt', 'Try again.', 'Tenta outra vez.'),
('help', 'ajudar', 'verbs', 'beginner', '/help/', 'To assist', 'Can you help me?', 'Podes ajudar-me?'),
('learn', 'aprender', 'verbs', 'beginner', '/lɜːrn/', 'To gain knowledge', 'I want to learn English.', 'Quero aprender inglês.'),
('teach', 'ensinar', 'verbs', 'beginner', '/tiːtʃ/', 'To give knowledge', 'She teaches children.', 'Ela ensina crianças.'),
('study', 'estudar', 'verbs', 'beginner', '/ˈstʌdi/', 'To learn about', 'I study every day.', 'Estudo todos os dias.'),
('open', 'abrir', 'verbs', 'beginner', '/ˈoʊpən/', 'To make not closed', 'Open the door.', 'Abre a porta.'),
('close', 'fechar', 'verbs', 'beginner', '/kloʊz/', 'To make shut', 'Close the window.', 'Fecha a janela.'),
('buy', 'comprar', 'verbs', 'beginner', '/baɪ/', 'To purchase', 'I want to buy a book.', 'Quero comprar um livro.'),
('sell', 'vender', 'verbs', 'beginner', '/sel/', 'To exchange for money', 'They sell fruits.', 'Eles vendem frutas.'),
('pay', 'pagar', 'verbs', 'beginner', '/peɪ/', 'To give money', 'Pay at the counter.', 'Paga no balcão.'),
('find', 'encontrar', 'verbs', 'beginner', '/faɪnd/', 'To discover', 'I cannot find my keys.', 'Não consigo encontrar as chaves.'),
('put', 'pôr', 'verbs', 'beginner', '/pʊt/', 'To place', 'Put it on the table.', 'Põe na mesa.'),
('leave', 'sair/deixar', 'verbs', 'beginner', '/liːv/', 'To go away from', 'I must leave now.', 'Tenho de sair agora.'),
('sit', 'sentar', 'verbs', 'beginner', '/sɪt/', 'To rest on a seat', 'Please sit down.', 'Por favor, senta-te.'),
('stand', 'ficar de pé', 'verbs', 'beginner', '/stænd/', 'To be upright', 'Stand up please.', 'Levanta-te, por favor.'),
('start', 'começar', 'verbs', 'beginner', '/stɑːrt/', 'To begin', 'Let us start now.', 'Vamos começar agora.'),
('stop', 'parar', 'verbs', 'beginner', '/stɑːp/', 'To cease', 'Stop the car.', 'Para o carro.'),
('live', 'viver', 'verbs', 'beginner', '/lɪv/', 'To be alive', 'I live in Portugal.', 'Vivo em Portugal.'),
('die', 'morrer', 'verbs', 'beginner', '/daɪ/', 'To stop living', 'Flowers die in winter.', 'As flores morrem no inverno.')

ON CONFLICT (word) DO NOTHING;
