-- Base Vocabulary - Beginner Level (Part 2: 200 words)
-- Time, Weather, Places, Adjectives

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- Time
('time', 'tempo', 'time', 'beginner', '/taɪm/', 'Duration of events', 'What time is it?', 'Que horas são?'),
('day', 'dia', 'time', 'beginner', '/deɪ/', '24 hour period', 'Have a nice day.', 'Tenha um bom dia.'),
('night', 'noite', 'time', 'beginner', '/naɪt/', 'Time of darkness', 'The night is beautiful.', 'A noite é bonita.'),
('morning', 'manhã', 'time', 'beginner', '/ˈmɔːrnɪŋ/', 'Early part of day', 'I exercise in the morning.', 'Faço exercício de manhã.'),
('afternoon', 'tarde', 'time', 'beginner', '/ˌæftərˈnuːn/', 'After noon until evening', 'See you this afternoon.', 'Vemo-nos esta tarde.'),
('evening', 'fim de tarde', 'time', 'beginner', '/ˈiːvnɪŋ/', 'Late afternoon', 'The evening is cool.', 'O fim de tarde é fresco.'),
('week', 'semana', 'time', 'beginner', '/wiːk/', 'Seven days', 'See you next week.', 'Vemo-nos na próxima semana.'),
('weekend', 'fim de semana', 'time', 'beginner', '/ˈwiːkend/', 'Saturday and Sunday', 'What are your weekend plans?', 'Quais são os teus planos para o fim de semana?'),
('month', 'mês', 'time', 'beginner', '/mʌnθ/', 'About 30 days', 'This month is busy.', 'Este mês está ocupado.'),
('year', 'ano', 'time', 'beginner', '/jɪr/', '365 days', 'Happy New Year!', 'Feliz Ano Novo!'),
('today', 'hoje', 'time', 'beginner', '/təˈdeɪ/', 'This day', 'Today is Monday.', 'Hoje é segunda-feira.'),
('tomorrow', 'amanhã', 'time', 'beginner', '/təˈmɔːroʊ/', 'The day after today', 'See you tomorrow.', 'Até amanhã.'),
('yesterday', 'ontem', 'time', 'beginner', '/ˈjestərdeɪ/', 'The day before today', 'I saw him yesterday.', 'Vi-o ontem.'),
('now', 'agora', 'time', 'beginner', '/naʊ/', 'At this moment', 'Do it now.', 'Faz isso agora.'),
('later', 'mais tarde', 'time', 'beginner', '/ˈleɪtər/', 'After some time', 'I will call you later.', 'Ligo-te mais tarde.'),
('always', 'sempre', 'time', 'beginner', '/ˈɔːlweɪz/', 'At all times', 'I always wake up early.', 'Acordo sempre cedo.'),
('never', 'nunca', 'time', 'beginner', '/ˈnevər/', 'At no time', 'I never lie.', 'Nunca minto.'),
('sometimes', 'às vezes', 'time', 'beginner', '/ˈsʌmtaɪmz/', 'Occasionally', 'Sometimes I read at night.', 'Às vezes leio à noite.'),
('often', 'frequentemente', 'time', 'beginner', '/ˈɔːfən/', 'Many times', 'I often walk to work.', 'Frequentemente vou a pé para o trabalho.'),
('early', 'cedo', 'time', 'beginner', '/ˈɜːrli/', 'Before expected time', 'I woke up early.', 'Acordei cedo.'),
('late', 'tarde/atrasado', 'time', 'beginner', '/leɪt/', 'After expected time', 'Sorry I am late.', 'Desculpa, estou atrasado.'),
('Monday', 'segunda-feira', 'time', 'beginner', '/ˈmʌndeɪ/', 'First day of the week', 'I hate Mondays.', 'Detesto segundas-feiras.'),
('Tuesday', 'terça-feira', 'time', 'beginner', '/ˈtuːzdeɪ/', 'Second day of the week', 'The meeting is on Tuesday.', 'A reunião é na terça-feira.'),
('Wednesday', 'quarta-feira', 'time', 'beginner', '/ˈwenzdeɪ/', 'Third day of the week', 'Wednesday is my day off.', 'Quarta-feira é o meu dia de folga.'),
('Thursday', 'quinta-feira', 'time', 'beginner', '/ˈθɜːrzdeɪ/', 'Fourth day of the week', 'Thursday is almost Friday.', 'Quinta-feira é quase sexta.'),
('Friday', 'sexta-feira', 'time', 'beginner', '/ˈfraɪdeɪ/', 'Fifth day of the week', 'Thank God it is Friday!', 'Graças a Deus é sexta-feira!'),
('Saturday', 'sábado', 'time', 'beginner', '/ˈsætərdeɪ/', 'Sixth day of the week', 'I sleep late on Saturday.', 'Durmo até tarde no sábado.'),
('Sunday', 'domingo', 'time', 'beginner', '/ˈsʌndeɪ/', 'Last day of the week', 'Sunday is for family.', 'Domingo é para a família.'),
('January', 'janeiro', 'time', 'beginner', '/ˈdʒænjueri/', 'First month', 'January is cold.', 'Janeiro é frio.'),
('February', 'fevereiro', 'time', 'beginner', '/ˈfebrueri/', 'Second month', 'February has 28 days.', 'Fevereiro tem 28 dias.'),
('March', 'março', 'time', 'beginner', '/mɑːrtʃ/', 'Third month', 'Spring starts in March.', 'A primavera começa em março.'),
('April', 'abril', 'time', 'beginner', '/ˈeɪprəl/', 'Fourth month', 'April showers.', 'Chuvas de abril.'),
('May', 'maio', 'time', 'beginner', '/meɪ/', 'Fifth month', 'May flowers are beautiful.', 'As flores de maio são bonitas.'),
('June', 'junho', 'time', 'beginner', '/dʒuːn/', 'Sixth month', 'Summer starts in June.', 'O verão começa em junho.'),
('July', 'julho', 'time', 'beginner', '/dʒuˈlaɪ/', 'Seventh month', 'July is very hot.', 'Julho é muito quente.'),
('August', 'agosto', 'time', 'beginner', '/ˈɔːɡəst/', 'Eighth month', 'I have vacation in August.', 'Tenho férias em agosto.'),
('September', 'setembro', 'time', 'beginner', '/sepˈtembər/', 'Ninth month', 'School starts in September.', 'As aulas começam em setembro.'),
('October', 'outubro', 'time', 'beginner', '/ɑːkˈtoʊbər/', 'Tenth month', 'October has Halloween.', 'Outubro tem o Halloween.'),
('November', 'novembro', 'time', 'beginner', '/noʊˈvembər/', 'Eleventh month', 'November is rainy.', 'Novembro é chuvoso.'),
('December', 'dezembro', 'time', 'beginner', '/dɪˈsembər/', 'Last month', 'Christmas is in December.', 'O Natal é em dezembro.'),
('hour', 'hora', 'time', 'beginner', '/aʊər/', '60 minutes', 'I waited for one hour.', 'Esperei uma hora.'),
('minute', 'minuto', 'time', 'beginner', '/ˈmɪnɪt/', '60 seconds', 'Wait a minute.', 'Espera um minuto.'),
('clock', 'relógio', 'time', 'beginner', '/klɑːk/', 'Device showing time', 'The clock is broken.', 'O relógio está avariado.'),
('calendar', 'calendário', 'time', 'beginner', '/ˈkæləndər/', 'Shows days and months', 'Check the calendar.', 'Verifica o calendário.'),

-- Weather
('weather', 'tempo/clima', 'weather', 'beginner', '/ˈweðər/', 'Atmospheric conditions', 'How is the weather?', 'Como está o tempo?'),
('sun', 'sol', 'weather', 'beginner', '/sʌn/', 'Star in our sky', 'The sun is shining.', 'O sol está a brilhar.'),
('rain', 'chuva', 'weather', 'beginner', '/reɪn/', 'Water from clouds', 'It is raining outside.', 'Está a chover lá fora.'),
('snow', 'neve', 'weather', 'beginner', '/snoʊ/', 'Frozen water from sky', 'Children love snow.', 'As crianças adoram neve.'),
('cloud', 'nuvem', 'weather', 'beginner', '/klaʊd/', 'White mass in sky', 'Dark clouds are coming.', 'Nuvens escuras estão a vir.'),
('wind', 'vento', 'weather', 'beginner', '/wɪnd/', 'Moving air', 'The wind is strong.', 'O vento está forte.'),
('hot', 'quente', 'weather', 'beginner', '/hɑːt/', 'High temperature', 'It is very hot today.', 'Está muito quente hoje.'),
('cold', 'frio', 'weather', 'beginner', '/koʊld/', 'Low temperature', 'The winter is cold.', 'O inverno é frio.'),
('warm', 'morno', 'weather', 'beginner', '/wɔːrm/', 'Comfortably hot', 'The water is warm.', 'A água está morna.'),
('cool', 'fresco', 'weather', 'beginner', '/kuːl/', 'Slightly cold', 'The evening is cool.', 'A noite está fresca.'),
('sunny', 'ensolarado', 'weather', 'beginner', '/ˈsʌni/', 'Full of sunshine', 'A sunny day.', 'Um dia ensolarado.'),
('cloudy', 'nublado', 'weather', 'beginner', '/ˈklaʊdi/', 'Full of clouds', 'It is cloudy today.', 'Está nublado hoje.'),
('rainy', 'chuvoso', 'weather', 'beginner', '/ˈreɪni/', 'With much rain', 'A rainy afternoon.', 'Uma tarde chuvosa.'),
('windy', 'ventoso', 'weather', 'beginner', '/ˈwɪndi/', 'With much wind', 'It is windy outside.', 'Está ventoso lá fora.'),
('storm', 'tempestade', 'weather', 'beginner', '/stɔːrm/', 'Violent weather', 'A storm is coming.', 'Uma tempestade está a vir.'),
('spring', 'primavera', 'weather', 'beginner', '/sprɪŋ/', 'Season after winter', 'Flowers bloom in spring.', 'As flores florescem na primavera.'),
('summer', 'verão', 'weather', 'beginner', '/ˈsʌmər/', 'Hottest season', 'Summer vacation is fun.', 'As férias de verão são divertidas.'),
('autumn', 'outono', 'weather', 'beginner', '/ˈɔːtəm/', 'Season after summer', 'Leaves fall in autumn.', 'As folhas caem no outono.'),
('winter', 'inverno', 'weather', 'beginner', '/ˈwɪntər/', 'Coldest season', 'Winter nights are long.', 'As noites de inverno são longas.'),
('sky', 'céu', 'weather', 'beginner', '/skaɪ/', 'Space above earth', 'The sky is clear.', 'O céu está limpo.'),

-- Places
('house', 'casa', 'places', 'beginner', '/haʊs/', 'Building for living', 'My house is small.', 'A minha casa é pequena.'),
('home', 'lar', 'places', 'beginner', '/hoʊm/', 'Where one lives', 'There is no place like home.', 'Não há lugar como o lar.'),
('room', 'quarto/sala', 'places', 'beginner', '/ruːm/', 'Space in a building', 'This room is big.', 'Este quarto é grande.'),
('kitchen', 'cozinha', 'places', 'beginner', '/ˈkɪtʃɪn/', 'Room for cooking', 'The kitchen smells good.', 'A cozinha cheira bem.'),
('bathroom', 'casa de banho', 'places', 'beginner', '/ˈbæθruːm/', 'Room with toilet', 'Where is the bathroom?', 'Onde é a casa de banho?'),
('bedroom', 'quarto de dormir', 'places', 'beginner', '/ˈbedruːm/', 'Room for sleeping', 'My bedroom is upstairs.', 'O meu quarto é no andar de cima.'),
('living room', 'sala de estar', 'places', 'beginner', '/ˈlɪvɪŋ ruːm/', 'Main room for living', 'We watch TV in the living room.', 'Vemos televisão na sala de estar.'),
('door', 'porta', 'places', 'beginner', '/dɔːr/', 'Opening in a wall', 'Close the door please.', 'Fecha a porta, por favor.'),
('window', 'janela', 'places', 'beginner', '/ˈwɪndoʊ/', 'Glass opening in wall', 'Open the window.', 'Abre a janela.'),
('floor', 'chão', 'places', 'beginner', '/flɔːr/', 'Surface you walk on', 'The floor is clean.', 'O chão está limpo.'),
('wall', 'parede', 'places', 'beginner', '/wɔːl/', 'Vertical part of room', 'Paint the wall white.', 'Pinta a parede de branco.'),
('garden', 'jardim', 'places', 'beginner', '/ˈɡɑːrdən/', 'Area with plants', 'The garden is beautiful.', 'O jardim é bonito.'),
('street', 'rua', 'places', 'beginner', '/striːt/', 'Road in a town', 'Cross the street carefully.', 'Atravessa a rua com cuidado.'),
('city', 'cidade', 'places', 'beginner', '/ˈsɪti/', 'Large town', 'I live in a big city.', 'Vivo numa cidade grande.'),
('town', 'vila', 'places', 'beginner', '/taʊn/', 'Small city', 'This is a quiet town.', 'Esta é uma vila tranquila.'),
('country', 'país', 'places', 'beginner', '/ˈkʌntri/', 'Nation', 'What country are you from?', 'De que país és?'),
('school', 'escola', 'places', 'beginner', '/skuːl/', 'Place for learning', 'I go to school every day.', 'Vou à escola todos os dias.'),
('hospital', 'hospital', 'places', 'beginner', '/ˈhɑːspɪtəl/', 'Place for sick people', 'He is in the hospital.', 'Ele está no hospital.'),
('bank', 'banco', 'places', 'beginner', '/bæŋk/', 'Place for money', 'I need to go to the bank.', 'Preciso de ir ao banco.'),
('store', 'loja', 'places', 'beginner', '/stɔːr/', 'Place to buy things', 'The store is closed.', 'A loja está fechada.'),
('shop', 'loja', 'places', 'beginner', '/ʃɑːp/', 'Small store', 'A flower shop.', 'Uma loja de flores.'),
('market', 'mercado', 'places', 'beginner', '/ˈmɑːrkɪt/', 'Place to buy food', 'I go to the market on Saturday.', 'Vou ao mercado no sábado.'),
('supermarket', 'supermercado', 'places', 'beginner', '/ˈsuːpərmɑːrkɪt/', 'Large store', 'The supermarket is open 24 hours.', 'O supermercado está aberto 24 horas.'),
('restaurant', 'restaurante', 'places', 'beginner', '/ˈrestərɑːnt/', 'Place to eat', 'Let us go to a restaurant.', 'Vamos a um restaurante.'),
('hotel', 'hotel', 'places', 'beginner', '/hoʊˈtel/', 'Place to stay', 'The hotel is expensive.', 'O hotel é caro.'),
('airport', 'aeroporto', 'places', 'beginner', '/ˈerpɔːrt/', 'Place for planes', 'I am going to the airport.', 'Estou a ir para o aeroporto.'),
('station', 'estação', 'places', 'beginner', '/ˈsteɪʃən/', 'Place for trains', 'The train station is near.', 'A estação de comboio é perto.'),
('park', 'parque', 'places', 'beginner', '/pɑːrk/', 'Green area for recreation', 'Children play in the park.', 'As crianças brincam no parque.'),
('beach', 'praia', 'places', 'beginner', '/biːtʃ/', 'Sandy area by sea', 'I love the beach.', 'Adoro a praia.'),
('church', 'igreja', 'places', 'beginner', '/tʃɜːrtʃ/', 'Place for worship', 'The church is old.', 'A igreja é antiga.'),
('library', 'biblioteca', 'places', 'beginner', '/ˈlaɪbreri/', 'Place with books', 'I study at the library.', 'Estudo na biblioteca.'),
('office', 'escritório', 'places', 'beginner', '/ˈɔːfɪs/', 'Place for work', 'My office is downtown.', 'O meu escritório é no centro.'),
('factory', 'fábrica', 'places', 'beginner', '/ˈfæktəri/', 'Place making goods', 'He works in a factory.', 'Ele trabalha numa fábrica.'),

-- Basic Adjectives
('good', 'bom', 'adjectives', 'beginner', '/ɡʊd/', 'Of high quality', 'This is a good book.', 'Este é um bom livro.'),
('bad', 'mau', 'adjectives', 'beginner', '/bæd/', 'Of low quality', 'This is a bad idea.', 'Esta é uma má ideia.'),
('big', 'grande', 'adjectives', 'beginner', '/bɪɡ/', 'Large in size', 'A big house.', 'Uma casa grande.'),
('small', 'pequeno', 'adjectives', 'beginner', '/smɔːl/', 'Little in size', 'A small cat.', 'Um gato pequeno.'),
('new', 'novo', 'adjectives', 'beginner', '/nuː/', 'Recently made', 'I have a new phone.', 'Tenho um telefone novo.'),
('old', 'velho', 'adjectives', 'beginner', '/oʊld/', 'Not new', 'An old building.', 'Um edifício velho.'),
('young', 'jovem', 'adjectives', 'beginner', '/jʌŋ/', 'Not old in age', 'A young woman.', 'Uma mulher jovem.'),
('happy', 'feliz', 'adjectives', 'beginner', '/ˈhæpi/', 'Feeling joy', 'I am happy today.', 'Estou feliz hoje.'),
('sad', 'triste', 'adjectives', 'beginner', '/sæd/', 'Feeling sorrow', 'Why are you sad?', 'Porque estás triste?'),
('beautiful', 'bonito', 'adjectives', 'beginner', '/ˈbjuːtɪfəl/', 'Very attractive', 'A beautiful flower.', 'Uma flor bonita.'),
('ugly', 'feio', 'adjectives', 'beginner', '/ˈʌɡli/', 'Not attractive', 'An ugly monster.', 'Um monstro feio.'),
('fast', 'rápido', 'adjectives', 'beginner', '/fæst/', 'Moving quickly', 'A fast car.', 'Um carro rápido.'),
('slow', 'lento', 'adjectives', 'beginner', '/sloʊ/', 'Moving not quickly', 'A slow turtle.', 'Uma tartaruga lenta.'),
('easy', 'fácil', 'adjectives', 'beginner', '/ˈiːzi/', 'Not difficult', 'An easy question.', 'Uma pergunta fácil.'),
('difficult', 'difícil', 'adjectives', 'beginner', '/ˈdɪfɪkəlt/', 'Not easy', 'A difficult problem.', 'Um problema difícil.'),
('hard', 'duro/difícil', 'adjectives', 'beginner', '/hɑːrd/', 'Not soft or not easy', 'This is hard work.', 'Este é um trabalho difícil.'),
('soft', 'macio', 'adjectives', 'beginner', '/sɔːft/', 'Not hard', 'A soft pillow.', 'Uma almofada macia.'),
('long', 'longo', 'adjectives', 'beginner', '/lɔːŋ/', 'Great in length', 'A long road.', 'Uma estrada longa.'),
('short', 'curto', 'adjectives', 'beginner', '/ʃɔːrt/', 'Not long', 'A short movie.', 'Um filme curto.'),
('tall', 'alto', 'adjectives', 'beginner', '/tɔːl/', 'High in stature', 'A tall man.', 'Um homem alto.'),
('high', 'alto', 'adjectives', 'beginner', '/haɪ/', 'Far from ground', 'A high mountain.', 'Uma montanha alta.'),
('low', 'baixo', 'adjectives', 'beginner', '/loʊ/', 'Near to ground', 'A low table.', 'Uma mesa baixa.'),
('strong', 'forte', 'adjectives', 'beginner', '/strɔːŋ/', 'Having power', 'A strong man.', 'Um homem forte.'),
('weak', 'fraco', 'adjectives', 'beginner', '/wiːk/', 'Not strong', 'I feel weak today.', 'Sinto-me fraco hoje.'),
('rich', 'rico', 'adjectives', 'beginner', '/rɪtʃ/', 'Having much money', 'A rich family.', 'Uma família rica.'),
('poor', 'pobre', 'adjectives', 'beginner', '/pʊr/', 'Having little money', 'A poor neighborhood.', 'Um bairro pobre.'),
('cheap', 'barato', 'adjectives', 'beginner', '/tʃiːp/', 'Low in price', 'A cheap restaurant.', 'Um restaurante barato.'),
('expensive', 'caro', 'adjectives', 'beginner', '/ɪkˈspensɪv/', 'High in price', 'An expensive car.', 'Um carro caro.'),
('clean', 'limpo', 'adjectives', 'beginner', '/kliːn/', 'Free from dirt', 'A clean house.', 'Uma casa limpa.'),
('dirty', 'sujo', 'adjectives', 'beginner', '/ˈdɜːrti/', 'Not clean', 'Dirty hands.', 'Mãos sujas.'),
('empty', 'vazio', 'adjectives', 'beginner', '/ˈempti/', 'Containing nothing', 'An empty bottle.', 'Uma garrafa vazia.'),
('full', 'cheio', 'adjectives', 'beginner', '/fʊl/', 'Containing much', 'A full glass.', 'Um copo cheio.'),
('open', 'aberto', 'adjectives', 'beginner', '/ˈoʊpən/', 'Not closed', 'The door is open.', 'A porta está aberta.'),
('closed', 'fechado', 'adjectives', 'beginner', '/kloʊzd/', 'Not open', 'The store is closed.', 'A loja está fechada.'),
('right', 'certo', 'adjectives', 'beginner', '/raɪt/', 'Correct', 'That is right.', 'Isso está certo.'),
('wrong', 'errado', 'adjectives', 'beginner', '/rɔːŋ/', 'Not correct', 'The answer is wrong.', 'A resposta está errada.'),
('same', 'mesmo', 'adjectives', 'beginner', '/seɪm/', 'Identical', 'We have the same idea.', 'Temos a mesma ideia.'),
('different', 'diferente', 'adjectives', 'beginner', '/ˈdɪfərənt/', 'Not the same', 'A different approach.', 'Uma abordagem diferente.'),
('important', 'importante', 'adjectives', 'beginner', '/ɪmˈpɔːrtənt/', 'Of great value', 'This is important.', 'Isto é importante.'),
('possible', 'possível', 'adjectives', 'beginner', '/ˈpɑːsəbəl/', 'Can be done', 'Everything is possible.', 'Tudo é possível.'),
('free', 'livre/grátis', 'adjectives', 'beginner', '/friː/', 'At no cost or not restricted', 'This is free.', 'Isto é grátis.'),
('busy', 'ocupado', 'adjectives', 'beginner', '/ˈbɪzi/', 'Having much to do', 'I am busy now.', 'Estou ocupado agora.'),
('ready', 'pronto', 'adjectives', 'beginner', '/ˈredi/', 'Prepared', 'I am ready.', 'Estou pronto.'),
('quiet', 'silencioso', 'adjectives', 'beginner', '/ˈkwaɪət/', 'Making little noise', 'A quiet place.', 'Um lugar silencioso.'),
('loud', 'barulhento', 'adjectives', 'beginner', '/laʊd/', 'Making much noise', 'The music is loud.', 'A música está alta.'),
('dark', 'escuro', 'adjectives', 'beginner', '/dɑːrk/', 'Without light', 'A dark room.', 'Um quarto escuro.'),
('light', 'claro/leve', 'adjectives', 'beginner', '/laɪt/', 'With light or not heavy', 'A light color.', 'Uma cor clara.'),
('heavy', 'pesado', 'adjectives', 'beginner', '/ˈhevi/', 'Having much weight', 'A heavy box.', 'Uma caixa pesada.'),
('safe', 'seguro', 'adjectives', 'beginner', '/seɪf/', 'Free from danger', 'A safe place.', 'Um lugar seguro.'),
('dangerous', 'perigoso', 'adjectives', 'beginner', '/ˈdeɪndʒərəs/', 'Likely to cause harm', 'A dangerous road.', 'Uma estrada perigosa.'),
('nice', 'agradável', 'adjectives', 'beginner', '/naɪs/', 'Pleasant', 'A nice day.', 'Um dia agradável.'),
('kind', 'gentil', 'adjectives', 'beginner', '/kaɪnd/', 'Friendly and generous', 'A kind person.', 'Uma pessoa gentil.'),
('funny', 'engraçado', 'adjectives', 'beginner', '/ˈfʌni/', 'Causing laughter', 'A funny joke.', 'Uma piada engraçada.'),
('interesting', 'interessante', 'adjectives', 'beginner', '/ˈɪntrəstɪŋ/', 'Arousing curiosity', 'An interesting book.', 'Um livro interessante.'),
('boring', 'aborrecido', 'adjectives', 'beginner', '/ˈbɔːrɪŋ/', 'Not interesting', 'A boring movie.', 'Um filme aborrecido.'),
('tired', 'cansado', 'adjectives', 'beginner', '/ˈtaɪərd/', 'Needing rest', 'I am tired.', 'Estou cansado.'),
('hungry', 'com fome', 'adjectives', 'beginner', '/ˈhʌŋɡri/', 'Wanting food', 'I am hungry.', 'Tenho fome.'),
('thirsty', 'com sede', 'adjectives', 'beginner', '/ˈθɜːrsti/', 'Wanting drink', 'I am thirsty.', 'Tenho sede.'),
('sick', 'doente', 'adjectives', 'beginner', '/sɪk/', 'Not healthy', 'I feel sick.', 'Sinto-me doente.'),
('healthy', 'saudável', 'adjectives', 'beginner', '/ˈhelθi/', 'In good condition', 'A healthy diet.', 'Uma dieta saudável.'),
('angry', 'zangado', 'adjectives', 'beginner', '/ˈæŋɡri/', 'Feeling anger', 'Do not be angry.', 'Não fiques zangado.'),
('afraid', 'com medo', 'adjectives', 'beginner', '/əˈfreɪd/', 'Feeling fear', 'I am afraid of dogs.', 'Tenho medo de cães.'),
('surprised', 'surpreendido', 'adjectives', 'beginner', '/sərˈpraɪzd/', 'Feeling surprise', 'I am surprised.', 'Estou surpreendido.'),
('lucky', 'sortudo', 'adjectives', 'beginner', '/ˈlʌki/', 'Having good fortune', 'You are lucky.', 'Tens sorte.')

ON CONFLICT (word) DO UPDATE SET
  translation = EXCLUDED.translation,
  category = EXCLUDED.category,
  difficulty = EXCLUDED.difficulty,
  pronunciation = EXCLUDED.pronunciation,
  definition = EXCLUDED.definition,
  example_sentence = EXCLUDED.example_sentence,
  example_translation = EXCLUDED.example_translation,
  updated_at = now();
