-- Base Vocabulary - Beginner Level (Part 3: 200 words)
-- Objects, Transportation, Professions, Clothing

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- Common Objects
('table', 'mesa', 'objects', 'beginner', '/ˈteɪbəl/', 'Furniture for eating or working', 'Put it on the table.', 'Põe na mesa.'),
('chair', 'cadeira', 'objects', 'beginner', '/tʃer/', 'Furniture for sitting', 'Please take a chair.', 'Por favor, senta-te.'),
('bed', 'cama', 'objects', 'beginner', '/bed/', 'Furniture for sleeping', 'The bed is comfortable.', 'A cama é confortável.'),
('sofa', 'sofá', 'objects', 'beginner', '/ˈsoʊfə/', 'Comfortable seat for several', 'Sit on the sofa.', 'Senta no sofá.'),
('desk', 'secretária', 'objects', 'beginner', '/desk/', 'Table for work', 'My desk is messy.', 'A minha secretária está desarrumada.'),
('lamp', 'candeeiro', 'objects', 'beginner', '/læmp/', 'Device giving light', 'Turn on the lamp.', 'Liga o candeeiro.'),
('mirror', 'espelho', 'objects', 'beginner', '/ˈmɪrər/', 'Glass that reflects', 'Look in the mirror.', 'Olha no espelho.'),
('picture', 'quadro/foto', 'objects', 'beginner', '/ˈpɪktʃər/', 'Image on wall', 'A beautiful picture.', 'Um quadro bonito.'),
('television', 'televisão', 'objects', 'beginner', '/ˈtelɪvɪʒən/', 'Device for watching programs', 'Turn off the television.', 'Desliga a televisão.'),
('computer', 'computador', 'objects', 'beginner', '/kəmˈpjuːtər/', 'Electronic machine', 'I work on a computer.', 'Trabalho num computador.'),
('phone', 'telefone', 'objects', 'beginner', '/foʊn/', 'Device for calling', 'My phone is ringing.', 'O meu telefone está a tocar.'),
('book', 'livro', 'objects', 'beginner', '/bʊk/', 'Written work', 'I am reading a book.', 'Estou a ler um livro.'),
('pen', 'caneta', 'objects', 'beginner', '/pen/', 'Writing instrument', 'Can I borrow your pen?', 'Posso emprestar a tua caneta?'),
('pencil', 'lápis', 'objects', 'beginner', '/ˈpensəl/', 'Writing instrument', 'Sharpen your pencil.', 'Afia o lápis.'),
('paper', 'papel', 'objects', 'beginner', '/ˈpeɪpər/', 'Material for writing', 'I need some paper.', 'Preciso de papel.'),
('key', 'chave', 'objects', 'beginner', '/kiː/', 'Opens locks', 'Where are my keys?', 'Onde estão as minhas chaves?'),
('bag', 'saco/mala', 'objects', 'beginner', '/bæɡ/', 'Container for carrying', 'Put it in the bag.', 'Põe no saco.'),
('box', 'caixa', 'objects', 'beginner', '/bɑːks/', 'Container with sides', 'Open the box.', 'Abre a caixa.'),
('bottle', 'garrafa', 'objects', 'beginner', '/ˈbɑːtəl/', 'Container for liquids', 'A bottle of water.', 'Uma garrafa de água.'),
('cup', 'chávena', 'objects', 'beginner', '/kʌp/', 'Container for drinking', 'A cup of tea.', 'Uma chávena de chá.'),
('glass', 'copo', 'objects', 'beginner', '/ɡlæs/', 'Container for drinking', 'A glass of water.', 'Um copo de água.'),
('plate', 'prato', 'objects', 'beginner', '/pleɪt/', 'Dish for food', 'An empty plate.', 'Um prato vazio.'),
('fork', 'garfo', 'objects', 'beginner', '/fɔːrk/', 'Eating utensil', 'Use your fork.', 'Usa o garfo.'),
('knife', 'faca', 'objects', 'beginner', '/naɪf/', 'Cutting utensil', 'Be careful with the knife.', 'Tem cuidado com a faca.'),
('spoon', 'colher', 'objects', 'beginner', '/spuːn/', 'Eating utensil', 'Stir with a spoon.', 'Mexe com uma colher.'),
('towel', 'toalha', 'objects', 'beginner', '/ˈtaʊəl/', 'Cloth for drying', 'Dry your hands with a towel.', 'Seca as mãos com uma toalha.'),
('soap', 'sabão', 'objects', 'beginner', '/soʊp/', 'For cleaning', 'Wash with soap.', 'Lava com sabão.'),
('toothbrush', 'escova de dentes', 'objects', 'beginner', '/ˈtuːθbrʌʃ/', 'For cleaning teeth', 'Brush with your toothbrush.', 'Escova com a tua escova de dentes.'),
('umbrella', 'guarda-chuva', 'objects', 'beginner', '/ʌmˈbrelə/', 'Protection from rain', 'Take your umbrella.', 'Leva o guarda-chuva.'),
('camera', 'câmara', 'objects', 'beginner', '/ˈkæmərə/', 'For taking photos', 'I forgot my camera.', 'Esqueci a minha câmara.'),
('watch', 'relógio de pulso', 'objects', 'beginner', '/wɑːtʃ/', 'Time device on wrist', 'Check your watch.', 'Verifica o relógio.'),
('money', 'dinheiro', 'objects', 'beginner', '/ˈmʌni/', 'Currency', 'I need money.', 'Preciso de dinheiro.'),
('wallet', 'carteira', 'objects', 'beginner', '/ˈwɔːlɪt/', 'For carrying money', 'I lost my wallet.', 'Perdi a minha carteira.'),
('ticket', 'bilhete', 'objects', 'beginner', '/ˈtɪkɪt/', 'Pass for entry', 'Buy a ticket.', 'Compra um bilhete.'),
('gift', 'presente', 'objects', 'beginner', '/ɡɪft/', 'Something given', 'A birthday gift.', 'Um presente de aniversário.'),
('toy', 'brinquedo', 'objects', 'beginner', '/tɔɪ/', 'Object for playing', 'Children love toys.', 'As crianças adoram brinquedos.'),
('ball', 'bola', 'objects', 'beginner', '/bɔːl/', 'Round object for games', 'Kick the ball.', 'Chuta a bola.'),
('game', 'jogo', 'objects', 'beginner', '/ɡeɪm/', 'Activity for fun', 'Let us play a game.', 'Vamos jogar um jogo.'),

-- Transportation
('car', 'carro', 'transport', 'beginner', '/kɑːr/', 'Vehicle with four wheels', 'I drive a car.', 'Conduzo um carro.'),
('bus', 'autocarro', 'transport', 'beginner', '/bʌs/', 'Large public vehicle', 'Take the bus.', 'Apanha o autocarro.'),
('train', 'comboio', 'transport', 'beginner', '/treɪn/', 'Runs on tracks', 'The train is late.', 'O comboio está atrasado.'),
('plane', 'avião', 'transport', 'beginner', '/pleɪn/', 'Flying vehicle', 'The plane is landing.', 'O avião está a aterrar.'),
('bicycle', 'bicicleta', 'transport', 'beginner', '/ˈbaɪsɪkəl/', 'Two-wheeled vehicle', 'I ride a bicycle.', 'Ando de bicicleta.'),
('bike', 'bicicleta/mota', 'transport', 'beginner', '/baɪk/', 'Two-wheeled vehicle', 'I love my bike.', 'Adoro a minha bicicleta.'),
('motorcycle', 'motocicleta', 'transport', 'beginner', '/ˈmoʊtərsaɪkəl/', 'Two-wheeled motor vehicle', 'He has a motorcycle.', 'Ele tem uma mota.'),
('taxi', 'táxi', 'transport', 'beginner', '/ˈtæksi/', 'Hired car', 'Call a taxi.', 'Chama um táxi.'),
('boat', 'barco', 'transport', 'beginner', '/boʊt/', 'Water vehicle', 'A small boat.', 'Um barco pequeno.'),
('ship', 'navio', 'transport', 'beginner', '/ʃɪp/', 'Large water vehicle', 'The ship is sailing.', 'O navio está a navegar.'),
('truck', 'camião', 'transport', 'beginner', '/trʌk/', 'Large land vehicle', 'A delivery truck.', 'Um camião de entregas.'),
('subway', 'metro', 'transport', 'beginner', '/ˈsʌbweɪ/', 'Underground train', 'Take the subway.', 'Apanha o metro.'),
('road', 'estrada', 'transport', 'beginner', '/roʊd/', 'Path for vehicles', 'A long road.', 'Uma estrada longa.'),
('bridge', 'ponte', 'transport', 'beginner', '/brɪdʒ/', 'Structure over water', 'Cross the bridge.', 'Atravessa a ponte.'),
('traffic', 'trânsito', 'transport', 'beginner', '/ˈtræfɪk/', 'Vehicles on road', 'Heavy traffic today.', 'Muito trânsito hoje.'),
('driver', 'condutor', 'transport', 'beginner', '/ˈdraɪvər/', 'Person who drives', 'The bus driver.', 'O condutor do autocarro.'),
('passenger', 'passageiro', 'transport', 'beginner', '/ˈpæsəndʒər/', 'Person traveling', 'A train passenger.', 'Um passageiro de comboio.'),
('trip', 'viagem', 'transport', 'beginner', '/trɪp/', 'Journey', 'Have a good trip!', 'Boa viagem!'),
('journey', 'jornada', 'transport', 'beginner', '/ˈdʒɜːrni/', 'Travel from one place to another', 'A long journey.', 'Uma longa jornada.'),

-- Professions
('teacher', 'professor', 'professions', 'beginner', '/ˈtiːtʃər/', 'Person who teaches', 'My teacher is nice.', 'A minha professora é simpática.'),
('student', 'estudante', 'professions', 'beginner', '/ˈstuːdənt/', 'Person who studies', 'I am a student.', 'Sou estudante.'),
('doctor', 'médico', 'professions', 'beginner', '/ˈdɑːktər/', 'Medical professional', 'The doctor is busy.', 'O médico está ocupado.'),
('nurse', 'enfermeiro', 'professions', 'beginner', '/nɜːrs/', 'Medical assistant', 'The nurse is helpful.', 'A enfermeira é prestável.'),
('engineer', 'engenheiro', 'professions', 'beginner', '/ˌendʒɪˈnɪr/', 'Technical professional', 'He is an engineer.', 'Ele é engenheiro.'),
('lawyer', 'advogado', 'professions', 'beginner', '/ˈlɔːjər/', 'Legal professional', 'I need a lawyer.', 'Preciso de um advogado.'),
('police', 'polícia', 'professions', 'beginner', '/pəˈliːs/', 'Law enforcement', 'Call the police.', 'Chama a polícia.'),
('firefighter', 'bombeiro', 'professions', 'beginner', '/ˈfaɪərfaɪtər/', 'Fights fires', 'Firefighters are brave.', 'Os bombeiros são corajosos.'),
('cook', 'cozinheiro', 'professions', 'beginner', '/kʊk/', 'Person who cooks', 'He is a good cook.', 'Ele é um bom cozinheiro.'),
('waiter', 'empregado de mesa', 'professions', 'beginner', '/ˈweɪtər/', 'Serves food', 'The waiter is polite.', 'O empregado de mesa é educado.'),
('farmer', 'agricultor', 'professions', 'beginner', '/ˈfɑːrmər/', 'Works on farm', 'The farmer grows vegetables.', 'O agricultor cultiva vegetais.'),
('driver', 'motorista', 'professions', 'beginner', '/ˈdraɪvər/', 'Drives vehicles', 'A taxi driver.', 'Um motorista de táxi.'),
('pilot', 'piloto', 'professions', 'beginner', '/ˈpaɪlət/', 'Flies planes', 'She is a pilot.', 'Ela é piloto.'),
('dentist', 'dentista', 'professions', 'beginner', '/ˈdentɪst/', 'Treats teeth', 'I go to the dentist.', 'Vou ao dentista.'),
('artist', 'artista', 'professions', 'beginner', '/ˈɑːrtɪst/', 'Creates art', 'She is an artist.', 'Ela é artista.'),
('singer', 'cantor', 'professions', 'beginner', '/ˈsɪŋər/', 'Person who sings', 'A famous singer.', 'Um cantor famoso.'),
('actor', 'ator', 'professions', 'beginner', '/ˈæktər/', 'Performs in plays or films', 'A movie actor.', 'Um ator de cinema.'),
('writer', 'escritor', 'professions', 'beginner', '/ˈraɪtər/', 'Creates written works', 'A book writer.', 'Um escritor de livros.'),
('manager', 'gerente', 'professions', 'beginner', '/ˈmænɪdʒər/', 'Person in charge', 'The store manager.', 'O gerente da loja.'),
('secretary', 'secretário', 'professions', 'beginner', '/ˈsekrəteri/', 'Office assistant', 'My secretary helps me.', 'A minha secretária ajuda-me.'),
('businessman', 'empresário', 'professions', 'beginner', '/ˈbɪznəsmæn/', 'Person in business', 'A successful businessman.', 'Um empresário bem-sucedido.'),
('worker', 'trabalhador', 'professions', 'beginner', '/ˈwɜːrkər/', 'Person who works', 'A factory worker.', 'Um trabalhador de fábrica.'),
('boss', 'chefe', 'professions', 'beginner', '/bɔːs/', 'Person in charge', 'My boss is strict.', 'O meu chefe é rigoroso.'),
('job', 'emprego', 'professions', 'beginner', '/dʒɑːb/', 'Work position', 'I have a new job.', 'Tenho um novo emprego.'),
('career', 'carreira', 'professions', 'beginner', '/kəˈrɪr/', 'Professional life', 'A long career.', 'Uma longa carreira.'),
('salary', 'salário', 'professions', 'beginner', '/ˈsæləri/', 'Money for work', 'A good salary.', 'Um bom salário.'),

-- Clothing
('clothes', 'roupa', 'clothing', 'beginner', '/kloʊðz/', 'Items worn on body', 'Nice clothes.', 'Roupa bonita.'),
('shirt', 'camisa', 'clothing', 'beginner', '/ʃɜːrt/', 'Upper body garment', 'A white shirt.', 'Uma camisa branca.'),
('pants', 'calças', 'clothing', 'beginner', '/pænts/', 'Lower body garment', 'Blue pants.', 'Calças azuis.'),
('jeans', 'calças de ganga', 'clothing', 'beginner', '/dʒiːnz/', 'Casual pants', 'I wear jeans.', 'Uso calças de ganga.'),
('dress', 'vestido', 'clothing', 'beginner', '/dres/', 'Female garment', 'A beautiful dress.', 'Um vestido bonito.'),
('skirt', 'saia', 'clothing', 'beginner', '/skɜːrt/', 'Lower body female garment', 'A short skirt.', 'Uma saia curta.'),
('jacket', 'casaco', 'clothing', 'beginner', '/ˈdʒækɪt/', 'Outer garment', 'A leather jacket.', 'Um casaco de pele.'),
('coat', 'casaco comprido', 'clothing', 'beginner', '/koʊt/', 'Long outer garment', 'A warm coat.', 'Um casaco quente.'),
('sweater', 'camisola', 'clothing', 'beginner', '/ˈswetər/', 'Warm upper garment', 'A wool sweater.', 'Uma camisola de lã.'),
('suit', 'fato', 'clothing', 'beginner', '/suːt/', 'Formal outfit', 'A business suit.', 'Um fato de negócios.'),
('tie', 'gravata', 'clothing', 'beginner', '/taɪ/', 'Neck accessory', 'A silk tie.', 'Uma gravata de seda.'),
('shoes', 'sapatos', 'clothing', 'beginner', '/ʃuːz/', 'Footwear', 'New shoes.', 'Sapatos novos.'),
('boots', 'botas', 'clothing', 'beginner', '/buːts/', 'Tall footwear', 'Winter boots.', 'Botas de inverno.'),
('socks', 'meias', 'clothing', 'beginner', '/sɑːks/', 'Foot covering', 'White socks.', 'Meias brancas.'),
('hat', 'chapéu', 'clothing', 'beginner', '/hæt/', 'Head covering', 'A sun hat.', 'Um chapéu de sol.'),
('cap', 'boné', 'clothing', 'beginner', '/kæp/', 'Casual head covering', 'A baseball cap.', 'Um boné de basebol.'),
('gloves', 'luvas', 'clothing', 'beginner', '/ɡlʌvz/', 'Hand covering', 'Warm gloves.', 'Luvas quentes.'),
('scarf', 'cachecol', 'clothing', 'beginner', '/skɑːrf/', 'Neck covering', 'A wool scarf.', 'Um cachecol de lã.'),
('belt', 'cinto', 'clothing', 'beginner', '/belt/', 'Waist accessory', 'A leather belt.', 'Um cinto de couro.'),
('pocket', 'bolso', 'clothing', 'beginner', '/ˈpɑːkɪt/', 'Part of clothes for holding things', 'Put it in your pocket.', 'Põe no bolso.'),
('button', 'botão', 'clothing', 'beginner', '/ˈbʌtən/', 'Fastener on clothes', 'A missing button.', 'Um botão em falta.'),
('zipper', 'fecho', 'clothing', 'beginner', '/ˈzɪpər/', 'Closing device', 'Close the zipper.', 'Fecha o fecho.'),
('size', 'tamanho', 'clothing', 'beginner', '/saɪz/', 'Measurement of clothes', 'What is your size?', 'Qual é o teu tamanho?'),
('underwear', 'roupa interior', 'clothing', 'beginner', '/ˈʌndərwer/', 'Clothes worn under', 'Pack some underwear.', 'Leva roupa interior.'),
('pajamas', 'pijama', 'clothing', 'beginner', '/pəˈdʒɑːməz/', 'Sleeping clothes', 'Put on your pajamas.', 'Veste o pijama.'),
('uniform', 'uniforme', 'clothing', 'beginner', '/ˈjuːnɪfɔːrm/', 'Standard outfit', 'School uniform.', 'Uniforme escolar.'),

-- Animals
('dog', 'cão', 'animals', 'beginner', '/dɔːɡ/', 'Common pet', 'I have a dog.', 'Tenho um cão.'),
('cat', 'gato', 'animals', 'beginner', '/kæt/', 'Common pet', 'The cat is sleeping.', 'O gato está a dormir.'),
('bird', 'pássaro', 'animals', 'beginner', '/bɜːrd/', 'Flying animal', 'A beautiful bird.', 'Um pássaro bonito.'),
('horse', 'cavalo', 'animals', 'beginner', '/hɔːrs/', 'Large animal for riding', 'I can ride a horse.', 'Sei montar a cavalo.'),
('cow', 'vaca', 'animals', 'beginner', '/kaʊ/', 'Farm animal', 'Cows give milk.', 'As vacas dão leite.'),
('pig', 'porco', 'animals', 'beginner', '/pɪɡ/', 'Farm animal', 'Pigs are smart.', 'Os porcos são inteligentes.'),
('sheep', 'ovelha', 'animals', 'beginner', '/ʃiːp/', 'Wool animal', 'Sheep give wool.', 'As ovelhas dão lã.'),
('chicken', 'galinha', 'animals', 'beginner', '/ˈtʃɪkɪn/', 'Farm bird', 'Chickens lay eggs.', 'As galinhas põem ovos.'),
('duck', 'pato', 'animals', 'beginner', '/dʌk/', 'Water bird', 'Ducks can swim.', 'Os patos sabem nadar.'),
('rabbit', 'coelho', 'animals', 'beginner', '/ˈræbɪt/', 'Small furry animal', 'A white rabbit.', 'Um coelho branco.'),
('mouse', 'rato', 'animals', 'beginner', '/maʊs/', 'Small rodent', 'A tiny mouse.', 'Um ratinho pequeno.'),
('elephant', 'elefante', 'animals', 'beginner', '/ˈelɪfənt/', 'Large animal with trunk', 'Elephants are big.', 'Os elefantes são grandes.'),
('lion', 'leão', 'animals', 'beginner', '/ˈlaɪən/', 'King of animals', 'The lion roars.', 'O leão ruge.'),
('tiger', 'tigre', 'animals', 'beginner', '/ˈtaɪɡər/', 'Striped big cat', 'Tigers are strong.', 'Os tigres são fortes.'),
('bear', 'urso', 'animals', 'beginner', '/ber/', 'Large furry animal', 'A brown bear.', 'Um urso castanho.'),
('monkey', 'macaco', 'animals', 'beginner', '/ˈmʌŋki/', 'Climbing animal', 'Monkeys climb trees.', 'Os macacos trepam às árvores.'),
('snake', 'cobra', 'animals', 'beginner', '/sneɪk/', 'Legless reptile', 'I am afraid of snakes.', 'Tenho medo de cobras.'),
('frog', 'rã', 'animals', 'beginner', '/frɔːɡ/', 'Jumping amphibian', 'Frogs jump.', 'As rãs saltam.'),
('butterfly', 'borboleta', 'animals', 'beginner', '/ˈbʌtərflaɪ/', 'Flying insect', 'A colorful butterfly.', 'Uma borboleta colorida.'),
('bee', 'abelha', 'animals', 'beginner', '/biː/', 'Honey-making insect', 'Bees make honey.', 'As abelhas fazem mel.'),
('ant', 'formiga', 'animals', 'beginner', '/ænt/', 'Small insect', 'Ants are hardworking.', 'As formigas são trabalhadoras.'),
('spider', 'aranha', 'animals', 'beginner', '/ˈspaɪdər/', 'Eight-legged creature', 'A spider web.', 'Uma teia de aranha.'),
('shark', 'tubarão', 'animals', 'beginner', '/ʃɑːrk/', 'Ocean predator', 'Sharks are dangerous.', 'Os tubarões são perigosos.'),
('whale', 'baleia', 'animals', 'beginner', '/weɪl/', 'Large sea mammal', 'Whales are huge.', 'As baleias são enormes.'),
('dolphin', 'golfinho', 'animals', 'beginner', '/ˈdɑːlfɪn/', 'Intelligent sea mammal', 'Dolphins are friendly.', 'Os golfinhos são amigáveis.'),
('turtle', 'tartaruga', 'animals', 'beginner', '/ˈtɜːrtəl/', 'Shelled reptile', 'Turtles are slow.', 'As tartarugas são lentas.'),
('pet', 'animal de estimação', 'animals', 'beginner', '/pet/', 'Domesticated animal', 'Do you have a pet?', 'Tens um animal de estimação?'),
('animal', 'animal', 'animals', 'beginner', '/ˈænɪməl/', 'Living creature', 'I love animals.', 'Adoro animais.')

ON CONFLICT (word) DO NOTHING;
