-- Base Vocabulary - Beginner Level (Part 4: 200 words)
-- More verbs, pronouns, prepositions, question words, common expressions

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- More Common Verbs
('call', 'chamar/ligar', 'verbs', 'beginner', '/kɔːl/', 'To phone or name', 'Call me later.', 'Liga-me mais tarde.'),
('carry', 'carregar', 'verbs', 'beginner', '/ˈkæri/', 'To transport', 'Carry this bag.', 'Carrega este saco.'),
('catch', 'apanhar', 'verbs', 'beginner', '/kætʃ/', 'To capture', 'Catch the ball!', 'Apanha a bola!'),
('change', 'mudar', 'verbs', 'beginner', '/tʃeɪndʒ/', 'To make different', 'I need to change clothes.', 'Preciso de mudar de roupa.'),
('choose', 'escolher', 'verbs', 'beginner', '/tʃuːz/', 'To select', 'Choose one.', 'Escolhe um.'),
('clean', 'limpar', 'verbs', 'beginner', '/kliːn/', 'To make clean', 'Clean your room.', 'Limpa o teu quarto.'),
('cook', 'cozinhar', 'verbs', 'beginner', '/kʊk/', 'To prepare food', 'I can cook pasta.', 'Sei cozinhar massa.'),
('copy', 'copiar', 'verbs', 'beginner', '/ˈkɑːpi/', 'To duplicate', 'Copy this text.', 'Copia este texto.'),
('count', 'contar', 'verbs', 'beginner', '/kaʊnt/', 'To number', 'Count to ten.', 'Conta até dez.'),
('cry', 'chorar', 'verbs', 'beginner', '/kraɪ/', 'To shed tears', 'Do not cry.', 'Não chores.'),
('cut', 'cortar', 'verbs', 'beginner', '/kʌt/', 'To divide with knife', 'Cut the paper.', 'Corta o papel.'),
('dance', 'dançar', 'verbs', 'beginner', '/dæns/', 'To move to music', 'I love to dance.', 'Adoro dançar.'),
('draw', 'desenhar', 'verbs', 'beginner', '/drɔː/', 'To make pictures', 'Draw a picture.', 'Desenha um quadro.'),
('drive', 'conduzir', 'verbs', 'beginner', '/draɪv/', 'To operate a vehicle', 'I can drive.', 'Sei conduzir.'),
('drop', 'deixar cair', 'verbs', 'beginner', '/drɑːp/', 'To let fall', 'Do not drop it!', 'Não deixes cair!'),
('feel', 'sentir', 'verbs', 'beginner', '/fiːl/', 'To experience emotion', 'I feel happy.', 'Sinto-me feliz.'),
('fill', 'encher', 'verbs', 'beginner', '/fɪl/', 'To make full', 'Fill the glass.', 'Enche o copo.'),
('finish', 'terminar', 'verbs', 'beginner', '/ˈfɪnɪʃ/', 'To complete', 'Finish your homework.', 'Termina os trabalhos de casa.'),
('fix', 'consertar', 'verbs', 'beginner', '/fɪks/', 'To repair', 'Fix the car.', 'Conserta o carro.'),
('fly', 'voar', 'verbs', 'beginner', '/flaɪ/', 'To move through air', 'Birds can fly.', 'Os pássaros podem voar.'),
('follow', 'seguir', 'verbs', 'beginner', '/ˈfɑːloʊ/', 'To go after', 'Follow me.', 'Segue-me.'),
('forget', 'esquecer', 'verbs', 'beginner', '/fərˈɡet/', 'To not remember', 'I forgot my keys.', 'Esqueci as minhas chaves.'),
('grow', 'crescer', 'verbs', 'beginner', '/ɡroʊ/', 'To get bigger', 'Children grow fast.', 'As crianças crescem rápido.'),
('hide', 'esconder', 'verbs', 'beginner', '/haɪd/', 'To conceal', 'Hide and seek.', 'Esconde-esconde.'),
('hit', 'bater', 'verbs', 'beginner', '/hɪt/', 'To strike', 'Hit the ball.', 'Bate na bola.'),
('hold', 'segurar', 'verbs', 'beginner', '/hoʊld/', 'To grasp', 'Hold my hand.', 'Segura a minha mão.'),
('hope', 'esperar/desejar', 'verbs', 'beginner', '/hoʊp/', 'To wish', 'I hope so.', 'Espero que sim.'),
('hurt', 'magoar', 'verbs', 'beginner', '/hɜːrt/', 'To cause pain', 'It hurts.', 'Dói.'),
('invite', 'convidar', 'verbs', 'beginner', '/ɪnˈvaɪt/', 'To ask to come', 'I invite you.', 'Convido-te.'),
('join', 'juntar', 'verbs', 'beginner', '/dʒɔɪn/', 'To connect', 'Join us!', 'Junta-te a nós!'),
('jump', 'saltar', 'verbs', 'beginner', '/dʒʌmp/', 'To leap', 'Jump high!', 'Salta alto!'),
('keep', 'manter', 'verbs', 'beginner', '/kiːp/', 'To retain', 'Keep it safe.', 'Mantém-no seguro.'),
('kick', 'pontapear', 'verbs', 'beginner', '/kɪk/', 'To strike with foot', 'Kick the ball.', 'Chuta a bola.'),
('kill', 'matar', 'verbs', 'beginner', '/kɪl/', 'To end life', 'Do not kill insects.', 'Não mates insetos.'),
('kiss', 'beijar', 'verbs', 'beginner', '/kɪs/', 'To touch with lips', 'Kiss me goodbye.', 'Dá-me um beijo de despedida.'),
('laugh', 'rir', 'verbs', 'beginner', '/læf/', 'To express joy', 'She laughs a lot.', 'Ela ri muito.'),
('lose', 'perder', 'verbs', 'beginner', '/luːz/', 'To misplace', 'Do not lose your ticket.', 'Não percas o bilhete.'),
('meet', 'conhecer/encontrar', 'verbs', 'beginner', '/miːt/', 'To encounter', 'Nice to meet you.', 'Prazer em conhecer-te.'),
('miss', 'sentir falta', 'verbs', 'beginner', '/mɪs/', 'To feel absence', 'I miss you.', 'Tenho saudades tuas.'),
('move', 'mover', 'verbs', 'beginner', '/muːv/', 'To change position', 'Do not move.', 'Não te mexas.'),
('paint', 'pintar', 'verbs', 'beginner', '/peɪnt/', 'To apply color', 'Paint the wall.', 'Pinta a parede.'),
('pick', 'escolher/apanhar', 'verbs', 'beginner', '/pɪk/', 'To select or gather', 'Pick a card.', 'Escolhe uma carta.'),
('plan', 'planear', 'verbs', 'beginner', '/plæn/', 'To organize', 'Plan your trip.', 'Planeia a viagem.'),
('point', 'apontar', 'verbs', 'beginner', '/pɔɪnt/', 'To indicate', 'Point to the map.', 'Aponta para o mapa.'),
('practice', 'praticar', 'verbs', 'beginner', '/ˈpræktɪs/', 'To do repeatedly', 'Practice makes perfect.', 'A prática leva à perfeição.'),
('prepare', 'preparar', 'verbs', 'beginner', '/prɪˈper/', 'To make ready', 'Prepare dinner.', 'Prepara o jantar.'),
('promise', 'prometer', 'verbs', 'beginner', '/ˈprɑːmɪs/', 'To give word', 'I promise.', 'Eu prometo.'),
('pull', 'puxar', 'verbs', 'beginner', '/pʊl/', 'To draw toward', 'Pull the door.', 'Puxa a porta.'),
('push', 'empurrar', 'verbs', 'beginner', '/pʊʃ/', 'To press forward', 'Push the button.', 'Carrega no botão.'),
('reach', 'alcançar', 'verbs', 'beginner', '/riːtʃ/', 'To arrive at', 'Reach for the sky.', 'Alcança o céu.'),
('remember', 'lembrar', 'verbs', 'beginner', '/rɪˈmembər/', 'To recall', 'Remember to call.', 'Lembra-te de ligar.'),
('return', 'voltar/devolver', 'verbs', 'beginner', '/rɪˈtɜːrn/', 'To come back', 'I will return soon.', 'Voltarei em breve.'),
('save', 'salvar/poupar', 'verbs', 'beginner', '/seɪv/', 'To rescue or keep', 'Save money.', 'Poupa dinheiro.'),
('search', 'procurar', 'verbs', 'beginner', '/sɜːrtʃ/', 'To look for', 'Search online.', 'Procura online.'),
('send', 'enviar', 'verbs', 'beginner', '/send/', 'To dispatch', 'Send an email.', 'Envia um email.'),
('share', 'partilhar', 'verbs', 'beginner', '/ʃer/', 'To divide with others', 'Share with friends.', 'Partilha com amigos.'),
('show', 'mostrar', 'verbs', 'beginner', '/ʃoʊ/', 'To display', 'Show me.', 'Mostra-me.'),
('shut', 'fechar', 'verbs', 'beginner', '/ʃʌt/', 'To close', 'Shut the door.', 'Fecha a porta.'),
('sing', 'cantar', 'verbs', 'beginner', '/sɪŋ/', 'To make music with voice', 'Sing a song.', 'Canta uma canção.'),
('smell', 'cheirar', 'verbs', 'beginner', '/smel/', 'To perceive odor', 'Smell the flowers.', 'Cheira as flores.'),
('smile', 'sorrir', 'verbs', 'beginner', '/smaɪl/', 'To express happiness', 'Smile for the photo.', 'Sorri para a foto.'),
('spend', 'gastar', 'verbs', 'beginner', '/spend/', 'To use money or time', 'Do not spend too much.', 'Não gastes demais.'),
('stay', 'ficar', 'verbs', 'beginner', '/steɪ/', 'To remain', 'Stay here.', 'Fica aqui.'),
('swim', 'nadar', 'verbs', 'beginner', '/swɪm/', 'To move in water', 'I can swim.', 'Sei nadar.'),
('taste', 'provar', 'verbs', 'beginner', '/teɪst/', 'To try food', 'Taste this.', 'Prova isto.'),
('throw', 'atirar', 'verbs', 'beginner', '/θroʊ/', 'To propel', 'Throw the ball.', 'Atira a bola.'),
('touch', 'tocar', 'verbs', 'beginner', '/tʌtʃ/', 'To feel with hand', 'Do not touch.', 'Não toques.'),
('travel', 'viajar', 'verbs', 'beginner', '/ˈtrævəl/', 'To journey', 'I love to travel.', 'Adoro viajar.'),
('turn', 'virar', 'verbs', 'beginner', '/tɜːrn/', 'To rotate', 'Turn left.', 'Vira à esquerda.'),
('understand', 'compreender', 'verbs', 'beginner', '/ˌʌndərˈstænd/', 'To comprehend', 'I understand.', 'Eu compreendo.'),
('use', 'usar', 'verbs', 'beginner', '/juːz/', 'To employ', 'Use your phone.', 'Usa o telemóvel.'),
('visit', 'visitar', 'verbs', 'beginner', '/ˈvɪzɪt/', 'To go see', 'Visit your grandparents.', 'Visita os teus avós.'),
('wake', 'acordar', 'verbs', 'beginner', '/weɪk/', 'To stop sleeping', 'Wake up early.', 'Acorda cedo.'),
('wash', 'lavar', 'verbs', 'beginner', '/wɑːʃ/', 'To clean with water', 'Wash your hands.', 'Lava as mãos.'),
('wear', 'vestir', 'verbs', 'beginner', '/wer/', 'To have on body', 'Wear a coat.', 'Veste um casaco.'),
('win', 'ganhar', 'verbs', 'beginner', '/wɪn/', 'To be victorious', 'I want to win.', 'Quero ganhar.'),
('worry', 'preocupar', 'verbs', 'beginner', '/ˈwɜːri/', 'To feel anxious', 'Do not worry.', 'Não te preocupes.'),

-- Pronouns
('I', 'eu', 'pronouns', 'beginner', '/aɪ/', 'First person singular', 'I am here.', 'Eu estou aqui.'),
('you', 'tu/você', 'pronouns', 'beginner', '/juː/', 'Second person', 'You are nice.', 'Tu és simpático.'),
('he', 'ele', 'pronouns', 'beginner', '/hiː/', 'Third person male', 'He is tall.', 'Ele é alto.'),
('she', 'ela', 'pronouns', 'beginner', '/ʃiː/', 'Third person female', 'She is smart.', 'Ela é inteligente.'),
('it', 'isso/ele/ela', 'pronouns', 'beginner', '/ɪt/', 'Third person neutral', 'It is cold.', 'Está frio.'),
('we', 'nós', 'pronouns', 'beginner', '/wiː/', 'First person plural', 'We are friends.', 'Nós somos amigos.'),
('they', 'eles/elas', 'pronouns', 'beginner', '/ðeɪ/', 'Third person plural', 'They are happy.', 'Eles estão felizes.'),
('me', 'mim/me', 'pronouns', 'beginner', '/miː/', 'Object form of I', 'Tell me.', 'Diz-me.'),
('him', 'ele/o', 'pronouns', 'beginner', '/hɪm/', 'Object form of he', 'I saw him.', 'Eu vi-o.'),
('her', 'ela/a', 'pronouns', 'beginner', '/hɜːr/', 'Object form of she', 'I called her.', 'Eu liguei-lhe.'),
('us', 'nós', 'pronouns', 'beginner', '/ʌs/', 'Object form of we', 'Join us.', 'Junta-te a nós.'),
('them', 'eles/elas', 'pronouns', 'beginner', '/ðem/', 'Object form of they', 'I saw them.', 'Eu vi-os.'),
('my', 'meu/minha', 'pronouns', 'beginner', '/maɪ/', 'Possessive of I', 'My book.', 'O meu livro.'),
('your', 'teu/seu', 'pronouns', 'beginner', '/jʊr/', 'Possessive of you', 'Your house.', 'A tua casa.'),
('his', 'dele', 'pronouns', 'beginner', '/hɪz/', 'Possessive of he', 'His car.', 'O carro dele.'),
('our', 'nosso', 'pronouns', 'beginner', '/aʊr/', 'Possessive of we', 'Our family.', 'A nossa família.'),
('their', 'deles/delas', 'pronouns', 'beginner', '/ðer/', 'Possessive of they', 'Their house.', 'A casa deles.'),
('this', 'isto/este', 'pronouns', 'beginner', '/ðɪs/', 'Near demonstrative', 'This is good.', 'Isto é bom.'),
('that', 'isso/aquele', 'pronouns', 'beginner', '/ðæt/', 'Far demonstrative', 'That is nice.', 'Isso é bonito.'),
('these', 'estes/estas', 'pronouns', 'beginner', '/ðiːz/', 'Plural of this', 'These are mine.', 'Estes são meus.'),
('those', 'esses/aqueles', 'pronouns', 'beginner', '/ðoʊz/', 'Plural of that', 'Those are big.', 'Aqueles são grandes.'),
('what', 'o quê', 'pronouns', 'beginner', '/wɑːt/', 'Question word', 'What is this?', 'O que é isto?'),
('who', 'quem', 'pronouns', 'beginner', '/huː/', 'Question for person', 'Who is there?', 'Quem está aí?'),
('which', 'qual', 'pronouns', 'beginner', '/wɪtʃ/', 'Question for choice', 'Which one?', 'Qual deles?'),
('where', 'onde', 'pronouns', 'beginner', '/wer/', 'Question for place', 'Where are you?', 'Onde estás?'),
('when', 'quando', 'pronouns', 'beginner', '/wen/', 'Question for time', 'When is it?', 'Quando é?'),
('why', 'porquê', 'pronouns', 'beginner', '/waɪ/', 'Question for reason', 'Why not?', 'Porque não?'),
('how', 'como', 'pronouns', 'beginner', '/haʊ/', 'Question for manner', 'How are you?', 'Como estás?'),
('something', 'alguma coisa', 'pronouns', 'beginner', '/ˈsʌmθɪŋ/', 'Unknown thing', 'I need something.', 'Preciso de alguma coisa.'),
('nothing', 'nada', 'pronouns', 'beginner', '/ˈnʌθɪŋ/', 'No thing', 'Nothing happened.', 'Nada aconteceu.'),
('everything', 'tudo', 'pronouns', 'beginner', '/ˈevriθɪŋ/', 'All things', 'Everything is fine.', 'Está tudo bem.'),
('someone', 'alguém', 'pronouns', 'beginner', '/ˈsʌmwʌn/', 'Unknown person', 'Someone called.', 'Alguém ligou.'),
('anyone', 'qualquer pessoa', 'pronouns', 'beginner', '/ˈeniwʌn/', 'Any person', 'Does anyone know?', 'Alguém sabe?'),
('everyone', 'toda a gente', 'pronouns', 'beginner', '/ˈevriwʌn/', 'All people', 'Everyone is here.', 'Toda a gente está aqui.'),
('nobody', 'ninguém', 'pronouns', 'beginner', '/ˈnoʊbɑːdi/', 'No person', 'Nobody knows.', 'Ninguém sabe.'),
('myself', 'eu mesmo', 'pronouns', 'beginner', '/maɪˈself/', 'Reflexive I', 'I did it myself.', 'Eu fiz isso sozinho.'),

-- Prepositions
('in', 'em/dentro', 'prepositions', 'beginner', '/ɪn/', 'Inside of', 'In the box.', 'Dentro da caixa.'),
('on', 'em/sobre', 'prepositions', 'beginner', '/ɑːn/', 'On top of', 'On the table.', 'Em cima da mesa.'),
('at', 'em/a', 'prepositions', 'beginner', '/æt/', 'At a location', 'At home.', 'Em casa.'),
('to', 'para/a', 'prepositions', 'beginner', '/tuː/', 'Direction', 'Go to school.', 'Vai para a escola.'),
('from', 'de/desde', 'prepositions', 'beginner', '/frʌm/', 'Origin', 'From Portugal.', 'De Portugal.'),
('by', 'por/junto', 'prepositions', 'beginner', '/baɪ/', 'Near or by means of', 'By the window.', 'Junto à janela.'),
('with', 'com', 'prepositions', 'beginner', '/wɪð/', 'Together', 'With friends.', 'Com amigos.'),
('without', 'sem', 'prepositions', 'beginner', '/wɪˈðaʊt/', 'Not having', 'Without sugar.', 'Sem açúcar.'),
('for', 'para/por', 'prepositions', 'beginner', '/fɔːr/', 'Purpose', 'For you.', 'Para ti.'),
('about', 'sobre/acerca', 'prepositions', 'beginner', '/əˈbaʊt/', 'Concerning', 'About the book.', 'Sobre o livro.'),
('after', 'depois', 'prepositions', 'beginner', '/ˈæftər/', 'Following', 'After lunch.', 'Depois do almoço.'),
('before', 'antes', 'prepositions', 'beginner', '/bɪˈfɔːr/', 'Prior to', 'Before dinner.', 'Antes do jantar.'),
('between', 'entre', 'prepositions', 'beginner', '/bɪˈtwiːn/', 'In the middle', 'Between us.', 'Entre nós.'),
('behind', 'atrás', 'prepositions', 'beginner', '/bɪˈhaɪnd/', 'At the back', 'Behind the door.', 'Atrás da porta.'),
('under', 'debaixo', 'prepositions', 'beginner', '/ˈʌndər/', 'Below', 'Under the bed.', 'Debaixo da cama.'),
('over', 'sobre/acima', 'prepositions', 'beginner', '/ˈoʊvər/', 'Above', 'Over the bridge.', 'Sobre a ponte.'),
('above', 'acima', 'prepositions', 'beginner', '/əˈbʌv/', 'Higher than', 'Above the clouds.', 'Acima das nuvens.'),
('below', 'abaixo', 'prepositions', 'beginner', '/bɪˈloʊ/', 'Lower than', 'Below zero.', 'Abaixo de zero.'),
('next to', 'ao lado de', 'prepositions', 'beginner', '/nekst tuː/', 'Beside', 'Next to the bank.', 'Ao lado do banco.'),
('near', 'perto', 'prepositions', 'beginner', '/nɪr/', 'Close to', 'Near the station.', 'Perto da estação.'),
('far', 'longe', 'prepositions', 'beginner', '/fɑːr/', 'At a distance', 'Far from here.', 'Longe daqui.'),
('into', 'para dentro', 'prepositions', 'beginner', '/ˈɪntuː/', 'To inside', 'Go into the room.', 'Entra no quarto.'),
('out of', 'fora de', 'prepositions', 'beginner', '/aʊt ʌv/', 'From inside', 'Out of the house.', 'Fora de casa.'),
('through', 'através', 'prepositions', 'beginner', '/θruː/', 'From one side to another', 'Through the window.', 'Através da janela.'),
('around', 'à volta', 'prepositions', 'beginner', '/əˈraʊnd/', 'Surrounding', 'Around the city.', 'À volta da cidade.'),
('along', 'ao longo', 'prepositions', 'beginner', '/əˈlɔːŋ/', 'Following length', 'Along the river.', 'Ao longo do rio.'),
('during', 'durante', 'prepositions', 'beginner', '/ˈdʊrɪŋ/', 'Throughout', 'During the night.', 'Durante a noite.'),
('until', 'até', 'prepositions', 'beginner', '/ənˈtɪl/', 'Up to time', 'Until tomorrow.', 'Até amanhã.'),
('since', 'desde', 'prepositions', 'beginner', '/sɪns/', 'From time', 'Since Monday.', 'Desde segunda-feira.'),
('against', 'contra', 'prepositions', 'beginner', '/əˈɡenst/', 'In opposition', 'Against the wall.', 'Contra a parede.'),

-- Common Expressions
('of course', 'claro', 'expressions', 'beginner', '/əv kɔːrs/', 'Certainly', 'Of course I can help.', 'Claro que posso ajudar.'),
('I think', 'eu acho', 'expressions', 'beginner', '/aɪ θɪŋk/', 'In my opinion', 'I think it is good.', 'Eu acho que é bom.'),
('I know', 'eu sei', 'expressions', 'beginner', '/aɪ noʊ/', 'I have knowledge', 'I know the answer.', 'Eu sei a resposta.'),
('I do not know', 'não sei', 'expressions', 'beginner', '/aɪ doʊnt noʊ/', 'I lack knowledge', 'I do not know yet.', 'Ainda não sei.'),
('that is right', 'isso mesmo', 'expressions', 'beginner', '/ðæt ɪz raɪt/', 'Correct', 'That is right!', 'Isso mesmo!'),
('I am sorry', 'desculpa', 'expressions', 'beginner', '/aɪ æm ˈsɔːri/', 'Apologizing', 'I am sorry for that.', 'Desculpa por isso.'),
('no problem', 'sem problema', 'expressions', 'beginner', '/noʊ ˈprɑːbləm/', 'It is okay', 'No problem at all.', 'Sem problema nenhum.'),
('see you', 'até já', 'expressions', 'beginner', '/siː juː/', 'Goodbye', 'See you later!', 'Até logo!'),
('take care', 'cuida-te', 'expressions', 'beginner', '/teɪk ker/', 'Be careful', 'Take care of yourself.', 'Cuida-te.'),
('have fun', 'diverte-te', 'expressions', 'beginner', '/hæv fʌn/', 'Enjoy yourself', 'Have fun at the party!', 'Diverte-te na festa!'),
('let us go', 'vamos', 'expressions', 'beginner', '/lets ɡoʊ/', 'We should go', 'Let us go home.', 'Vamos para casa.'),
('come on', 'vá lá', 'expressions', 'beginner', '/kʌm ɑːn/', 'Encouragement', 'Come on, try again!', 'Vá lá, tenta outra vez!'),
('well done', 'muito bem', 'expressions', 'beginner', '/wel dʌn/', 'Good job', 'Well done!', 'Muito bem!'),
('be careful', 'tem cuidado', 'expressions', 'beginner', '/biː ˈkerfl/', 'Warning', 'Be careful on the road.', 'Tem cuidado na estrada.'),
('I agree', 'concordo', 'expressions', 'beginner', '/aɪ əˈɡriː/', 'Same opinion', 'I totally agree.', 'Concordo totalmente.'),
('I disagree', 'discordo', 'expressions', 'beginner', '/aɪ ˌdɪsəˈɡriː/', 'Different opinion', 'I disagree with you.', 'Discordo de ti.'),
('it depends', 'depende', 'expressions', 'beginner', '/ɪt dɪˈpendz/', 'Conditional', 'It depends on the weather.', 'Depende do tempo.'),
('I do not care', 'não me importo', 'expressions', 'beginner', '/aɪ doʊnt ker/', 'Indifference', 'I do not care about that.', 'Não me importo com isso.'),
('never mind', 'não faz mal', 'expressions', 'beginner', '/ˈnevər maɪnd/', 'Forget it', 'Never mind, it is okay.', 'Não faz mal, está bem.')

ON CONFLICT (word) DO UPDATE SET
  translation = EXCLUDED.translation,
  category = EXCLUDED.category,
  difficulty = EXCLUDED.difficulty,
  pronunciation = EXCLUDED.pronunciation,
  definition = EXCLUDED.definition,
  example_sentence = EXCLUDED.example_sentence,
  example_translation = EXCLUDED.example_translation,
  updated_at = now();
