-- Base Vocabulary - Beginner Level (Part 5: 200 words)
-- School, Technology, Nature, Sports, Emotions

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- School & Education
('class', 'aula/turma', 'education', 'beginner', '/klæs/', 'Lesson or group of students', 'I have class at 9.', 'Tenho aula às 9.'),
('classroom', 'sala de aula', 'education', 'beginner', '/ˈklæsruːm/', 'Room for teaching', 'The classroom is big.', 'A sala de aula é grande.'),
('lesson', 'lição', 'education', 'beginner', '/ˈlesən/', 'Teaching session', 'An English lesson.', 'Uma lição de inglês.'),
('homework', 'trabalhos de casa', 'education', 'beginner', '/ˈhoʊmwɜːrk/', 'School work at home', 'I forgot my homework.', 'Esqueci os trabalhos de casa.'),
('test', 'teste', 'education', 'beginner', '/test/', 'Examination', 'I have a test tomorrow.', 'Tenho um teste amanhã.'),
('exam', 'exame', 'education', 'beginner', '/ɪɡˈzæm/', 'Formal test', 'The final exam.', 'O exame final.'),
('question', 'pergunta', 'education', 'beginner', '/ˈkwestʃən/', 'Something asked', 'A difficult question.', 'Uma pergunta difícil.'),
('answer', 'resposta', 'education', 'beginner', '/ˈænsər/', 'Response', 'The correct answer.', 'A resposta correta.'),
('subject', 'disciplina', 'education', 'beginner', '/ˈsʌbdʒekt/', 'Topic of study', 'My favorite subject.', 'A minha disciplina favorita.'),
('math', 'matemática', 'education', 'beginner', '/mæθ/', 'Study of numbers', 'I like math.', 'Gosto de matemática.'),
('science', 'ciência', 'education', 'beginner', '/ˈsaɪəns/', 'Study of nature', 'Science is interesting.', 'A ciência é interessante.'),
('history', 'história', 'education', 'beginner', '/ˈhɪstəri/', 'Study of past', 'I study history.', 'Estudo história.'),
('geography', 'geografia', 'education', 'beginner', '/dʒiˈɑːɡrəfi/', 'Study of places', 'Geography class.', 'Aula de geografia.'),
('English', 'inglês', 'education', 'beginner', '/ˈɪŋɡlɪʃ/', 'Language', 'I study English.', 'Estudo inglês.'),
('notebook', 'caderno', 'education', 'beginner', '/ˈnoʊtbʊk/', 'Book for notes', 'Open your notebook.', 'Abre o caderno.'),
('dictionary', 'dicionário', 'education', 'beginner', '/ˈdɪkʃəneri/', 'Word reference', 'Use a dictionary.', 'Usa um dicionário.'),
('page', 'página', 'education', 'beginner', '/peɪdʒ/', 'Sheet in a book', 'Turn the page.', 'Vira a página.'),
('word', 'palavra', 'education', 'beginner', '/wɜːrd/', 'Unit of language', 'A new word.', 'Uma palavra nova.'),
('sentence', 'frase', 'education', 'beginner', '/ˈsentəns/', 'Group of words', 'Write a sentence.', 'Escreve uma frase.'),
('letter', 'letra/carta', 'education', 'beginner', '/ˈletər/', 'Alphabet character or mail', 'The letter A.', 'A letra A.'),
('number', 'número', 'education', 'beginner', '/ˈnʌmbər/', 'Mathematical symbol', 'Pick a number.', 'Escolhe um número.'),
('grade', 'nota', 'education', 'beginner', '/ɡreɪd/', 'Score', 'I got a good grade.', 'Tive uma boa nota.'),
('mistake', 'erro', 'education', 'beginner', '/mɪˈsteɪk/', 'Error', 'I made a mistake.', 'Cometi um erro.'),
('example', 'exemplo', 'education', 'beginner', '/ɪɡˈzæmpəl/', 'Sample', 'For example.', 'Por exemplo.'),
('idea', 'ideia', 'education', 'beginner', '/aɪˈdiːə/', 'Thought', 'A good idea.', 'Uma boa ideia.'),

-- Technology
('internet', 'internet', 'technology', 'beginner', '/ˈɪntərnet/', 'Global network', 'I use the internet.', 'Uso a internet.'),
('email', 'email', 'technology', 'beginner', '/ˈiːmeɪl/', 'Electronic mail', 'Send me an email.', 'Envia-me um email.'),
('website', 'website', 'technology', 'beginner', '/ˈwebsaɪt/', 'Internet page', 'Visit our website.', 'Visita o nosso website.'),
('password', 'palavra-passe', 'technology', 'beginner', '/ˈpæswɜːrd/', 'Secret code', 'Change your password.', 'Muda a palavra-passe.'),
('message', 'mensagem', 'technology', 'beginner', '/ˈmesɪdʒ/', 'Communication', 'I got your message.', 'Recebi a tua mensagem.'),
('video', 'vídeo', 'technology', 'beginner', '/ˈvɪdioʊ/', 'Moving images', 'Watch a video.', 'Vê um vídeo.'),
('photo', 'foto', 'technology', 'beginner', '/ˈfoʊtoʊ/', 'Picture', 'Take a photo.', 'Tira uma foto.'),
('music', 'música', 'technology', 'beginner', '/ˈmjuːzɪk/', 'Sound art', 'I listen to music.', 'Ouço música.'),
('movie', 'filme', 'technology', 'beginner', '/ˈmuːvi/', 'Film', 'Watch a movie.', 'Vê um filme.'),
('screen', 'ecrã', 'technology', 'beginner', '/skriːn/', 'Display surface', 'A big screen.', 'Um ecrã grande.'),
('keyboard', 'teclado', 'technology', 'beginner', '/ˈkiːbɔːrd/', 'Input device', 'Type on the keyboard.', 'Escreve no teclado.'),
('mouse', 'rato', 'technology', 'beginner', '/maʊs/', 'Pointing device', 'Click the mouse.', 'Clica no rato.'),
('printer', 'impressora', 'technology', 'beginner', '/ˈprɪntər/', 'Printing device', 'The printer is broken.', 'A impressora está avariada.'),
('battery', 'bateria', 'technology', 'beginner', '/ˈbætəri/', 'Power source', 'Low battery.', 'Bateria fraca.'),
('charger', 'carregador', 'technology', 'beginner', '/ˈtʃɑːrdʒər/', 'Device for charging', 'I need a charger.', 'Preciso de um carregador.'),

-- Nature & Environment
('tree', 'árvore', 'nature', 'beginner', '/triː/', 'Large plant', 'A tall tree.', 'Uma árvore alta.'),
('flower', 'flor', 'nature', 'beginner', '/ˈflaʊər/', 'Plant blossom', 'A beautiful flower.', 'Uma flor bonita.'),
('grass', 'relva', 'nature', 'beginner', '/ɡræs/', 'Green ground cover', 'Sit on the grass.', 'Senta na relva.'),
('plant', 'planta', 'nature', 'beginner', '/plænt/', 'Living organism', 'Water the plants.', 'Rega as plantas.'),
('leaf', 'folha', 'nature', 'beginner', '/liːf/', 'Part of plant', 'A green leaf.', 'Uma folha verde.'),
('forest', 'floresta', 'nature', 'beginner', '/ˈfɔːrɪst/', 'Area with trees', 'A dense forest.', 'Uma floresta densa.'),
('mountain', 'montanha', 'nature', 'beginner', '/ˈmaʊntən/', 'High land', 'Climb a mountain.', 'Subir uma montanha.'),
('river', 'rio', 'nature', 'beginner', '/ˈrɪvər/', 'Flowing water', 'A long river.', 'Um rio longo.'),
('lake', 'lago', 'nature', 'beginner', '/leɪk/', 'Body of water', 'Swim in the lake.', 'Nadar no lago.'),
('sea', 'mar', 'nature', 'beginner', '/siː/', 'Salt water body', 'The sea is calm.', 'O mar está calmo.'),
('ocean', 'oceano', 'nature', 'beginner', '/ˈoʊʃən/', 'Large water body', 'The Pacific Ocean.', 'O Oceano Pacífico.'),
('island', 'ilha', 'nature', 'beginner', '/ˈaɪlənd/', 'Land surrounded by water', 'A tropical island.', 'Uma ilha tropical.'),
('sand', 'areia', 'nature', 'beginner', '/sænd/', 'Beach material', 'Play in the sand.', 'Brincar na areia.'),
('rock', 'rocha', 'nature', 'beginner', '/rɑːk/', 'Hard mineral', 'A big rock.', 'Uma rocha grande.'),
('stone', 'pedra', 'nature', 'beginner', '/stoʊn/', 'Small rock', 'Throw a stone.', 'Atira uma pedra.'),
('air', 'ar', 'nature', 'beginner', '/er/', 'Atmosphere', 'Fresh air.', 'Ar fresco.'),
('fire', 'fogo', 'nature', 'beginner', '/ˈfaɪər/', 'Flames', 'Make a fire.', 'Faz uma fogueira.'),
('earth', 'terra', 'nature', 'beginner', '/ɜːrθ/', 'Soil or planet', 'The Earth is round.', 'A Terra é redonda.'),
('moon', 'lua', 'nature', 'beginner', '/muːn/', 'Earth satellite', 'Full moon tonight.', 'Lua cheia esta noite.'),
('star', 'estrela', 'nature', 'beginner', '/stɑːr/', 'Light in sky', 'Count the stars.', 'Conta as estrelas.'),
('world', 'mundo', 'nature', 'beginner', '/wɜːrld/', 'The Earth', 'Around the world.', 'À volta do mundo.'),
('environment', 'ambiente', 'nature', 'beginner', '/ɪnˈvaɪrənmənt/', 'Surroundings', 'Protect the environment.', 'Protege o ambiente.'),
('pollution', 'poluição', 'nature', 'beginner', '/pəˈluːʃən/', 'Contamination', 'Air pollution.', 'Poluição do ar.'),

-- Sports & Activities
('sport', 'desporto', 'sports', 'beginner', '/spɔːrt/', 'Physical activity', 'I love sports.', 'Adoro desporto.'),
('football', 'futebol', 'sports', 'beginner', '/ˈfʊtbɔːl/', 'Ball sport', 'Play football.', 'Jogar futebol.'),
('basketball', 'basquetebol', 'sports', 'beginner', '/ˈbæskɪtbɔːl/', 'Ball sport', 'Basketball game.', 'Jogo de basquetebol.'),
('tennis', 'ténis', 'sports', 'beginner', '/ˈtenɪs/', 'Racket sport', 'Play tennis.', 'Jogar ténis.'),
('swimming', 'natação', 'sports', 'beginner', '/ˈswɪmɪŋ/', 'Water activity', 'I enjoy swimming.', 'Gosto de natação.'),
('running', 'corrida', 'sports', 'beginner', '/ˈrʌnɪŋ/', 'Foot activity', 'Go running.', 'Ir correr.'),
('exercise', 'exercício', 'sports', 'beginner', '/ˈeksərsaɪz/', 'Physical activity', 'Do exercise daily.', 'Faz exercício diariamente.'),
('gym', 'ginásio', 'sports', 'beginner', '/dʒɪm/', 'Exercise place', 'Go to the gym.', 'Ir ao ginásio.'),
('team', 'equipa', 'sports', 'beginner', '/tiːm/', 'Group playing together', 'A great team.', 'Uma grande equipa.'),
('player', 'jogador', 'sports', 'beginner', '/ˈpleɪər/', 'Person who plays', 'A good player.', 'Um bom jogador.'),
('match', 'jogo/partida', 'sports', 'beginner', '/mætʃ/', 'Game', 'Football match.', 'Jogo de futebol.'),
('score', 'pontuação', 'sports', 'beginner', '/skɔːr/', 'Points', 'Final score.', 'Pontuação final.'),
('goal', 'golo/objetivo', 'sports', 'beginner', '/ɡoʊl/', 'Target or score', 'Score a goal.', 'Marcar um golo.'),
('race', 'corrida', 'sports', 'beginner', '/reɪs/', 'Competition', 'A running race.', 'Uma corrida.'),
('hobby', 'passatempo', 'sports', 'beginner', '/ˈhɑːbi/', 'Leisure activity', 'Reading is my hobby.', 'Ler é o meu passatempo.'),
('vacation', 'férias', 'sports', 'beginner', '/veɪˈkeɪʃən/', 'Time off', 'Summer vacation.', 'Férias de verão.'),
('holiday', 'feriado', 'sports', 'beginner', '/ˈhɑːlədeɪ/', 'Celebration day', 'A national holiday.', 'Um feriado nacional.'),
('party', 'festa', 'sports', 'beginner', '/ˈpɑːrti/', 'Celebration', 'Birthday party.', 'Festa de aniversário.'),
('birthday', 'aniversário', 'sports', 'beginner', '/ˈbɜːrθdeɪ/', 'Birth anniversary', 'Happy birthday!', 'Feliz aniversário!'),
('wedding', 'casamento', 'sports', 'beginner', '/ˈwedɪŋ/', 'Marriage ceremony', 'A beautiful wedding.', 'Um casamento bonito.'),

-- Emotions & Feelings
('feeling', 'sentimento', 'emotions', 'beginner', '/ˈfiːlɪŋ/', 'Emotion', 'A good feeling.', 'Um bom sentimento.'),
('happiness', 'felicidade', 'emotions', 'beginner', '/ˈhæpinəs/', 'State of joy', 'Full of happiness.', 'Cheio de felicidade.'),
('sadness', 'tristeza', 'emotions', 'beginner', '/ˈsædnəs/', 'State of sorrow', 'Deep sadness.', 'Tristeza profunda.'),
('anger', 'raiva', 'emotions', 'beginner', '/ˈæŋɡər/', 'State of fury', 'Control your anger.', 'Controla a tua raiva.'),
('fear', 'medo', 'emotions', 'beginner', '/fɪr/', 'Feeling of danger', 'Face your fears.', 'Enfrenta os teus medos.'),
('love', 'amor', 'emotions', 'beginner', '/lʌv/', 'Deep affection', 'True love.', 'Amor verdadeiro.'),
('hate', 'ódio', 'emotions', 'beginner', '/heɪt/', 'Intense dislike', 'I hate lies.', 'Odeio mentiras.'),
('hope', 'esperança', 'emotions', 'beginner', '/hoʊp/', 'Wish for future', 'Never lose hope.', 'Nunca percas a esperança.'),
('peace', 'paz', 'emotions', 'beginner', '/piːs/', 'Calm state', 'World peace.', 'Paz mundial.'),
('fun', 'diversão', 'emotions', 'beginner', '/fʌn/', 'Enjoyment', 'Have fun!', 'Diverte-te!'),
('joy', 'alegria', 'emotions', 'beginner', '/dʒɔɪ/', 'Great happiness', 'Tears of joy.', 'Lágrimas de alegria.'),
('pain', 'dor', 'emotions', 'beginner', '/peɪn/', 'Physical or emotional hurt', 'No pain no gain.', 'Sem dor não há ganho.'),
('stress', 'stress', 'emotions', 'beginner', '/stres/', 'Mental tension', 'Too much stress.', 'Demasiado stress.'),
('surprise', 'surpresa', 'emotions', 'beginner', '/sərˈpraɪz/', 'Unexpected event', 'What a surprise!', 'Que surpresa!'),
('excitement', 'entusiasmo', 'emotions', 'beginner', '/ɪkˈsaɪtmənt/', 'Eager anticipation', 'Full of excitement.', 'Cheio de entusiasmo.'),

-- Miscellaneous Common Words
('thing', 'coisa', 'general', 'beginner', '/θɪŋ/', 'Object', 'What is this thing?', 'O que é esta coisa?'),
('person', 'pessoa', 'general', 'beginner', '/ˈpɜːrsən/', 'Human being', 'A nice person.', 'Uma pessoa simpática.'),
('people', 'pessoas', 'general', 'beginner', '/ˈpiːpəl/', 'Humans', 'Many people.', 'Muitas pessoas.'),
('man', 'homem', 'general', 'beginner', '/mæn/', 'Adult male', 'A tall man.', 'Um homem alto.'),
('woman', 'mulher', 'general', 'beginner', '/ˈwʊmən/', 'Adult female', 'A kind woman.', 'Uma mulher gentil.'),
('boy', 'rapaz', 'general', 'beginner', '/bɔɪ/', 'Young male', 'A little boy.', 'Um rapaz pequeno.'),
('girl', 'rapariga', 'general', 'beginner', '/ɡɜːrl/', 'Young female', 'A smart girl.', 'Uma rapariga inteligente.'),
('friend', 'amigo', 'general', 'beginner', '/frend/', 'Close companion', 'My best friend.', 'O meu melhor amigo.'),
('name', 'nome', 'general', 'beginner', '/neɪm/', 'Word for identification', 'What is your name?', 'Qual é o teu nome?'),
('age', 'idade', 'general', 'beginner', '/eɪdʒ/', 'How old', 'What is your age?', 'Qual é a tua idade?'),
('life', 'vida', 'general', 'beginner', '/laɪf/', 'Existence', 'A good life.', 'Uma boa vida.'),
('death', 'morte', 'general', 'beginner', '/deθ/', 'End of life', 'Life and death.', 'Vida e morte.'),
('dream', 'sonho', 'general', 'beginner', '/driːm/', 'Sleep vision or aspiration', 'Follow your dreams.', 'Segue os teus sonhos.'),
('truth', 'verdade', 'general', 'beginner', '/truːθ/', 'What is real', 'Tell the truth.', 'Diz a verdade.'),
('lie', 'mentira', 'general', 'beginner', '/laɪ/', 'False statement', 'Do not tell lies.', 'Não digas mentiras.'),
('problem', 'problema', 'general', 'beginner', '/ˈprɑːbləm/', 'Difficulty', 'No problem.', 'Sem problema.'),
('reason', 'razão', 'general', 'beginner', '/ˈriːzən/', 'Explanation', 'For this reason.', 'Por esta razão.'),
('way', 'caminho/maneira', 'general', 'beginner', '/weɪ/', 'Path or method', 'This way please.', 'Por aqui, por favor.'),
('place', 'lugar', 'general', 'beginner', '/pleɪs/', 'Location', 'A nice place.', 'Um lugar agradável.'),
('part', 'parte', 'general', 'beginner', '/pɑːrt/', 'Portion', 'Part of the plan.', 'Parte do plano.'),
('side', 'lado', 'general', 'beginner', '/saɪd/', 'Edge or aspect', 'On this side.', 'Deste lado.'),
('point', 'ponto', 'general', 'beginner', '/pɔɪnt/', 'Location or idea', 'Good point.', 'Bom ponto.'),
('kind', 'tipo', 'general', 'beginner', '/kaɪnd/', 'Type', 'What kind?', 'Que tipo?'),
('lot', 'muito', 'general', 'beginner', '/lɑːt/', 'Large amount', 'A lot of work.', 'Muito trabalho.'),
('end', 'fim', 'general', 'beginner', '/end/', 'Final part', 'The end.', 'O fim.'),
('beginning', 'início', 'general', 'beginner', '/bɪˈɡɪnɪŋ/', 'Start', 'In the beginning.', 'No início.'),
('middle', 'meio', 'general', 'beginner', '/ˈmɪdəl/', 'Center', 'In the middle.', 'No meio.'),
('top', 'topo', 'general', 'beginner', '/tɑːp/', 'Highest part', 'At the top.', 'No topo.'),
('bottom', 'fundo', 'general', 'beginner', '/ˈbɑːtəm/', 'Lowest part', 'At the bottom.', 'No fundo.'),
('front', 'frente', 'general', 'beginner', '/frʌnt/', 'Forward part', 'In front of.', 'Em frente de.'),
('center', 'centro', 'general', 'beginner', '/ˈsentər/', 'Middle point', 'City center.', 'Centro da cidade.'),
('left', 'esquerda', 'general', 'beginner', '/left/', 'Opposite of right', 'Turn left.', 'Vira à esquerda.'),
('right', 'direita', 'general', 'beginner', '/raɪt/', 'Opposite of left', 'Turn right.', 'Vira à direita.'),
('voice', 'voz', 'general', 'beginner', '/vɔɪs/', 'Sound from mouth', 'A beautiful voice.', 'Uma voz bonita.'),
('sound', 'som', 'general', 'beginner', '/saʊnd/', 'What we hear', 'A loud sound.', 'Um som alto.'),
('noise', 'barulho', 'general', 'beginner', '/nɔɪz/', 'Unwanted sound', 'Too much noise.', 'Muito barulho.'),
('silence', 'silêncio', 'general', 'beginner', '/ˈsaɪləns/', 'Absence of sound', 'Complete silence.', 'Silêncio completo.'),
('story', 'história', 'general', 'beginner', '/ˈstɔːri/', 'Narrative', 'Tell me a story.', 'Conta-me uma história.'),
('news', 'notícias', 'general', 'beginner', '/nuːz/', 'Information', 'Good news!', 'Boas notícias!'),
('information', 'informação', 'general', 'beginner', '/ˌɪnfərˈmeɪʃən/', 'Facts', 'More information.', 'Mais informação.'),
('language', 'língua', 'general', 'beginner', '/ˈlæŋɡwɪdʒ/', 'Communication system', 'A new language.', 'Uma nova língua.'),
('country', 'campo', 'general', 'beginner', '/ˈkʌntri/', 'Rural area', 'In the country.', 'No campo.')

ON CONFLICT (word) DO NOTHING;
