-- Base Vocabulary - Intermediate Level (Part 1: 250 words)
-- Business, Work, Professional Communication

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- Business & Work
('meeting', 'reunião', 'business', 'intermediate', '/ˈmiːtɪŋ/', 'Gathering for discussion', 'We have a meeting at 3.', 'Temos uma reunião às 3.'),
('deadline', 'prazo', 'business', 'intermediate', '/ˈdedlaɪn/', 'Final date', 'The deadline is Friday.', 'O prazo é sexta-feira.'),
('project', 'projeto', 'business', 'intermediate', '/ˈprɑːdʒekt/', 'Planned work', 'A new project.', 'Um novo projeto.'),
('budget', 'orçamento', 'business', 'intermediate', '/ˈbʌdʒɪt/', 'Financial plan', 'Stay within budget.', 'Mantém-te dentro do orçamento.'),
('schedule', 'horário', 'business', 'intermediate', '/ˈskedʒuːl/', 'Time plan', 'Check your schedule.', 'Verifica o teu horário.'),
('appointment', 'compromisso', 'business', 'intermediate', '/əˈpɔɪntmənt/', 'Arranged meeting', 'I have an appointment.', 'Tenho um compromisso.'),
('colleague', 'colega', 'business', 'intermediate', '/ˈkɑːliːɡ/', 'Work associate', 'My colleague helped me.', 'O meu colega ajudou-me.'),
('client', 'cliente', 'business', 'intermediate', '/ˈklaɪənt/', 'Customer', 'Meet with the client.', 'Reunir com o cliente.'),
('employee', 'empregado', 'business', 'intermediate', '/ɪmˈplɔɪiː/', 'Worker', 'A new employee.', 'Um novo empregado.'),
('employer', 'empregador', 'business', 'intermediate', '/ɪmˈplɔɪər/', 'Person who employs', 'A good employer.', 'Um bom empregador.'),
('department', 'departamento', 'business', 'intermediate', '/dɪˈpɑːrtmənt/', 'Company division', 'The sales department.', 'O departamento de vendas.'),
('contract', 'contrato', 'business', 'intermediate', '/ˈkɑːntrækt/', 'Legal agreement', 'Sign the contract.', 'Assina o contrato.'),
('salary', 'salário', 'business', 'intermediate', '/ˈsæləri/', 'Monthly pay', 'A competitive salary.', 'Um salário competitivo.'),
('bonus', 'bónus', 'business', 'intermediate', '/ˈboʊnəs/', 'Extra payment', 'Year-end bonus.', 'Bónus de fim de ano.'),
('promotion', 'promoção', 'business', 'intermediate', '/prəˈmoʊʃən/', 'Career advancement', 'She got a promotion.', 'Ela teve uma promoção.'),
('interview', 'entrevista', 'business', 'intermediate', '/ˈɪntərvjuː/', 'Job discussion', 'A job interview.', 'Uma entrevista de emprego.'),
('resume', 'currículo', 'business', 'intermediate', '/ˈrezjʊmeɪ/', 'Work history document', 'Update your resume.', 'Atualiza o currículo.'),
('experience', 'experiência', 'business', 'intermediate', '/ɪkˈspɪriəns/', 'Past work', 'Work experience.', 'Experiência de trabalho.'),
('skill', 'competência', 'business', 'intermediate', '/skɪl/', 'Ability', 'Communication skills.', 'Competências de comunicação.'),
('training', 'formação', 'business', 'intermediate', '/ˈtreɪnɪŋ/', 'Teaching skills', 'Staff training.', 'Formação de pessoal.'),
('task', 'tarefa', 'business', 'intermediate', '/tæsk/', 'Work assignment', 'Complete this task.', 'Completa esta tarefa.'),
('responsibility', 'responsabilidade', 'business', 'intermediate', '/rɪˌspɑːnsəˈbɪləti/', 'Duty', 'A big responsibility.', 'Uma grande responsabilidade.'),
('opportunity', 'oportunidade', 'business', 'intermediate', '/ˌɑːpərˈtuːnəti/', 'Chance', 'A great opportunity.', 'Uma grande oportunidade.'),
('challenge', 'desafio', 'business', 'intermediate', '/ˈtʃælɪndʒ/', 'Difficult task', 'Accept the challenge.', 'Aceita o desafio.'),
('solution', 'solução', 'business', 'intermediate', '/səˈluːʃən/', 'Answer to problem', 'Find a solution.', 'Encontra uma solução.'),
('decision', 'decisão', 'business', 'intermediate', '/dɪˈsɪʒən/', 'Choice', 'Make a decision.', 'Toma uma decisão.'),
('strategy', 'estratégia', 'business', 'intermediate', '/ˈstrætədʒi/', 'Plan of action', 'Marketing strategy.', 'Estratégia de marketing.'),
('target', 'objetivo', 'business', 'intermediate', '/ˈtɑːrɡɪt/', 'Goal to reach', 'Meet the target.', 'Atingir o objetivo.'),
('profit', 'lucro', 'business', 'intermediate', '/ˈprɑːfɪt/', 'Financial gain', 'Make a profit.', 'Ter lucro.'),
('loss', 'perda', 'business', 'intermediate', '/lɔːs/', 'Financial decline', 'Avoid losses.', 'Evita perdas.'),
('investment', 'investimento', 'business', 'intermediate', '/ɪnˈvestmənt/', 'Money put in', 'A good investment.', 'Um bom investimento.'),
('competition', 'concorrência', 'business', 'intermediate', '/ˌkɑːmpəˈtɪʃən/', 'Business rivals', 'Strong competition.', 'Forte concorrência.'),
('customer', 'cliente', 'business', 'intermediate', '/ˈkʌstəmər/', 'Buyer', 'Customer satisfaction.', 'Satisfação do cliente.'),
('supplier', 'fornecedor', 'business', 'intermediate', '/səˈplaɪər/', 'Provider', 'Reliable supplier.', 'Fornecedor fiável.'),
('negotiation', 'negociação', 'business', 'intermediate', '/nɪˌɡoʊʃiˈeɪʃən/', 'Discussion to agree', 'Salary negotiation.', 'Negociação salarial.'),
('agreement', 'acordo', 'business', 'intermediate', '/əˈɡriːmənt/', 'Mutual understanding', 'Reach an agreement.', 'Chegar a um acordo.'),
('proposal', 'proposta', 'business', 'intermediate', '/prəˈpoʊzəl/', 'Suggestion', 'A business proposal.', 'Uma proposta de negócio.'),
('presentation', 'apresentação', 'business', 'intermediate', '/ˌprezənˈteɪʃən/', 'Formal talk', 'Give a presentation.', 'Fazer uma apresentação.'),
('report', 'relatório', 'business', 'intermediate', '/rɪˈpɔːrt/', 'Written account', 'Annual report.', 'Relatório anual.'),
('analysis', 'análise', 'business', 'intermediate', '/əˈnæləsɪs/', 'Detailed examination', 'Data analysis.', 'Análise de dados.'),
('research', 'investigação', 'business', 'intermediate', '/ˈriːsɜːrtʃ/', 'Study', 'Market research.', 'Investigação de mercado.'),
('development', 'desenvolvimento', 'business', 'intermediate', '/dɪˈveləpmənt/', 'Growth or creation', 'Product development.', 'Desenvolvimento de produto.'),
('improvement', 'melhoria', 'business', 'intermediate', '/ɪmˈpruːvmənt/', 'Getting better', 'Continuous improvement.', 'Melhoria contínua.'),
('efficiency', 'eficiência', 'business', 'intermediate', '/ɪˈfɪʃənsi/', 'Working well', 'Improve efficiency.', 'Melhorar a eficiência.'),
('productivity', 'produtividade', 'business', 'intermediate', '/ˌproʊdʌkˈtɪvəti/', 'Output level', 'Increase productivity.', 'Aumentar a produtividade.'),

-- Communication Verbs
('discuss', 'discutir', 'verbs', 'intermediate', '/dɪˈskʌs/', 'To talk about', 'Let us discuss this.', 'Vamos discutir isto.'),
('explain', 'explicar', 'verbs', 'intermediate', '/ɪkˈspleɪn/', 'To make clear', 'Please explain.', 'Por favor explica.'),
('describe', 'descrever', 'verbs', 'intermediate', '/dɪˈskraɪb/', 'To tell about', 'Describe the situation.', 'Descreve a situação.'),
('suggest', 'sugerir', 'verbs', 'intermediate', '/səˈdʒest/', 'To propose', 'I suggest we wait.', 'Sugiro que esperemos.'),
('recommend', 'recomendar', 'verbs', 'intermediate', '/ˌrekəˈmend/', 'To advise', 'I recommend this book.', 'Recomendo este livro.'),
('confirm', 'confirmar', 'verbs', 'intermediate', '/kənˈfɜːrm/', 'To verify', 'Please confirm.', 'Por favor confirma.'),
('cancel', 'cancelar', 'verbs', 'intermediate', '/ˈkænsəl/', 'To call off', 'Cancel the meeting.', 'Cancela a reunião.'),
('postpone', 'adiar', 'verbs', 'intermediate', '/poʊstˈpoʊn/', 'To delay', 'Postpone the deadline.', 'Adia o prazo.'),
('organize', 'organizar', 'verbs', 'intermediate', '/ˈɔːrɡənaɪz/', 'To arrange', 'Organize the files.', 'Organiza os ficheiros.'),
('achieve', 'alcançar', 'verbs', 'intermediate', '/əˈtʃiːv/', 'To accomplish', 'Achieve your goals.', 'Alcança os teus objetivos.'),
('succeed', 'ter sucesso', 'verbs', 'intermediate', '/səkˈsiːd/', 'To be successful', 'You will succeed.', 'Vais ter sucesso.'),
('fail', 'falhar', 'verbs', 'intermediate', '/feɪl/', 'To not succeed', 'Do not be afraid to fail.', 'Não tenhas medo de falhar.'),
('improve', 'melhorar', 'verbs', 'intermediate', '/ɪmˈpruːv/', 'To make better', 'Improve your skills.', 'Melhora as tuas competências.'),
('develop', 'desenvolver', 'verbs', 'intermediate', '/dɪˈveləp/', 'To grow or create', 'Develop new products.', 'Desenvolver novos produtos.'),
('manage', 'gerir', 'verbs', 'intermediate', '/ˈmænɪdʒ/', 'To control', 'Manage the team.', 'Gerir a equipa.'),
('lead', 'liderar', 'verbs', 'intermediate', '/liːd/', 'To guide', 'Lead the project.', 'Liderar o projeto.'),
('support', 'apoiar', 'verbs', 'intermediate', '/səˈpɔːrt/', 'To help', 'Support your team.', 'Apoia a tua equipa.'),
('encourage', 'encorajar', 'verbs', 'intermediate', '/ɪnˈkɜːrɪdʒ/', 'To give confidence', 'Encourage others.', 'Encoraja os outros.'),
('motivate', 'motivar', 'verbs', 'intermediate', '/ˈmoʊtɪveɪt/', 'To inspire', 'Motivate your staff.', 'Motiva os teus funcionários.'),
('evaluate', 'avaliar', 'verbs', 'intermediate', '/ɪˈvæljueɪt/', 'To assess', 'Evaluate performance.', 'Avaliar o desempenho.'),
('measure', 'medir', 'verbs', 'intermediate', '/ˈmeʒər/', 'To determine size', 'Measure the results.', 'Mede os resultados.'),
('compare', 'comparar', 'verbs', 'intermediate', '/kəmˈper/', 'To examine differences', 'Compare prices.', 'Compara preços.'),
('reduce', 'reduzir', 'verbs', 'intermediate', '/rɪˈduːs/', 'To make smaller', 'Reduce costs.', 'Reduz os custos.'),
('increase', 'aumentar', 'verbs', 'intermediate', '/ɪnˈkriːs/', 'To make larger', 'Increase sales.', 'Aumenta as vendas.'),
('maintain', 'manter', 'verbs', 'intermediate', '/meɪnˈteɪn/', 'To keep up', 'Maintain quality.', 'Mantém a qualidade.'),
('establish', 'estabelecer', 'verbs', 'intermediate', '/ɪˈstæblɪʃ/', 'To set up', 'Establish a business.', 'Estabelecer um negócio.'),
('create', 'criar', 'verbs', 'intermediate', '/kriˈeɪt/', 'To make', 'Create a plan.', 'Cria um plano.'),
('design', 'desenhar', 'verbs', 'intermediate', '/dɪˈzaɪn/', 'To plan appearance', 'Design a website.', 'Desenha um website.'),
('implement', 'implementar', 'verbs', 'intermediate', '/ˈɪmpləment/', 'To put into action', 'Implement the strategy.', 'Implementa a estratégia.'),
('apply', 'aplicar', 'verbs', 'intermediate', '/əˈplaɪ/', 'To put to use', 'Apply for a job.', 'Candidatar-se a um emprego.'),
('require', 'requerer', 'verbs', 'intermediate', '/rɪˈkwaɪər/', 'To need', 'This requires patience.', 'Isto requer paciência.'),
('depend', 'depender', 'verbs', 'intermediate', '/dɪˈpend/', 'To rely on', 'It depends on you.', 'Depende de ti.'),
('include', 'incluir', 'verbs', 'intermediate', '/ɪnˈkluːd/', 'To contain', 'Include all details.', 'Inclui todos os detalhes.'),
('exclude', 'excluir', 'verbs', 'intermediate', '/ɪkˈskluːd/', 'To leave out', 'Exclude unnecessary items.', 'Exclui itens desnecessários.'),
('consider', 'considerar', 'verbs', 'intermediate', '/kənˈsɪdər/', 'To think about', 'Consider all options.', 'Considera todas as opções.'),
('assume', 'assumir', 'verbs', 'intermediate', '/əˈsuːm/', 'To suppose', 'Do not assume.', 'Não assumas.'),
('expect', 'esperar', 'verbs', 'intermediate', '/ɪkˈspekt/', 'To anticipate', 'I expect results.', 'Espero resultados.'),
('predict', 'prever', 'verbs', 'intermediate', '/prɪˈdɪkt/', 'To forecast', 'Predict the outcome.', 'Prever o resultado.'),
('estimate', 'estimar', 'verbs', 'intermediate', '/ˈestɪmeɪt/', 'To guess approximately', 'Estimate the cost.', 'Estima o custo.'),
('calculate', 'calcular', 'verbs', 'intermediate', '/ˈkælkjuleɪt/', 'To compute', 'Calculate the total.', 'Calcula o total.'),

-- Adjectives for Work
('professional', 'profissional', 'adjectives', 'intermediate', '/prəˈfeʃənəl/', 'Related to work', 'A professional attitude.', 'Uma atitude profissional.'),
('reliable', 'fiável', 'adjectives', 'intermediate', '/rɪˈlaɪəbəl/', 'Dependable', 'A reliable partner.', 'Um parceiro fiável.'),
('responsible', 'responsável', 'adjectives', 'intermediate', '/rɪˈspɑːnsəbəl/', 'Accountable', 'Be responsible.', 'Sê responsável.'),
('experienced', 'experiente', 'adjectives', 'intermediate', '/ɪkˈspɪriənst/', 'Having experience', 'An experienced manager.', 'Um gestor experiente.'),
('qualified', 'qualificado', 'adjectives', 'intermediate', '/ˈkwɑːlɪfaɪd/', 'Having qualifications', 'A qualified candidate.', 'Um candidato qualificado.'),
('efficient', 'eficiente', 'adjectives', 'intermediate', '/ɪˈfɪʃənt/', 'Working well', 'An efficient process.', 'Um processo eficiente.'),
('effective', 'eficaz', 'adjectives', 'intermediate', '/ɪˈfektɪv/', 'Producing results', 'An effective solution.', 'Uma solução eficaz.'),
('productive', 'produtivo', 'adjectives', 'intermediate', '/prəˈdʌktɪv/', 'Producing much', 'A productive day.', 'Um dia produtivo.'),
('successful', 'bem-sucedido', 'adjectives', 'intermediate', '/səkˈsesfəl/', 'Achieving goals', 'A successful company.', 'Uma empresa bem-sucedida.'),
('competitive', 'competitivo', 'adjectives', 'intermediate', '/kəmˈpetətɪv/', 'Wanting to win', 'A competitive market.', 'Um mercado competitivo.'),
('creative', 'criativo', 'adjectives', 'intermediate', '/kriˈeɪtɪv/', 'Having new ideas', 'A creative solution.', 'Uma solução criativa.'),
('innovative', 'inovador', 'adjectives', 'intermediate', '/ˈɪnəveɪtɪv/', 'Introducing new things', 'An innovative approach.', 'Uma abordagem inovadora.'),
('flexible', 'flexível', 'adjectives', 'intermediate', '/ˈfleksəbəl/', 'Adaptable', 'Flexible working hours.', 'Horário de trabalho flexível.'),
('dedicated', 'dedicado', 'adjectives', 'intermediate', '/ˈdedɪkeɪtɪd/', 'Committed', 'A dedicated team.', 'Uma equipa dedicada.'),
('motivated', 'motivado', 'adjectives', 'intermediate', '/ˈmoʊtɪveɪtɪd/', 'Eager to work', 'Highly motivated.', 'Altamente motivado.'),
('confident', 'confiante', 'adjectives', 'intermediate', '/ˈkɑːnfɪdənt/', 'Self-assured', 'Be confident.', 'Sê confiante.'),
('ambitious', 'ambicioso', 'adjectives', 'intermediate', '/æmˈbɪʃəs/', 'Having big goals', 'An ambitious plan.', 'Um plano ambicioso.'),
('organized', 'organizado', 'adjectives', 'intermediate', '/ˈɔːrɡənaɪzd/', 'Well arranged', 'Stay organized.', 'Mantém-te organizado.'),
('focused', 'focado', 'adjectives', 'intermediate', '/ˈfoʊkəst/', 'Concentrated', 'Stay focused.', 'Mantém-te focado.'),
('practical', 'prático', 'adjectives', 'intermediate', '/ˈpræktɪkəl/', 'Useful', 'A practical solution.', 'Uma solução prática.'),
('technical', 'técnico', 'adjectives', 'intermediate', '/ˈteknɪkəl/', 'Related to technology', 'Technical knowledge.', 'Conhecimento técnico.'),
('financial', 'financeiro', 'adjectives', 'intermediate', '/faɪˈnænʃəl/', 'Related to money', 'Financial planning.', 'Planeamento financeiro.'),
('economic', 'económico', 'adjectives', 'intermediate', '/ˌiːkəˈnɑːmɪk/', 'Related to economy', 'Economic growth.', 'Crescimento económico.'),
('commercial', 'comercial', 'adjectives', 'intermediate', '/kəˈmɜːrʃəl/', 'Related to commerce', 'Commercial success.', 'Sucesso comercial.'),
('international', 'internacional', 'adjectives', 'intermediate', '/ˌɪntərˈnæʃənəl/', 'Between countries', 'International trade.', 'Comércio internacional.'),
('global', 'global', 'adjectives', 'intermediate', '/ˈɡloʊbəl/', 'Worldwide', 'A global company.', 'Uma empresa global.'),
('local', 'local', 'adjectives', 'intermediate', '/ˈloʊkəl/', 'Of a particular place', 'Local business.', 'Negócio local.'),
('current', 'atual', 'adjectives', 'intermediate', '/ˈkɜːrənt/', 'Present', 'Current situation.', 'Situação atual.'),
('previous', 'anterior', 'adjectives', 'intermediate', '/ˈpriːviəs/', 'Before now', 'Previous experience.', 'Experiência anterior.'),
('recent', 'recente', 'adjectives', 'intermediate', '/ˈriːsənt/', 'Not long ago', 'Recent developments.', 'Desenvolvimentos recentes.'),
('available', 'disponível', 'adjectives', 'intermediate', '/əˈveɪləbəl/', 'Can be obtained', 'Available resources.', 'Recursos disponíveis.'),
('appropriate', 'apropriado', 'adjectives', 'intermediate', '/əˈproʊpriət/', 'Suitable', 'Appropriate behavior.', 'Comportamento apropriado.'),
('relevant', 'relevante', 'adjectives', 'intermediate', '/ˈreləvənt/', 'Related and important', 'Relevant information.', 'Informação relevante.'),
('essential', 'essencial', 'adjectives', 'intermediate', '/ɪˈsenʃəl/', 'Absolutely necessary', 'Essential skills.', 'Competências essenciais.'),
('necessary', 'necessário', 'adjectives', 'intermediate', '/ˈnesəseri/', 'Required', 'Necessary steps.', 'Passos necessários.'),
('urgent', 'urgente', 'adjectives', 'intermediate', '/ˈɜːrdʒənt/', 'Needing immediate action', 'An urgent matter.', 'Um assunto urgente.'),
('specific', 'específico', 'adjectives', 'intermediate', '/spəˈsɪfɪk/', 'Particular', 'Specific requirements.', 'Requisitos específicos.'),
('general', 'geral', 'adjectives', 'intermediate', '/ˈdʒenərəl/', 'Not specific', 'General information.', 'Informação geral.'),
('detailed', 'detalhado', 'adjectives', 'intermediate', '/ˈdiːteɪld/', 'With many details', 'A detailed report.', 'Um relatório detalhado.'),
('complex', 'complexo', 'adjectives', 'intermediate', '/ˈkɑːmpleks/', 'Complicated', 'A complex problem.', 'Um problema complexo.'),
('simple', 'simples', 'adjectives', 'intermediate', '/ˈsɪmpəl/', 'Not complex', 'A simple solution.', 'Uma solução simples.'),
('accurate', 'preciso', 'adjectives', 'intermediate', '/ˈækjərət/', 'Correct and exact', 'Accurate data.', 'Dados precisos.'),
('approximate', 'aproximado', 'adjectives', 'intermediate', '/əˈprɑːksɪmət/', 'Nearly correct', 'An approximate value.', 'Um valor aproximado.'),
('significant', 'significativo', 'adjectives', 'intermediate', '/sɪɡˈnɪfɪkənt/', 'Important', 'Significant progress.', 'Progresso significativo.'),
('considerable', 'considerável', 'adjectives', 'intermediate', '/kənˈsɪdərəbəl/', 'Large in amount', 'Considerable effort.', 'Esforço considerável.'),
('sufficient', 'suficiente', 'adjectives', 'intermediate', '/səˈfɪʃənt/', 'Enough', 'Sufficient funds.', 'Fundos suficientes.'),
('potential', 'potencial', 'adjectives', 'intermediate', '/pəˈtenʃəl/', 'Possible', 'Potential customers.', 'Clientes potenciais.'),
('alternative', 'alternativo', 'adjectives', 'intermediate', '/ɔːlˈtɜːrnətɪv/', 'Other option', 'An alternative plan.', 'Um plano alternativo.')

ON CONFLICT (word) DO NOTHING;
