-- Base Vocabulary - Intermediate Level (Part 2: 250 words)
-- Phrasal Verbs, Idioms, Advanced Communication

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- Common Phrasal Verbs
('look after', 'cuidar de', 'phrasal verbs', 'intermediate', '/lʊk ˈæftər/', 'To take care of', 'Look after your health.', 'Cuida da tua saúde.'),
('look for', 'procurar', 'phrasal verbs', 'intermediate', '/lʊk fɔːr/', 'To search for', 'I am looking for my keys.', 'Estou à procura das chaves.'),
('look forward to', 'aguardar com expectativa', 'phrasal verbs', 'intermediate', '/lʊk ˈfɔːrwərd tuː/', 'To anticipate with pleasure', 'I look forward to meeting you.', 'Aguardo com expectativa conhecer-te.'),
('look up', 'procurar (informação)', 'phrasal verbs', 'intermediate', '/lʊk ʌp/', 'To search for information', 'Look up the word.', 'Procura a palavra.'),
('give up', 'desistir', 'phrasal verbs', 'intermediate', '/ɡɪv ʌp/', 'To stop trying', 'Never give up.', 'Nunca desistas.'),
('give back', 'devolver', 'phrasal verbs', 'intermediate', '/ɡɪv bæk/', 'To return', 'Give it back to me.', 'Devolve-mo.'),
('take off', 'descolar/tirar', 'phrasal verbs', 'intermediate', '/teɪk ɔːf/', 'To remove or depart', 'The plane takes off at 6.', 'O avião descola às 6.'),
('take on', 'assumir', 'phrasal verbs', 'intermediate', '/teɪk ɑːn/', 'To accept responsibility', 'Take on new challenges.', 'Assume novos desafios.'),
('take over', 'assumir o controlo', 'phrasal verbs', 'intermediate', '/teɪk ˈoʊvər/', 'To gain control', 'Take over the project.', 'Assume o projeto.'),
('turn on', 'ligar', 'phrasal verbs', 'intermediate', '/tɜːrn ɑːn/', 'To switch on', 'Turn on the light.', 'Liga a luz.'),
('turn off', 'desligar', 'phrasal verbs', 'intermediate', '/tɜːrn ɔːf/', 'To switch off', 'Turn off your phone.', 'Desliga o telemóvel.'),
('turn down', 'recusar/baixar', 'phrasal verbs', 'intermediate', '/tɜːrn daʊn/', 'To refuse or reduce', 'Turn down the volume.', 'Baixa o volume.'),
('turn up', 'aparecer/aumentar', 'phrasal verbs', 'intermediate', '/tɜːrn ʌp/', 'To arrive or increase', 'He turned up late.', 'Ele apareceu atrasado.'),
('put off', 'adiar', 'phrasal verbs', 'intermediate', '/pʊt ɔːf/', 'To postpone', 'Do not put it off.', 'Não adies isso.'),
('put on', 'vestir', 'phrasal verbs', 'intermediate', '/pʊt ɑːn/', 'To wear', 'Put on your coat.', 'Veste o casaco.'),
('put up with', 'tolerar', 'phrasal verbs', 'intermediate', '/pʊt ʌp wɪð/', 'To tolerate', 'I cannot put up with this.', 'Não consigo tolerar isto.'),
('get along', 'dar-se bem', 'phrasal verbs', 'intermediate', '/ɡet əˈlɔːŋ/', 'To have good relations', 'They get along well.', 'Eles dão-se bem.'),
('get over', 'recuperar de', 'phrasal verbs', 'intermediate', '/ɡet ˈoʊvər/', 'To recover from', 'Get over the flu.', 'Recuperar da gripe.'),
('get through', 'conseguir contactar', 'phrasal verbs', 'intermediate', '/ɡet θruː/', 'To reach by phone', 'I cannot get through.', 'Não consigo contactar.'),
('get up', 'levantar-se', 'phrasal verbs', 'intermediate', '/ɡet ʌp/', 'To rise from bed', 'I get up at 7.', 'Levanto-me às 7.'),
('break down', 'avariar', 'phrasal verbs', 'intermediate', '/breɪk daʊn/', 'To stop working', 'The car broke down.', 'O carro avariou.'),
('break up', 'terminar (relação)', 'phrasal verbs', 'intermediate', '/breɪk ʌp/', 'To end a relationship', 'They broke up.', 'Eles terminaram.'),
('bring up', 'criar/mencionar', 'phrasal verbs', 'intermediate', '/brɪŋ ʌp/', 'To raise or mention', 'She brought up a good point.', 'Ela mencionou um bom ponto.'),
('carry on', 'continuar', 'phrasal verbs', 'intermediate', '/ˈkæri ɑːn/', 'To continue', 'Carry on with your work.', 'Continua com o teu trabalho.'),
('carry out', 'realizar', 'phrasal verbs', 'intermediate', '/ˈkæri aʊt/', 'To conduct', 'Carry out the plan.', 'Realiza o plano.'),
('come across', 'encontrar por acaso', 'phrasal verbs', 'intermediate', '/kʌm əˈkrɔːs/', 'To find by chance', 'I came across an old photo.', 'Encontrei uma foto antiga.'),
('come up with', 'inventar', 'phrasal verbs', 'intermediate', '/kʌm ʌp wɪð/', 'To think of', 'Come up with a solution.', 'Inventa uma solução.'),
('end up', 'acabar por', 'phrasal verbs', 'intermediate', '/end ʌp/', 'To finally be', 'We ended up staying.', 'Acabámos por ficar.'),
('figure out', 'descobrir', 'phrasal verbs', 'intermediate', '/ˈfɪɡər aʊt/', 'To understand', 'Figure out the problem.', 'Descobre o problema.'),
('fill in', 'preencher', 'phrasal verbs', 'intermediate', '/fɪl ɪn/', 'To complete a form', 'Fill in this form.', 'Preenche este formulário.'),
('find out', 'descobrir', 'phrasal verbs', 'intermediate', '/faɪnd aʊt/', 'To discover', 'Find out the truth.', 'Descobre a verdade.'),
('go on', 'continuar', 'phrasal verbs', 'intermediate', '/ɡoʊ ɑːn/', 'To continue', 'Go on, tell me more.', 'Continua, conta-me mais.'),
('go through', 'passar por', 'phrasal verbs', 'intermediate', '/ɡoʊ θruː/', 'To experience', 'Go through difficult times.', 'Passar por tempos difíceis.'),
('hold on', 'esperar', 'phrasal verbs', 'intermediate', '/hoʊld ɑːn/', 'To wait', 'Hold on a moment.', 'Espera um momento.'),
('keep up', 'acompanhar', 'phrasal verbs', 'intermediate', '/kiːp ʌp/', 'To maintain pace', 'Keep up the good work.', 'Continua o bom trabalho.'),
('let down', 'desiludir', 'phrasal verbs', 'intermediate', '/let daʊn/', 'To disappoint', 'Do not let me down.', 'Não me desiludas.'),
('make up', 'inventar/reconciliar', 'phrasal verbs', 'intermediate', '/meɪk ʌp/', 'To invent or reconcile', 'Make up your mind.', 'Decide-te.'),
('pass away', 'falecer', 'phrasal verbs', 'intermediate', '/pæs əˈweɪ/', 'To die', 'He passed away peacefully.', 'Ele faleceu em paz.'),
('pick up', 'apanhar/aprender', 'phrasal verbs', 'intermediate', '/pɪk ʌp/', 'To collect or learn', 'Pick up the phone.', 'Atende o telefone.'),
('point out', 'apontar', 'phrasal verbs', 'intermediate', '/pɔɪnt aʊt/', 'To indicate', 'I must point out that...', 'Devo apontar que...'),
('run out of', 'ficar sem', 'phrasal verbs', 'intermediate', '/rʌn aʊt əv/', 'To have no more', 'We ran out of milk.', 'Ficámos sem leite.'),
('set up', 'montar/estabelecer', 'phrasal verbs', 'intermediate', '/set ʌp/', 'To establish', 'Set up a meeting.', 'Marca uma reunião.'),
('show up', 'aparecer', 'phrasal verbs', 'intermediate', '/ʃoʊ ʌp/', 'To arrive', 'He did not show up.', 'Ele não apareceu.'),
('sort out', 'resolver', 'phrasal verbs', 'intermediate', '/sɔːrt aʊt/', 'To organize or fix', 'Sort out the problem.', 'Resolve o problema.'),
('work out', 'resultar/exercitar', 'phrasal verbs', 'intermediate', '/wɜːrk aʊt/', 'To exercise or succeed', 'Everything worked out.', 'Tudo resultou bem.'),

-- Common Idioms
('break the ice', 'quebrar o gelo', 'idioms', 'intermediate', '/breɪk ðə aɪs/', 'To start a conversation', 'Tell a joke to break the ice.', 'Conta uma piada para quebrar o gelo.'),
('hit the nail on the head', 'acertar em cheio', 'idioms', 'intermediate', '/hɪt ðə neɪl/', 'To be exactly right', 'You hit the nail on the head.', 'Acertaste em cheio.'),
('piece of cake', 'canja', 'idioms', 'intermediate', '/piːs əv keɪk/', 'Very easy', 'The test was a piece of cake.', 'O teste foi canja.'),
('once in a blue moon', 'de vez em quando', 'idioms', 'intermediate', '/wʌns ɪn ə bluː muːn/', 'Rarely', 'I see him once in a blue moon.', 'Vejo-o de vez em quando.'),
('under the weather', 'adoentado', 'idioms', 'intermediate', '/ˈʌndər ðə ˈweðər/', 'Feeling ill', 'I am under the weather today.', 'Estou adoentado hoje.'),
('cost an arm and a leg', 'custar os olhos da cara', 'idioms', 'intermediate', '/kɔːst ən ɑːrm/', 'Very expensive', 'This car cost an arm and a leg.', 'Este carro custou os olhos da cara.'),
('bite the bullet', 'enfrentar a situação', 'idioms', 'intermediate', '/baɪt ðə ˈbʊlɪt/', 'To face something difficult', 'It is time to bite the bullet.', 'É altura de enfrentar a situação.'),
('get out of hand', 'sair do controlo', 'idioms', 'intermediate', '/ɡet aʊt əv hænd/', 'To become uncontrollable', 'The situation got out of hand.', 'A situação saiu do controlo.'),
('in the long run', 'a longo prazo', 'idioms', 'intermediate', '/ɪn ðə lɔːŋ rʌn/', 'Eventually', 'It will pay off in the long run.', 'Vai compensar a longo prazo.'),
('on the same page', 'de acordo', 'idioms', 'intermediate', '/ɑːn ðə seɪm peɪdʒ/', 'In agreement', 'We are on the same page.', 'Estamos de acordo.'),
('the ball is in your court', 'a decisão é tua', 'idioms', 'intermediate', '/ðə bɔːl ɪz ɪn jɔːr kɔːrt/', 'It is your decision', 'The ball is in your court now.', 'Agora a decisão é tua.'),
('time flies', 'o tempo voa', 'idioms', 'intermediate', '/taɪm flaɪz/', 'Time passes quickly', 'Time flies when you are having fun.', 'O tempo voa quando te divertes.'),
('better late than never', 'antes tarde do que nunca', 'idioms', 'intermediate', '/ˈbetər leɪt ðən ˈnevər/', 'It is better to do something late than not at all', 'Better late than never!', 'Antes tarde do que nunca!'),
('actions speak louder than words', 'ações valem mais que palavras', 'idioms', 'intermediate', '/ˈækʃənz spiːk/', 'What you do is more important', 'Actions speak louder than words.', 'Ações valem mais que palavras.'),
('every cloud has a silver lining', 'há sempre um lado positivo', 'idioms', 'intermediate', '/ˈevri klaʊd/', 'There is something good in every bad situation', 'Every cloud has a silver lining.', 'Há sempre um lado positivo.'),

-- Academic & Formal Vocabulary
('research', 'investigação', 'academic', 'intermediate', '/rɪˈsɜːrtʃ/', 'Systematic study', 'Scientific research.', 'Investigação científica.'),
('theory', 'teoria', 'academic', 'intermediate', '/ˈθɪəri/', 'Set of ideas', 'A new theory.', 'Uma nova teoria.'),
('hypothesis', 'hipótese', 'academic', 'intermediate', '/haɪˈpɑːθəsɪs/', 'Proposed explanation', 'Test the hypothesis.', 'Testar a hipótese.'),
('experiment', 'experiência', 'academic', 'intermediate', '/ɪkˈsperɪmənt/', 'Scientific test', 'Conduct an experiment.', 'Realizar uma experiência.'),
('evidence', 'evidência', 'academic', 'intermediate', '/ˈevɪdəns/', 'Proof', 'Strong evidence.', 'Evidência forte.'),
('conclusion', 'conclusão', 'academic', 'intermediate', '/kənˈkluːʒən/', 'Final result', 'Draw a conclusion.', 'Tirar uma conclusão.'),
('argument', 'argumento', 'academic', 'intermediate', '/ˈɑːrɡjumənt/', 'Reasoning', 'A strong argument.', 'Um argumento forte.'),
('opinion', 'opinião', 'academic', 'intermediate', '/əˈpɪnjən/', 'Personal view', 'In my opinion.', 'Na minha opinião.'),
('perspective', 'perspetiva', 'academic', 'intermediate', '/pərˈspektɪv/', 'Point of view', 'Different perspectives.', 'Perspetivas diferentes.'),
('concept', 'conceito', 'academic', 'intermediate', '/ˈkɑːnsept/', 'Idea', 'A new concept.', 'Um novo conceito.'),
('approach', 'abordagem', 'academic', 'intermediate', '/əˈproʊtʃ/', 'Method', 'A different approach.', 'Uma abordagem diferente.'),
('method', 'método', 'academic', 'intermediate', '/ˈmeθəd/', 'Way of doing', 'Scientific method.', 'Método científico.'),
('process', 'processo', 'academic', 'intermediate', '/ˈprɑːses/', 'Series of actions', 'Learning process.', 'Processo de aprendizagem.'),
('result', 'resultado', 'academic', 'intermediate', '/rɪˈzʌlt/', 'Outcome', 'Positive results.', 'Resultados positivos.'),
('effect', 'efeito', 'academic', 'intermediate', '/ɪˈfekt/', 'Impact', 'Cause and effect.', 'Causa e efeito.'),
('cause', 'causa', 'academic', 'intermediate', '/kɔːz/', 'Reason', 'The main cause.', 'A causa principal.'),
('factor', 'fator', 'academic', 'intermediate', '/ˈfæktər/', 'Element', 'Key factors.', 'Fatores-chave.'),
('issue', 'questão', 'academic', 'intermediate', '/ˈɪʃuː/', 'Topic or problem', 'An important issue.', 'Uma questão importante.'),
('aspect', 'aspeto', 'academic', 'intermediate', '/ˈæspekt/', 'Part or feature', 'Different aspects.', 'Aspetos diferentes.'),
('situation', 'situação', 'academic', 'intermediate', '/ˌsɪtʃuˈeɪʃən/', 'Circumstances', 'A difficult situation.', 'Uma situação difícil.'),
('context', 'contexto', 'academic', 'intermediate', '/ˈkɑːntekst/', 'Surrounding conditions', 'In this context.', 'Neste contexto.'),
('source', 'fonte', 'academic', 'intermediate', '/sɔːrs/', 'Origin', 'Reliable sources.', 'Fontes fiáveis.'),
('reference', 'referência', 'academic', 'intermediate', '/ˈrefərəns/', 'Citation', 'Add references.', 'Adiciona referências.'),
('summary', 'resumo', 'academic', 'intermediate', '/ˈsʌməri/', 'Brief account', 'A summary of events.', 'Um resumo dos acontecimentos.'),
('definition', 'definição', 'academic', 'intermediate', '/ˌdefɪˈnɪʃən/', 'Meaning explanation', 'The definition of.', 'A definição de.'),
('explanation', 'explicação', 'academic', 'intermediate', '/ˌekspləˈneɪʃən/', 'Making clear', 'A clear explanation.', 'Uma explicação clara.'),
('description', 'descrição', 'academic', 'intermediate', '/dɪˈskrɪpʃən/', 'Account of something', 'A detailed description.', 'Uma descrição detalhada.'),
('comparison', 'comparação', 'academic', 'intermediate', '/kəmˈpærɪsən/', 'Examining similarities', 'Make a comparison.', 'Faz uma comparação.'),
('contrast', 'contraste', 'academic', 'intermediate', '/ˈkɑːntræst/', 'Difference', 'In contrast to.', 'Em contraste com.'),
('example', 'exemplo', 'academic', 'intermediate', '/ɪɡˈzæmpəl/', 'Instance', 'For example.', 'Por exemplo.'),

-- Health & Wellbeing
('health', 'saúde', 'health', 'intermediate', '/helθ/', 'State of body', 'Good health.', 'Boa saúde.'),
('illness', 'doença', 'health', 'intermediate', '/ˈɪlnəs/', 'Sickness', 'A serious illness.', 'Uma doença grave.'),
('disease', 'doença', 'health', 'intermediate', '/dɪˈziːz/', 'Medical condition', 'Heart disease.', 'Doença cardíaca.'),
('symptom', 'sintoma', 'health', 'intermediate', '/ˈsɪmptəm/', 'Sign of illness', 'Common symptoms.', 'Sintomas comuns.'),
('treatment', 'tratamento', 'health', 'intermediate', '/ˈtriːtmənt/', 'Medical care', 'Effective treatment.', 'Tratamento eficaz.'),
('medicine', 'medicamento', 'health', 'intermediate', '/ˈmedɪsən/', 'Drug', 'Take your medicine.', 'Toma o medicamento.'),
('prescription', 'receita', 'health', 'intermediate', '/prɪˈskrɪpʃən/', 'Doctor order', 'A prescription for.', 'Uma receita para.'),
('appointment', 'consulta', 'health', 'intermediate', '/əˈpɔɪntmənt/', 'Medical visit', 'Doctor appointment.', 'Consulta médica.'),
('surgery', 'cirurgia', 'health', 'intermediate', '/ˈsɜːrdʒəri/', 'Medical operation', 'Heart surgery.', 'Cirurgia cardíaca.'),
('recovery', 'recuperação', 'health', 'intermediate', '/rɪˈkʌvəri/', 'Getting better', 'A quick recovery.', 'Uma recuperação rápida.'),
('diet', 'dieta', 'health', 'intermediate', '/ˈdaɪət/', 'Food plan', 'A balanced diet.', 'Uma dieta equilibrada.'),
('nutrition', 'nutrição', 'health', 'intermediate', '/nuːˈtrɪʃən/', 'Food value', 'Good nutrition.', 'Boa nutrição.'),
('fitness', 'boa forma', 'health', 'intermediate', '/ˈfɪtnəs/', 'Physical condition', 'Fitness goals.', 'Objetivos de boa forma.'),
('workout', 'treino', 'health', 'intermediate', '/ˈwɜːrkaʊt/', 'Exercise session', 'Daily workout.', 'Treino diário.'),
('wellness', 'bem-estar', 'health', 'intermediate', '/ˈwelnəs/', 'State of being well', 'Focus on wellness.', 'Foco no bem-estar.'),
('anxiety', 'ansiedade', 'health', 'intermediate', '/æŋˈzaɪəti/', 'Worry', 'Anxiety disorder.', 'Transtorno de ansiedade.'),
('depression', 'depressão', 'health', 'intermediate', '/dɪˈpreʃən/', 'Mental condition', 'Overcome depression.', 'Superar a depressão.'),
('therapy', 'terapia', 'health', 'intermediate', '/ˈθerəpi/', 'Treatment', 'Physical therapy.', 'Fisioterapia.'),
('allergy', 'alergia', 'health', 'intermediate', '/ˈælərdʒi/', 'Immune reaction', 'Food allergy.', 'Alergia alimentar.'),
('infection', 'infeção', 'health', 'intermediate', '/ɪnˈfekʃən/', 'Disease caused by germs', 'Viral infection.', 'Infeção viral.')

ON CONFLICT (word) DO UPDATE SET
  translation = EXCLUDED.translation,
  category = EXCLUDED.category,
  difficulty = EXCLUDED.difficulty,
  pronunciation = EXCLUDED.pronunciation,
  definition = EXCLUDED.definition,
  example_sentence = EXCLUDED.example_sentence,
  example_translation = EXCLUDED.example_translation,
  updated_at = now();
