-- Base Vocabulary - Intermediate Level (Part 3: 250 words)
-- Technology, Media, Society, Relationships

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- Technology & Digital
('software', 'software', 'technology', 'intermediate', '/ˈsɔːftwer/', 'Computer programs', 'Install the software.', 'Instala o software.'),
('hardware', 'hardware', 'technology', 'intermediate', '/ˈhɑːrdwer/', 'Physical equipment', 'Hardware malfunction.', 'Avaria de hardware.'),
('database', 'base de dados', 'technology', 'intermediate', '/ˈdeɪtəbeɪs/', 'Organized data collection', 'Update the database.', 'Atualiza a base de dados.'),
('network', 'rede', 'technology', 'intermediate', '/ˈnetwɜːrk/', 'Connected systems', 'Network connection.', 'Ligação de rede.'),
('server', 'servidor', 'technology', 'intermediate', '/ˈsɜːrvər/', 'Central computer', 'Server is down.', 'O servidor está em baixo.'),
('device', 'dispositivo', 'technology', 'intermediate', '/dɪˈvaɪs/', 'Electronic tool', 'Mobile device.', 'Dispositivo móvel.'),
('application', 'aplicação', 'technology', 'intermediate', '/ˌæplɪˈkeɪʃən/', 'Software program', 'Download the application.', 'Descarrega a aplicação.'),
('update', 'atualização', 'technology', 'intermediate', '/ˈʌpdeɪt/', 'New version', 'System update.', 'Atualização do sistema.'),
('download', 'descarregar', 'technology', 'intermediate', '/ˈdaʊnloʊd/', 'Transfer from internet', 'Download the file.', 'Descarrega o ficheiro.'),
('upload', 'carregar', 'technology', 'intermediate', '/ˈʌploʊd/', 'Transfer to internet', 'Upload your photo.', 'Carrega a tua foto.'),
('storage', 'armazenamento', 'technology', 'intermediate', '/ˈstɔːrɪdʒ/', 'Space for data', 'Cloud storage.', 'Armazenamento na nuvem.'),
('backup', 'cópia de segurança', 'technology', 'intermediate', '/ˈbækʌp/', 'Copy for safety', 'Make a backup.', 'Faz uma cópia de segurança.'),
('security', 'segurança', 'technology', 'intermediate', '/sɪˈkjʊrəti/', 'Protection', 'Online security.', 'Segurança online.'),
('privacy', 'privacidade', 'technology', 'intermediate', '/ˈpraɪvəsi/', 'Personal space', 'Respect privacy.', 'Respeita a privacidade.'),
('account', 'conta', 'technology', 'intermediate', '/əˈkaʊnt/', 'User profile', 'Create an account.', 'Cria uma conta.'),
('username', 'nome de utilizador', 'technology', 'intermediate', '/ˈjuːzərneɪm/', 'Login name', 'Choose a username.', 'Escolhe um nome de utilizador.'),
('login', 'iniciar sessão', 'technology', 'intermediate', '/ˈlɔːɡɪn/', 'Access system', 'Login to your account.', 'Inicia sessão na tua conta.'),
('logout', 'terminar sessão', 'technology', 'intermediate', '/ˈlɔːɡaʊt/', 'Exit system', 'Remember to logout.', 'Lembra-te de terminar sessão.'),
('notification', 'notificação', 'technology', 'intermediate', '/ˌnoʊtɪfɪˈkeɪʃən/', 'Alert message', 'Push notification.', 'Notificação push.'),
('setting', 'definição', 'technology', 'intermediate', '/ˈsetɪŋ/', 'Configuration', 'Change settings.', 'Altera as definições.'),
('feature', 'funcionalidade', 'technology', 'intermediate', '/ˈfiːtʃər/', 'Capability', 'New feature.', 'Nova funcionalidade.'),
('interface', 'interface', 'technology', 'intermediate', '/ˈɪntərfeɪs/', 'User interaction area', 'User interface.', 'Interface de utilizador.'),
('browser', 'navegador', 'technology', 'intermediate', '/ˈbraʊzər/', 'Web viewing program', 'Open your browser.', 'Abre o navegador.'),
('search engine', 'motor de busca', 'technology', 'intermediate', '/sɜːrtʃ ˈendʒɪn/', 'Web search tool', 'Use a search engine.', 'Usa um motor de busca.'),
('social media', 'redes sociais', 'technology', 'intermediate', '/ˈsoʊʃəl ˈmiːdiə/', 'Online platforms', 'Social media presence.', 'Presença nas redes sociais.'),
('content', 'conteúdo', 'technology', 'intermediate', '/ˈkɑːntent/', 'Material published', 'Create content.', 'Cria conteúdo.'),
('platform', 'plataforma', 'technology', 'intermediate', '/ˈplætfɔːrm/', 'Base system', 'Online platform.', 'Plataforma online.'),
('digital', 'digital', 'technology', 'intermediate', '/ˈdɪdʒɪtəl/', 'Electronic', 'Digital transformation.', 'Transformação digital.'),
('online', 'online', 'technology', 'intermediate', '/ˈɑːnlaɪn/', 'On internet', 'Online shopping.', 'Compras online.'),
('offline', 'offline', 'technology', 'intermediate', '/ˈɔːflaɪn/', 'Not on internet', 'Work offline.', 'Trabalhar offline.'),
('virtual', 'virtual', 'technology', 'intermediate', '/ˈvɜːrtʃuəl/', 'Computer-based', 'Virtual meeting.', 'Reunião virtual.'),
('wireless', 'sem fios', 'technology', 'intermediate', '/ˈwaɪərləs/', 'Without wires', 'Wireless connection.', 'Ligação sem fios.'),
('algorithm', 'algoritmo', 'technology', 'intermediate', '/ˈælɡərɪðəm/', 'Set of rules', 'Search algorithm.', 'Algoritmo de pesquisa.'),
('data', 'dados', 'technology', 'intermediate', '/ˈdeɪtə/', 'Information', 'Collect data.', 'Recolher dados.'),

-- Media & Entertainment
('media', 'média', 'media', 'intermediate', '/ˈmiːdiə/', 'Communication channels', 'Mass media.', 'Meios de comunicação.'),
('broadcast', 'transmissão', 'media', 'intermediate', '/ˈbrɔːdkæst/', 'Radio or TV transmission', 'Live broadcast.', 'Transmissão ao vivo.'),
('channel', 'canal', 'media', 'intermediate', '/ˈtʃænəl/', 'TV station', 'Change the channel.', 'Muda de canal.'),
('program', 'programa', 'media', 'intermediate', '/ˈproʊɡræm/', 'TV show', 'A new program.', 'Um novo programa.'),
('series', 'série', 'media', 'intermediate', '/ˈsɪriːz/', 'TV episodes', 'Watch a series.', 'Ver uma série.'),
('episode', 'episódio', 'media', 'intermediate', '/ˈepɪsoʊd/', 'Part of series', 'The latest episode.', 'O episódio mais recente.'),
('documentary', 'documentário', 'media', 'intermediate', '/ˌdɑːkjuˈmentəri/', 'Factual film', 'Watch a documentary.', 'Ver um documentário.'),
('journalist', 'jornalista', 'media', 'intermediate', '/ˈdʒɜːrnəlɪst/', 'News reporter', 'A famous journalist.', 'Um jornalista famoso.'),
('article', 'artigo', 'media', 'intermediate', '/ˈɑːrtɪkəl/', 'Written piece', 'Read the article.', 'Lê o artigo.'),
('headline', 'título', 'media', 'intermediate', '/ˈhedlaɪn/', 'News title', 'Front page headline.', 'Título de primeira página.'),
('advertisement', 'anúncio', 'media', 'intermediate', '/ˌædvərˈtaɪzmənt/', 'Commercial', 'A TV advertisement.', 'Um anúncio de televisão.'),
('commercial', 'comercial', 'media', 'intermediate', '/kəˈmɜːrʃəl/', 'Advertising', 'A funny commercial.', 'Um anúncio engraçado.'),
('audience', 'audiência', 'media', 'intermediate', '/ˈɔːdiəns/', 'Viewers or listeners', 'Large audience.', 'Grande audiência.'),
('viewer', 'telespetador', 'media', 'intermediate', '/ˈvjuːər/', 'Person watching', 'Millions of viewers.', 'Milhões de telespetadores.'),
('listener', 'ouvinte', 'media', 'intermediate', '/ˈlɪsənər/', 'Person listening', 'Radio listeners.', 'Ouvintes de rádio.'),
('podcast', 'podcast', 'media', 'intermediate', '/ˈpɑːdkæst/', 'Audio program', 'Listen to podcasts.', 'Ouvir podcasts.'),
('streaming', 'streaming', 'media', 'intermediate', '/ˈstriːmɪŋ/', 'Online watching', 'Streaming service.', 'Serviço de streaming.'),
('entertainment', 'entretenimento', 'media', 'intermediate', '/ˌentərˈteɪnmənt/', 'Amusement', 'Entertainment industry.', 'Indústria do entretenimento.'),
('celebrity', 'celebridade', 'media', 'intermediate', '/səˈlebrəti/', 'Famous person', 'A Hollywood celebrity.', 'Uma celebridade de Hollywood.'),
('fame', 'fama', 'media', 'intermediate', '/feɪm/', 'Being famous', 'Rise to fame.', 'Ascender à fama.'),

-- Society & Culture
('society', 'sociedade', 'society', 'intermediate', '/səˈsaɪəti/', 'Community', 'Modern society.', 'Sociedade moderna.'),
('community', 'comunidade', 'society', 'intermediate', '/kəˈmjuːnəti/', 'Group of people', 'Local community.', 'Comunidade local.'),
('population', 'população', 'society', 'intermediate', '/ˌpɑːpjuˈleɪʃən/', 'Number of people', 'World population.', 'População mundial.'),
('citizen', 'cidadão', 'society', 'intermediate', '/ˈsɪtɪzən/', 'Member of country', 'A good citizen.', 'Um bom cidadão.'),
('government', 'governo', 'society', 'intermediate', '/ˈɡʌvərnmənt/', 'Ruling body', 'The government decided.', 'O governo decidiu.'),
('politics', 'política', 'society', 'intermediate', '/ˈpɑːlətɪks/', 'Government affairs', 'Talk about politics.', 'Falar de política.'),
('election', 'eleição', 'society', 'intermediate', '/ɪˈlekʃən/', 'Voting event', 'General election.', 'Eleições gerais.'),
('vote', 'votar', 'society', 'intermediate', '/voʊt/', 'Cast ballot', 'Vote for change.', 'Votar pela mudança.'),
('law', 'lei', 'society', 'intermediate', '/lɔː/', 'Legal rule', 'Break the law.', 'Violar a lei.'),
('right', 'direito', 'society', 'intermediate', '/raɪt/', 'Entitlement', 'Human rights.', 'Direitos humanos.'),
('freedom', 'liberdade', 'society', 'intermediate', '/ˈfriːdəm/', 'Liberty', 'Freedom of speech.', 'Liberdade de expressão.'),
('justice', 'justiça', 'society', 'intermediate', '/ˈdʒʌstɪs/', 'Fairness', 'Social justice.', 'Justiça social.'),
('equality', 'igualdade', 'society', 'intermediate', '/ɪˈkwɑːləti/', 'Same treatment', 'Gender equality.', 'Igualdade de género.'),
('democracy', 'democracia', 'society', 'intermediate', '/dɪˈmɑːkrəsi/', 'Government by people', 'Support democracy.', 'Apoiar a democracia.'),
('culture', 'cultura', 'society', 'intermediate', '/ˈkʌltʃər/', 'Way of life', 'Rich culture.', 'Cultura rica.'),
('tradition', 'tradição', 'society', 'intermediate', '/trəˈdɪʃən/', 'Custom', 'Family tradition.', 'Tradição familiar.'),
('custom', 'costume', 'society', 'intermediate', '/ˈkʌstəm/', 'Practice', 'Local customs.', 'Costumes locais.'),
('religion', 'religião', 'society', 'intermediate', '/rɪˈlɪdʒən/', 'Faith system', 'World religions.', 'Religiões do mundo.'),
('belief', 'crença', 'society', 'intermediate', '/bɪˈliːf/', 'Conviction', 'Personal beliefs.', 'Crenças pessoais.'),
('value', 'valor', 'society', 'intermediate', '/ˈvæljuː/', 'Principle', 'Core values.', 'Valores fundamentais.'),
('attitude', 'atitude', 'society', 'intermediate', '/ˈætɪtuːd/', 'Way of thinking', 'Positive attitude.', 'Atitude positiva.'),
('behavior', 'comportamento', 'society', 'intermediate', '/bɪˈheɪvjər/', 'Conduct', 'Good behavior.', 'Bom comportamento.'),
('identity', 'identidade', 'society', 'intermediate', '/aɪˈdentəti/', 'Who one is', 'Cultural identity.', 'Identidade cultural.'),
('generation', 'geração', 'society', 'intermediate', '/ˌdʒenəˈreɪʃən/', 'Age group', 'The younger generation.', 'A geração mais jovem.'),
('minority', 'minoria', 'society', 'intermediate', '/maɪˈnɔːrəti/', 'Smaller group', 'Ethnic minorities.', 'Minorias étnicas.'),
('majority', 'maioria', 'society', 'intermediate', '/məˈdʒɔːrəti/', 'Larger group', 'The vast majority.', 'A grande maioria.'),

-- Relationships & Social
('relationship', 'relacionamento', 'relationships', 'intermediate', '/rɪˈleɪʃənʃɪp/', 'Connection', 'A good relationship.', 'Um bom relacionamento.'),
('friendship', 'amizade', 'relationships', 'intermediate', '/ˈfrendʃɪp/', 'Being friends', 'True friendship.', 'Amizade verdadeira.'),
('partner', 'parceiro', 'relationships', 'intermediate', '/ˈpɑːrtnər/', 'Companion', 'Business partner.', 'Parceiro de negócios.'),
('couple', 'casal', 'relationships', 'intermediate', '/ˈkʌpəl/', 'Two people together', 'A happy couple.', 'Um casal feliz.'),
('neighbor', 'vizinho', 'relationships', 'intermediate', '/ˈneɪbər/', 'Person living near', 'Friendly neighbors.', 'Vizinhos simpáticos.'),
('stranger', 'desconhecido', 'relationships', 'intermediate', '/ˈstreɪndʒər/', 'Unknown person', 'Talk to strangers.', 'Falar com desconhecidos.'),
('acquaintance', 'conhecido', 'relationships', 'intermediate', '/əˈkweɪntəns/', 'Person you know slightly', 'A business acquaintance.', 'Um conhecido de negócios.'),
('companion', 'companheiro', 'relationships', 'intermediate', '/kəmˈpænjən/', 'Fellow traveler', 'A loyal companion.', 'Um companheiro leal.'),
('trust', 'confiança', 'relationships', 'intermediate', '/trʌst/', 'Belief in reliability', 'Build trust.', 'Construir confiança.'),
('respect', 'respeito', 'relationships', 'intermediate', '/rɪˈspekt/', 'Admiration', 'Mutual respect.', 'Respeito mútuo.'),
('loyalty', 'lealdade', 'relationships', 'intermediate', '/ˈlɔɪəlti/', 'Faithfulness', 'Show loyalty.', 'Mostrar lealdade.'),
('honesty', 'honestidade', 'relationships', 'intermediate', '/ˈɑːnəsti/', 'Truthfulness', 'Value honesty.', 'Valorizar a honestidade.'),
('commitment', 'compromisso', 'relationships', 'intermediate', '/kəˈmɪtmənt/', 'Dedication', 'A serious commitment.', 'Um compromisso sério.'),
('communication', 'comunicação', 'relationships', 'intermediate', '/kəˌmjuːnɪˈkeɪʃən/', 'Exchange of information', 'Good communication.', 'Boa comunicação.'),
('conversation', 'conversa', 'relationships', 'intermediate', '/ˌkɑːnvərˈseɪʃən/', 'Talk', 'Interesting conversation.', 'Conversa interessante.'),
('argument', 'discussão', 'relationships', 'intermediate', '/ˈɑːrɡjumənt/', 'Disagreement', 'Have an argument.', 'Ter uma discussão.'),
('conflict', 'conflito', 'relationships', 'intermediate', '/ˈkɑːnflɪkt/', 'Clash', 'Resolve conflict.', 'Resolver conflitos.'),
('compromise', 'compromisso', 'relationships', 'intermediate', '/ˈkɑːmprəmaɪz/', 'Agreement by concession', 'Reach a compromise.', 'Chegar a um compromisso.'),
('forgive', 'perdoar', 'relationships', 'intermediate', '/fərˈɡɪv/', 'Pardon', 'Learn to forgive.', 'Aprender a perdoar.'),
('apologize', 'pedir desculpa', 'relationships', 'intermediate', '/əˈpɑːlədʒaɪz/', 'Say sorry', 'I apologize.', 'Peço desculpa.'),

-- More Verbs
('adapt', 'adaptar', 'verbs', 'intermediate', '/əˈdæpt/', 'To adjust', 'Adapt to change.', 'Adaptar à mudança.'),
('adjust', 'ajustar', 'verbs', 'intermediate', '/əˈdʒʌst/', 'To modify', 'Adjust the settings.', 'Ajusta as definições.'),
('adopt', 'adotar', 'verbs', 'intermediate', '/əˈdɑːpt/', 'To take on', 'Adopt a new approach.', 'Adotar uma nova abordagem.'),
('affect', 'afetar', 'verbs', 'intermediate', '/əˈfekt/', 'To influence', 'How does it affect you?', 'Como é que te afeta?'),
('afford', 'poder pagar', 'verbs', 'intermediate', '/əˈfɔːrd/', 'To have money for', 'I cannot afford it.', 'Não posso pagar.'),
('appreciate', 'apreciar', 'verbs', 'intermediate', '/əˈpriːʃieɪt/', 'To value', 'I appreciate your help.', 'Aprecio a tua ajuda.'),
('arrange', 'arranjar', 'verbs', 'intermediate', '/əˈreɪndʒ/', 'To organize', 'Arrange a meeting.', 'Arranja uma reunião.'),
('associate', 'associar', 'verbs', 'intermediate', '/əˈsoʊʃieɪt/', 'To connect', 'Associate ideas.', 'Associar ideias.'),
('attach', 'anexar', 'verbs', 'intermediate', '/əˈtætʃ/', 'To fasten', 'Attach the file.', 'Anexa o ficheiro.'),
('attract', 'atrair', 'verbs', 'intermediate', '/əˈtrækt/', 'To draw toward', 'Attract attention.', 'Atrair atenção.'),
('avoid', 'evitar', 'verbs', 'intermediate', '/əˈvɔɪd/', 'To keep away from', 'Avoid mistakes.', 'Evita erros.'),
('belong', 'pertencer', 'verbs', 'intermediate', '/bɪˈlɔːŋ/', 'To be part of', 'Where do you belong?', 'A onde pertences?'),
('blame', 'culpar', 'verbs', 'intermediate', '/bleɪm/', 'To hold responsible', 'Do not blame others.', 'Não culpes os outros.'),
('borrow', 'pedir emprestado', 'verbs', 'intermediate', '/ˈbɔːroʊ/', 'To take temporarily', 'Can I borrow this?', 'Posso pedir emprestado?'),
('celebrate', 'celebrar', 'verbs', 'intermediate', '/ˈseləbreɪt/', 'To honor', 'Celebrate success.', 'Celebrar o sucesso.'),
('claim', 'reivindicar', 'verbs', 'intermediate', '/kleɪm/', 'To assert', 'Claim your rights.', 'Reivindica os teus direitos.'),
('combine', 'combinar', 'verbs', 'intermediate', '/kəmˈbaɪn/', 'To join together', 'Combine ideas.', 'Combina ideias.'),
('communicate', 'comunicar', 'verbs', 'intermediate', '/kəˈmjuːnɪkeɪt/', 'To share information', 'Communicate clearly.', 'Comunica claramente.'),
('compete', 'competir', 'verbs', 'intermediate', '/kəmˈpiːt/', 'To rival', 'Compete for the prize.', 'Competir pelo prémio.'),
('complain', 'reclamar', 'verbs', 'intermediate', '/kəmˈpleɪn/', 'To express dissatisfaction', 'Do not complain.', 'Não reclames.'),
('concentrate', 'concentrar', 'verbs', 'intermediate', '/ˈkɑːnsəntreɪt/', 'To focus', 'Concentrate on work.', 'Concentra-te no trabalho.'),
('conclude', 'concluir', 'verbs', 'intermediate', '/kənˈkluːd/', 'To finish', 'Conclude the presentation.', 'Conclui a apresentação.'),
('connect', 'ligar', 'verbs', 'intermediate', '/kəˈnekt/', 'To join', 'Connect the cables.', 'Liga os cabos.'),
('consist', 'consistir', 'verbs', 'intermediate', '/kənˈsɪst/', 'To be made of', 'It consists of three parts.', 'Consiste em três partes.'),
('contain', 'conter', 'verbs', 'intermediate', '/kənˈteɪn/', 'To hold', 'This box contains books.', 'Esta caixa contém livros.'),
('contribute', 'contribuir', 'verbs', 'intermediate', '/kənˈtrɪbjuːt/', 'To give', 'Contribute to society.', 'Contribuir para a sociedade.'),
('convince', 'convencer', 'verbs', 'intermediate', '/kənˈvɪns/', 'To persuade', 'Convince them.', 'Convence-os.'),
('deal', 'lidar', 'verbs', 'intermediate', '/diːl/', 'To handle', 'Deal with problems.', 'Lidar com problemas.'),
('decrease', 'diminuir', 'verbs', 'intermediate', '/dɪˈkriːs/', 'To reduce', 'Decrease expenses.', 'Diminuir despesas.'),
('deliver', 'entregar', 'verbs', 'intermediate', '/dɪˈlɪvər/', 'To bring', 'Deliver the package.', 'Entregar o pacote.'),
('demand', 'exigir', 'verbs', 'intermediate', '/dɪˈmænd/', 'To require', 'Demand respect.', 'Exigir respeito.'),
('demonstrate', 'demonstrar', 'verbs', 'intermediate', '/ˈdemənstreɪt/', 'To show', 'Demonstrate your skills.', 'Demonstra as tuas competências.'),
('deny', 'negar', 'verbs', 'intermediate', '/dɪˈnaɪ/', 'To refuse', 'Deny the accusation.', 'Negar a acusação.'),
('deserve', 'merecer', 'verbs', 'intermediate', '/dɪˈzɜːrv/', 'To be worthy of', 'You deserve it.', 'Tu mereces.'),
('destroy', 'destruir', 'verbs', 'intermediate', '/dɪˈstrɔɪ/', 'To ruin', 'Do not destroy nature.', 'Não destruas a natureza.'),
('determine', 'determinar', 'verbs', 'intermediate', '/dɪˈtɜːrmɪn/', 'To decide', 'Determine the cause.', 'Determinar a causa.'),
('disappear', 'desaparecer', 'verbs', 'intermediate', '/ˌdɪsəˈpɪr/', 'To vanish', 'The problem disappeared.', 'O problema desapareceu.'),
('discover', 'descobrir', 'verbs', 'intermediate', '/dɪˈskʌvər/', 'To find', 'Discover new places.', 'Descobrir novos lugares.'),
('divide', 'dividir', 'verbs', 'intermediate', '/dɪˈvaɪd/', 'To separate', 'Divide the work.', 'Divide o trabalho.'),
('doubt', 'duvidar', 'verbs', 'intermediate', '/daʊt/', 'To question', 'I doubt it.', 'Duvido.'),
('earn', 'ganhar', 'verbs', 'intermediate', '/ɜːrn/', 'To receive for work', 'Earn money.', 'Ganhar dinheiro.'),
('enable', 'permitir', 'verbs', 'intermediate', '/ɪˈneɪbəl/', 'To make possible', 'Enable the feature.', 'Ativa a funcionalidade.'),
('ensure', 'assegurar', 'verbs', 'intermediate', '/ɪnˈʃʊr/', 'To make certain', 'Ensure quality.', 'Assegurar qualidade.'),
('exist', 'existir', 'verbs', 'intermediate', '/ɪɡˈzɪst/', 'To be', 'Does it exist?', 'Existe?'),
('expand', 'expandir', 'verbs', 'intermediate', '/ɪkˈspænd/', 'To grow', 'Expand the business.', 'Expandir o negócio.'),
('explore', 'explorar', 'verbs', 'intermediate', '/ɪkˈsplɔːr/', 'To investigate', 'Explore options.', 'Explorar opções.'),
('express', 'expressar', 'verbs', 'intermediate', '/ɪkˈspres/', 'To show', 'Express your feelings.', 'Expressa os teus sentimentos.'),
('extend', 'estender', 'verbs', 'intermediate', '/ɪkˈstend/', 'To lengthen', 'Extend the deadline.', 'Estender o prazo.'),
('focus', 'focar', 'verbs', 'intermediate', '/ˈfoʊkəs/', 'To concentrate', 'Focus on priorities.', 'Foca nas prioridades.'),
('generate', 'gerar', 'verbs', 'intermediate', '/ˈdʒenəreɪt/', 'To produce', 'Generate income.', 'Gerar rendimento.')

ON CONFLICT (word) DO NOTHING;
