-- Base Vocabulary - Intermediate Level (Part 4: 250 words)
-- More verbs, travel, food, emotions

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- More Verbs (continued)
('identify', 'identificar', 'verbs', 'intermediate', '/aɪˈdentɪfaɪ/', 'To recognize', 'Identify the problem.', 'Identifica o problema.'),
('ignore', 'ignorar', 'verbs', 'intermediate', '/ɪɡˈnɔːr/', 'To disregard', 'Do not ignore warnings.', 'Não ignores avisos.'),
('imagine', 'imaginar', 'verbs', 'intermediate', '/ɪˈmædʒɪn/', 'To picture mentally', 'Imagine the possibilities.', 'Imagina as possibilidades.'),
('imply', 'implicar', 'verbs', 'intermediate', '/ɪmˈplaɪ/', 'To suggest', 'What does it imply?', 'O que é que implica?'),
('impress', 'impressionar', 'verbs', 'intermediate', '/ɪmˈpres/', 'To make an impact', 'Impress the audience.', 'Impressiona a audiência.'),
('indicate', 'indicar', 'verbs', 'intermediate', '/ˈɪndɪkeɪt/', 'To show', 'The results indicate.', 'Os resultados indicam.'),
('influence', 'influenciar', 'verbs', 'intermediate', '/ˈɪnfluəns/', 'To affect', 'Influence decisions.', 'Influenciar decisões.'),
('inform', 'informar', 'verbs', 'intermediate', '/ɪnˈfɔːrm/', 'To tell', 'Please inform us.', 'Por favor informa-nos.'),
('insist', 'insistir', 'verbs', 'intermediate', '/ɪnˈsɪst/', 'To demand firmly', 'I insist on quality.', 'Insisto na qualidade.'),
('inspire', 'inspirar', 'verbs', 'intermediate', '/ɪnˈspaɪər/', 'To motivate', 'Inspire others.', 'Inspira os outros.'),
('install', 'instalar', 'verbs', 'intermediate', '/ɪnˈstɔːl/', 'To set up', 'Install the software.', 'Instala o software.'),
('intend', 'tencionar', 'verbs', 'intermediate', '/ɪnˈtend/', 'To plan', 'I intend to go.', 'Tenciono ir.'),
('interpret', 'interpretar', 'verbs', 'intermediate', '/ɪnˈtɜːrprət/', 'To explain meaning', 'Interpret the data.', 'Interpreta os dados.'),
('introduce', 'apresentar', 'verbs', 'intermediate', '/ˌɪntrəˈduːs/', 'To make known', 'Let me introduce myself.', 'Deixa-me apresentar-me.'),
('invest', 'investir', 'verbs', 'intermediate', '/ɪnˈvest/', 'To put money in', 'Invest wisely.', 'Investe com sabedoria.'),
('investigate', 'investigar', 'verbs', 'intermediate', '/ɪnˈvestɪɡeɪt/', 'To examine', 'Investigate the case.', 'Investiga o caso.'),
('involve', 'envolver', 'verbs', 'intermediate', '/ɪnˈvɑːlv/', 'To include', 'Involve everyone.', 'Envolve toda a gente.'),
('judge', 'julgar', 'verbs', 'intermediate', '/dʒʌdʒ/', 'To form opinion', 'Do not judge others.', 'Não julgues os outros.'),
('justify', 'justificar', 'verbs', 'intermediate', '/ˈdʒʌstɪfaɪ/', 'To give reason', 'Justify your decision.', 'Justifica a tua decisão.'),
('lack', 'faltar', 'verbs', 'intermediate', '/læk/', 'To be without', 'Lack experience.', 'Faltar experiência.'),
('launch', 'lançar', 'verbs', 'intermediate', '/lɔːntʃ/', 'To start', 'Launch a product.', 'Lançar um produto.'),
('limit', 'limitar', 'verbs', 'intermediate', '/ˈlɪmɪt/', 'To restrict', 'Limit your spending.', 'Limita os teus gastos.'),
('link', 'ligar', 'verbs', 'intermediate', '/lɪŋk/', 'To connect', 'Link the pages.', 'Liga as páginas.'),
('locate', 'localizar', 'verbs', 'intermediate', '/ˈloʊkeɪt/', 'To find', 'Locate the file.', 'Localiza o ficheiro.'),
('mention', 'mencionar', 'verbs', 'intermediate', '/ˈmenʃən/', 'To refer to', 'I should mention.', 'Devo mencionar.'),
('negotiate', 'negociar', 'verbs', 'intermediate', '/nɪˈɡoʊʃieɪt/', 'To discuss terms', 'Negotiate a deal.', 'Negociar um acordo.'),
('notice', 'notar', 'verbs', 'intermediate', '/ˈnoʊtɪs/', 'To observe', 'Did you notice?', 'Notaste?'),
('obtain', 'obter', 'verbs', 'intermediate', '/əbˈteɪn/', 'To get', 'Obtain permission.', 'Obter permissão.'),
('occur', 'ocorrer', 'verbs', 'intermediate', '/əˈkɜːr/', 'To happen', 'Problems occur.', 'Problemas ocorrem.'),
('offer', 'oferecer', 'verbs', 'intermediate', '/ˈɔːfər/', 'To present', 'Offer help.', 'Oferece ajuda.'),
('operate', 'operar', 'verbs', 'intermediate', '/ˈɑːpəreɪt/', 'To function', 'Operate the machine.', 'Opera a máquina.'),
('overcome', 'superar', 'verbs', 'intermediate', '/ˌoʊvərˈkʌm/', 'To defeat', 'Overcome obstacles.', 'Supera obstáculos.'),
('perform', 'desempenhar', 'verbs', 'intermediate', '/pərˈfɔːrm/', 'To carry out', 'Perform well.', 'Desempenha bem.'),
('permit', 'permitir', 'verbs', 'intermediate', '/pərˈmɪt/', 'To allow', 'Permit access.', 'Permitir acesso.'),
('persuade', 'persuadir', 'verbs', 'intermediate', '/pərˈsweɪd/', 'To convince', 'Persuade them to come.', 'Persuade-os a vir.'),
('possess', 'possuir', 'verbs', 'intermediate', '/pəˈzes/', 'To own', 'Possess skills.', 'Possuir competências.'),
('prefer', 'preferir', 'verbs', 'intermediate', '/prɪˈfɜːr/', 'To like better', 'I prefer tea.', 'Prefiro chá.'),
('preserve', 'preservar', 'verbs', 'intermediate', '/prɪˈzɜːrv/', 'To protect', 'Preserve nature.', 'Preservar a natureza.'),
('prevent', 'prevenir', 'verbs', 'intermediate', '/prɪˈvent/', 'To stop', 'Prevent accidents.', 'Prevenir acidentes.'),
('produce', 'produzir', 'verbs', 'intermediate', '/prəˈduːs/', 'To make', 'Produce goods.', 'Produzir bens.'),
('promote', 'promover', 'verbs', 'intermediate', '/prəˈmoʊt/', 'To advance', 'Promote the product.', 'Promover o produto.'),
('propose', 'propor', 'verbs', 'intermediate', '/prəˈpoʊz/', 'To suggest', 'Propose a solution.', 'Propor uma solução.'),
('protect', 'proteger', 'verbs', 'intermediate', '/prəˈtekt/', 'To defend', 'Protect your data.', 'Protege os teus dados.'),
('provide', 'fornecer', 'verbs', 'intermediate', '/prəˈvaɪd/', 'To supply', 'Provide information.', 'Fornecer informação.'),
('publish', 'publicar', 'verbs', 'intermediate', '/ˈpʌblɪʃ/', 'To release', 'Publish the article.', 'Publicar o artigo.'),
('pursue', 'perseguir', 'verbs', 'intermediate', '/pərˈsuː/', 'To chase', 'Pursue your dreams.', 'Persegue os teus sonhos.'),
('react', 'reagir', 'verbs', 'intermediate', '/riˈækt/', 'To respond', 'How did you react?', 'Como reagiste?'),
('realize', 'perceber', 'verbs', 'intermediate', '/ˈriːəlaɪz/', 'To understand', 'I realize now.', 'Agora percebo.'),
('receive', 'receber', 'verbs', 'intermediate', '/rɪˈsiːv/', 'To get', 'Receive a gift.', 'Receber um presente.'),
('recognize', 'reconhecer', 'verbs', 'intermediate', '/ˈrekəɡnaɪz/', 'To identify', 'I recognize you.', 'Reconheço-te.'),
('recommend', 'recomendar', 'verbs', 'intermediate', '/ˌrekəˈmend/', 'To suggest', 'I recommend this.', 'Recomendo isto.'),

-- Travel & Tourism
('destination', 'destino', 'travel', 'intermediate', '/ˌdestɪˈneɪʃən/', 'Place to go', 'Popular destination.', 'Destino popular.'),
('departure', 'partida', 'travel', 'intermediate', '/dɪˈpɑːrtʃər/', 'Leaving', 'Departure time.', 'Hora de partida.'),
('arrival', 'chegada', 'travel', 'intermediate', '/əˈraɪvəl/', 'Coming', 'Arrival gate.', 'Portão de chegada.'),
('luggage', 'bagagem', 'travel', 'intermediate', '/ˈlʌɡɪdʒ/', 'Bags', 'Check your luggage.', 'Verifica a bagagem.'),
('suitcase', 'mala', 'travel', 'intermediate', '/ˈsuːtkeɪs/', 'Travel bag', 'Pack your suitcase.', 'Faz a mala.'),
('passport', 'passaporte', 'travel', 'intermediate', '/ˈpæspɔːrt/', 'Travel document', 'Valid passport.', 'Passaporte válido.'),
('visa', 'visto', 'travel', 'intermediate', '/ˈviːzə/', 'Entry permit', 'Apply for a visa.', 'Pedir um visto.'),
('reservation', 'reserva', 'travel', 'intermediate', '/ˌrezərˈveɪʃən/', 'Booking', 'Make a reservation.', 'Fazer uma reserva.'),
('accommodation', 'alojamento', 'travel', 'intermediate', '/əˌkɑːməˈdeɪʃən/', 'Place to stay', 'Find accommodation.', 'Encontrar alojamento.'),
('itinerary', 'itinerário', 'travel', 'intermediate', '/aɪˈtɪnəreri/', 'Travel plan', 'Check the itinerary.', 'Verifica o itinerário.'),
('tour', 'excursão', 'travel', 'intermediate', '/tʊr/', 'Guided visit', 'City tour.', 'Excursão pela cidade.'),
('tourist', 'turista', 'travel', 'intermediate', '/ˈtʊrɪst/', 'Visitor', 'Many tourists.', 'Muitos turistas.'),
('sightseeing', 'turismo', 'travel', 'intermediate', '/ˈsaɪtsiːɪŋ/', 'Visiting attractions', 'Go sightseeing.', 'Fazer turismo.'),
('attraction', 'atração', 'travel', 'intermediate', '/əˈtrækʃən/', 'Place of interest', 'Tourist attraction.', 'Atração turística.'),
('landmark', 'marco', 'travel', 'intermediate', '/ˈlændmɑːrk/', 'Famous place', 'Historical landmark.', 'Marco histórico.'),
('souvenir', 'lembrança', 'travel', 'intermediate', '/ˌsuːvəˈnɪr/', 'Memory item', 'Buy a souvenir.', 'Comprar uma lembrança.'),
('currency', 'moeda', 'travel', 'intermediate', '/ˈkɜːrənsi/', 'Money type', 'Local currency.', 'Moeda local.'),
('exchange', 'câmbio', 'travel', 'intermediate', '/ɪksˈtʃeɪndʒ/', 'Money change', 'Exchange rate.', 'Taxa de câmbio.'),
('delay', 'atraso', 'travel', 'intermediate', '/dɪˈleɪ/', 'Being late', 'Flight delay.', 'Atraso do voo.'),
('cancel', 'cancelar', 'travel', 'intermediate', '/ˈkænsəl/', 'To call off', 'Cancel the trip.', 'Cancelar a viagem.'),
('boarding', 'embarque', 'travel', 'intermediate', '/ˈbɔːrdɪŋ/', 'Getting on', 'Boarding pass.', 'Cartão de embarque.'),
('terminal', 'terminal', 'travel', 'intermediate', '/ˈtɜːrmɪnəl/', 'Station building', 'Airport terminal.', 'Terminal do aeroporto.'),
('customs', 'alfândega', 'travel', 'intermediate', '/ˈkʌstəmz/', 'Border control', 'Go through customs.', 'Passar pela alfândega.'),
('immigration', 'imigração', 'travel', 'intermediate', '/ˌɪmɪˈɡreɪʃən/', 'Border entry', 'Immigration control.', 'Controlo de imigração.'),
('abroad', 'no estrangeiro', 'travel', 'intermediate', '/əˈbrɔːd/', 'In another country', 'Travel abroad.', 'Viajar para o estrangeiro.'),

-- Advanced Food & Cuisine
('cuisine', 'cozinha', 'food', 'intermediate', '/kwɪˈziːn/', 'Style of cooking', 'French cuisine.', 'Cozinha francesa.'),
('ingredient', 'ingrediente', 'food', 'intermediate', '/ɪnˈɡriːdiənt/', 'Food component', 'Fresh ingredients.', 'Ingredientes frescos.'),
('recipe', 'receita', 'food', 'intermediate', '/ˈresəpi/', 'Cooking instructions', 'Follow the recipe.', 'Segue a receita.'),
('flavor', 'sabor', 'food', 'intermediate', '/ˈfleɪvər/', 'Taste', 'Rich flavor.', 'Sabor rico.'),
('spicy', 'picante', 'food', 'intermediate', '/ˈspaɪsi/', 'Hot tasting', 'Spicy food.', 'Comida picante.'),
('bitter', 'amargo', 'food', 'intermediate', '/ˈbɪtər/', 'Sharp taste', 'Bitter coffee.', 'Café amargo.'),
('sour', 'azedo', 'food', 'intermediate', '/ˈsaʊər/', 'Acidic taste', 'Sour lemon.', 'Limão azedo.'),
('delicious', 'delicioso', 'food', 'intermediate', '/dɪˈlɪʃəs/', 'Very tasty', 'Delicious meal.', 'Refeição deliciosa.'),
('appetizer', 'entrada', 'food', 'intermediate', '/ˈæpətaɪzər/', 'First course', 'Order an appetizer.', 'Pede uma entrada.'),
('main course', 'prato principal', 'food', 'intermediate', '/meɪn kɔːrs/', 'Primary dish', 'The main course.', 'O prato principal.'),
('dessert', 'sobremesa', 'food', 'intermediate', '/dɪˈzɜːrt/', 'Sweet course', 'Have dessert.', 'Comer sobremesa.'),
('beverage', 'bebida', 'food', 'intermediate', '/ˈbevərɪdʒ/', 'Drink', 'Hot beverages.', 'Bebidas quentes.'),
('portion', 'porção', 'food', 'intermediate', '/ˈpɔːrʃən/', 'Serving size', 'Large portion.', 'Porção grande.'),
('leftovers', 'sobras', 'food', 'intermediate', '/ˈleftˌoʊvərz/', 'Remaining food', 'Eat the leftovers.', 'Comer as sobras.'),
('organic', 'biológico', 'food', 'intermediate', '/ɔːrˈɡænɪk/', 'Natural', 'Organic vegetables.', 'Vegetais biológicos.'),
('vegetarian', 'vegetariano', 'food', 'intermediate', '/ˌvedʒəˈteriən/', 'No meat', 'Vegetarian menu.', 'Menu vegetariano.'),
('vegan', 'vegan', 'food', 'intermediate', '/ˈviːɡən/', 'No animal products', 'Vegan options.', 'Opções vegan.'),
('allergy', 'alergia', 'food', 'intermediate', '/ˈælərdʒi/', 'Food sensitivity', 'Food allergy.', 'Alergia alimentar.'),
('grill', 'grelhar', 'food', 'intermediate', '/ɡrɪl/', 'To cook on grill', 'Grill the meat.', 'Grelha a carne.'),
('roast', 'assar', 'food', 'intermediate', '/roʊst/', 'To cook in oven', 'Roast chicken.', 'Frango assado.'),
('steam', 'cozer a vapor', 'food', 'intermediate', '/stiːm/', 'To cook with steam', 'Steam vegetables.', 'Cozer vegetais a vapor.'),
('fry', 'fritar', 'food', 'intermediate', '/fraɪ/', 'To cook in oil', 'Fry the fish.', 'Frita o peixe.'),
('bake', 'cozer no forno', 'food', 'intermediate', '/beɪk/', 'To cook in oven', 'Bake a cake.', 'Cozer um bolo.'),
('stir', 'mexer', 'food', 'intermediate', '/stɜːr/', 'To mix', 'Stir the soup.', 'Mexe a sopa.'),
('slice', 'fatiar', 'food', 'intermediate', '/slaɪs/', 'To cut thin', 'Slice the bread.', 'Fatia o pão.'),

-- Emotions & Psychology
('emotion', 'emoção', 'emotions', 'intermediate', '/ɪˈmoʊʃən/', 'Feeling', 'Strong emotions.', 'Emoções fortes.'),
('mood', 'humor', 'emotions', 'intermediate', '/muːd/', 'State of mind', 'Good mood.', 'Bom humor.'),
('confidence', 'confiança', 'emotions', 'intermediate', '/ˈkɑːnfɪdəns/', 'Self-assurance', 'Build confidence.', 'Construir confiança.'),
('nervous', 'nervoso', 'emotions', 'intermediate', '/ˈnɜːrvəs/', 'Anxious', 'I feel nervous.', 'Sinto-me nervoso.'),
('anxious', 'ansioso', 'emotions', 'intermediate', '/ˈæŋkʃəs/', 'Worried', 'Anxious about the exam.', 'Ansioso com o exame.'),
('frustrated', 'frustrado', 'emotions', 'intermediate', '/ˈfrʌstreɪtɪd/', 'Disappointed', 'Feeling frustrated.', 'Sentir-se frustrado.'),
('disappointed', 'desiludido', 'emotions', 'intermediate', '/ˌdɪsəˈpɔɪntɪd/', 'Let down', 'Very disappointed.', 'Muito desiludido.'),
('embarrassed', 'envergonhado', 'emotions', 'intermediate', '/ɪmˈbærəst/', 'Ashamed', 'I felt embarrassed.', 'Senti-me envergonhado.'),
('confused', 'confuso', 'emotions', 'intermediate', '/kənˈfjuːzd/', 'Not understanding', 'I am confused.', 'Estou confuso.'),
('relieved', 'aliviado', 'emotions', 'intermediate', '/rɪˈliːvd/', 'Less worried', 'I feel relieved.', 'Sinto-me aliviado.'),
('grateful', 'grato', 'emotions', 'intermediate', '/ˈɡreɪtfəl/', 'Thankful', 'I am grateful.', 'Estou grato.'),
('proud', 'orgulhoso', 'emotions', 'intermediate', '/praʊd/', 'Self-satisfied', 'Very proud.', 'Muito orgulhoso.'),
('jealous', 'ciumento', 'emotions', 'intermediate', '/ˈdʒeləs/', 'Envious', 'Feeling jealous.', 'Sentir ciúmes.'),
('lonely', 'solitário', 'emotions', 'intermediate', '/ˈloʊnli/', 'Feeling alone', 'Feeling lonely.', 'Sentir-se solitário.'),
('bored', 'aborrecido', 'emotions', 'intermediate', '/bɔːrd/', 'Without interest', 'I am bored.', 'Estou aborrecido.'),
('excited', 'entusiasmado', 'emotions', 'intermediate', '/ɪkˈsaɪtɪd/', 'Very enthusiastic', 'So excited!', 'Tão entusiasmado!'),
('curious', 'curioso', 'emotions', 'intermediate', '/ˈkjʊriəs/', 'Wanting to know', 'I am curious.', 'Estou curioso.'),
('satisfied', 'satisfeito', 'emotions', 'intermediate', '/ˈsætɪsfaɪd/', 'Content', 'Feeling satisfied.', 'Sentir-se satisfeito.'),
('overwhelmed', 'sobrecarregado', 'emotions', 'intermediate', '/ˌoʊvərˈwelmd/', 'Too much to handle', 'Feeling overwhelmed.', 'Sentir-se sobrecarregado.'),
('inspired', 'inspirado', 'emotions', 'intermediate', '/ɪnˈspaɪərd/', 'Motivated', 'I feel inspired.', 'Sinto-me inspirado.'),
('determined', 'determinado', 'emotions', 'intermediate', '/dɪˈtɜːrmɪnd/', 'Resolved', 'Very determined.', 'Muito determinado.'),
('optimistic', 'otimista', 'emotions', 'intermediate', '/ˌɑːptɪˈmɪstɪk/', 'Hopeful', 'Stay optimistic.', 'Mantém-te otimista.'),
('pessimistic', 'pessimista', 'emotions', 'intermediate', '/ˌpesɪˈmɪstɪk/', 'Expecting bad', 'Do not be pessimistic.', 'Não sejas pessimista.'),
('sympathetic', 'simpático', 'emotions', 'intermediate', '/ˌsɪmpəˈθetɪk/', 'Understanding', 'A sympathetic friend.', 'Um amigo compreensivo.'),
('empathetic', 'empático', 'emotions', 'intermediate', '/ˌempəˈθetɪk/', 'Sharing feelings', 'Be empathetic.', 'Sê empático.')

ON CONFLICT (word) DO NOTHING;
