-- Base Vocabulary - Advanced Level (Part 1: 250 words)
-- Academic, Formal, Sophisticated Vocabulary

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- Academic & Formal Vocabulary
('abstract', 'abstrato', 'academic', 'advanced', '/ˈæbstrækt/', 'Theoretical, not concrete', 'Abstract concepts are difficult.', 'Conceitos abstratos são difíceis.'),
('accumulate', 'acumular', 'academic', 'advanced', '/əˈkjuːmjəleɪt/', 'To gather over time', 'Accumulate wealth.', 'Acumular riqueza.'),
('acknowledge', 'reconhecer', 'academic', 'advanced', '/əkˈnɑːlɪdʒ/', 'To admit or recognize', 'Acknowledge your mistakes.', 'Reconhece os teus erros.'),
('acquire', 'adquirir', 'academic', 'advanced', '/əˈkwaɪər/', 'To obtain', 'Acquire new skills.', 'Adquirir novas competências.'),
('adequate', 'adequado', 'academic', 'advanced', '/ˈædɪkwət/', 'Sufficient', 'Adequate resources.', 'Recursos adequados.'),
('adjacent', 'adjacente', 'academic', 'advanced', '/əˈdʒeɪsənt/', 'Next to', 'Adjacent buildings.', 'Edifícios adjacentes.'),
('advocate', 'defender', 'academic', 'advanced', '/ˈædvəkeɪt/', 'To support publicly', 'Advocate for change.', 'Defender a mudança.'),
('aggregate', 'agregar', 'academic', 'advanced', '/ˈæɡrɪɡeɪt/', 'To combine', 'Aggregate the data.', 'Agregar os dados.'),
('albeit', 'embora', 'academic', 'advanced', '/ɔːlˈbiːɪt/', 'Although', 'Albeit difficult, it is possible.', 'Embora difícil, é possível.'),
('allocate', 'alocar', 'academic', 'advanced', '/ˈæləkeɪt/', 'To distribute', 'Allocate resources.', 'Alocar recursos.'),
('ambiguous', 'ambíguo', 'academic', 'advanced', '/æmˈbɪɡjuəs/', 'Unclear', 'An ambiguous statement.', 'Uma afirmação ambígua.'),
('amend', 'emendar', 'academic', 'advanced', '/əˈmend/', 'To change', 'Amend the document.', 'Emendar o documento.'),
('analogous', 'análogo', 'academic', 'advanced', '/əˈnæləɡəs/', 'Similar', 'Analogous situations.', 'Situações análogas.'),
('anticipate', 'antecipar', 'academic', 'advanced', '/ænˈtɪsɪpeɪt/', 'To expect', 'Anticipate problems.', 'Antecipar problemas.'),
('apparent', 'aparente', 'academic', 'advanced', '/əˈpærənt/', 'Obvious', 'It became apparent.', 'Tornou-se aparente.'),
('arbitrary', 'arbitrário', 'academic', 'advanced', '/ˈɑːrbɪtreri/', 'Random', 'An arbitrary decision.', 'Uma decisão arbitrária.'),
('articulate', 'articular', 'academic', 'advanced', '/ɑːrˈtɪkjuleɪt/', 'To express clearly', 'Articulate your thoughts.', 'Articula os teus pensamentos.'),
('ascertain', 'averiguar', 'academic', 'advanced', '/ˌæsərˈteɪn/', 'To find out', 'Ascertain the truth.', 'Averiguar a verdade.'),
('assert', 'afirmar', 'academic', 'advanced', '/əˈsɜːrt/', 'To state firmly', 'Assert your rights.', 'Afirma os teus direitos.'),
('attribute', 'atribuir', 'academic', 'advanced', '/əˈtrɪbjuːt/', 'To assign', 'Attribute success to hard work.', 'Atribuir o sucesso ao trabalho árduo.'),
('augment', 'aumentar', 'academic', 'advanced', '/ɔːɡˈment/', 'To increase', 'Augment your income.', 'Aumentar o teu rendimento.'),
('coherent', 'coerente', 'academic', 'advanced', '/koʊˈhɪrənt/', 'Logical', 'A coherent argument.', 'Um argumento coerente.'),
('coincide', 'coincidir', 'academic', 'advanced', '/ˌkoʊɪnˈsaɪd/', 'To happen at same time', 'The events coincide.', 'Os eventos coincidem.'),
('collaborate', 'colaborar', 'academic', 'advanced', '/kəˈlæbəreɪt/', 'To work together', 'Collaborate on the project.', 'Colaborar no projeto.'),
('commence', 'começar', 'academic', 'advanced', '/kəˈmens/', 'To begin', 'Commence the ceremony.', 'Iniciar a cerimónia.'),
('compensate', 'compensar', 'academic', 'advanced', '/ˈkɑːmpənseɪt/', 'To make up for', 'Compensate for the loss.', 'Compensar a perda.'),
('compile', 'compilar', 'academic', 'advanced', '/kəmˈpaɪl/', 'To put together', 'Compile the data.', 'Compilar os dados.'),
('complement', 'complementar', 'academic', 'advanced', '/ˈkɑːmpləment/', 'To complete', 'They complement each other.', 'Complementam-se.'),
('comprehensive', 'abrangente', 'academic', 'advanced', '/ˌkɑːmprɪˈhensɪv/', 'Complete', 'A comprehensive study.', 'Um estudo abrangente.'),
('comprise', 'compreender', 'academic', 'advanced', '/kəmˈpraɪz/', 'To consist of', 'The team comprises five members.', 'A equipa compreende cinco membros.'),
('conceive', 'conceber', 'academic', 'advanced', '/kənˈsiːv/', 'To think of', 'Conceive a plan.', 'Conceber um plano.'),
('concurrent', 'simultâneo', 'academic', 'advanced', '/kənˈkɜːrənt/', 'At the same time', 'Concurrent events.', 'Eventos simultâneos.'),
('conform', 'conformar', 'academic', 'advanced', '/kənˈfɔːrm/', 'To comply', 'Conform to standards.', 'Conformar-se aos padrões.'),
('consensus', 'consenso', 'academic', 'advanced', '/kənˈsensəs/', 'Agreement', 'Reach a consensus.', 'Chegar a um consenso.'),
('consequent', 'consequente', 'academic', 'advanced', '/ˈkɑːnsɪkwənt/', 'Following as result', 'Consequent changes.', 'Mudanças consequentes.'),
('considerable', 'considerável', 'academic', 'advanced', '/kənˈsɪdərəbəl/', 'Large in amount', 'Considerable effort.', 'Esforço considerável.'),
('constitute', 'constituir', 'academic', 'advanced', '/ˈkɑːnstɪtuːt/', 'To make up', 'Constitute a majority.', 'Constituir a maioria.'),
('constrain', 'restringir', 'academic', 'advanced', '/kənˈstreɪn/', 'To limit', 'Constrain spending.', 'Restringir gastos.'),
('contemporary', 'contemporâneo', 'academic', 'advanced', '/kənˈtempəreri/', 'Modern', 'Contemporary art.', 'Arte contemporânea.'),
('contradict', 'contradizer', 'academic', 'advanced', '/ˌkɑːntrəˈdɪkt/', 'To deny', 'Do not contradict yourself.', 'Não te contradigas.'),
('contrary', 'contrário', 'academic', 'advanced', '/ˈkɑːntreri/', 'Opposite', 'On the contrary.', 'Pelo contrário.'),
('controversy', 'controvérsia', 'academic', 'advanced', '/ˈkɑːntrəvɜːrsi/', 'Dispute', 'Create controversy.', 'Criar controvérsia.'),
('convene', 'convocar', 'academic', 'advanced', '/kənˈviːn/', 'To assemble', 'Convene a meeting.', 'Convocar uma reunião.'),
('conventional', 'convencional', 'academic', 'advanced', '/kənˈvenʃənəl/', 'Traditional', 'Conventional methods.', 'Métodos convencionais.'),
('converse', 'inverso', 'academic', 'advanced', '/ˈkɑːnvɜːrs/', 'Opposite', 'The converse is true.', 'O inverso é verdade.'),
('convey', 'transmitir', 'academic', 'advanced', '/kənˈveɪ/', 'To communicate', 'Convey a message.', 'Transmitir uma mensagem.'),
('correspond', 'corresponder', 'academic', 'advanced', '/ˌkɔːrəˈspɑːnd/', 'To match', 'The numbers correspond.', 'Os números correspondem.'),
('criterion', 'critério', 'academic', 'advanced', '/kraɪˈtɪriən/', 'Standard', 'The main criterion.', 'O critério principal.'),
('crucial', 'crucial', 'academic', 'advanced', '/ˈkruːʃəl/', 'Essential', 'A crucial decision.', 'Uma decisão crucial.'),
('cumulative', 'cumulativo', 'academic', 'advanced', '/ˈkjuːmjəleɪtɪv/', 'Increasing by addition', 'Cumulative effect.', 'Efeito cumulativo.'),

-- Sophisticated Adjectives
('astute', 'astuto', 'adjectives', 'advanced', '/əˈstuːt/', 'Shrewd', 'An astute observation.', 'Uma observação astuta.'),
('benevolent', 'benevolente', 'adjectives', 'advanced', '/bəˈnevələnt/', 'Kind', 'A benevolent leader.', 'Um líder benevolente.'),
('candid', 'cândido', 'adjectives', 'advanced', '/ˈkændɪd/', 'Honest', 'A candid opinion.', 'Uma opinião cândida.'),
('compelling', 'convincente', 'adjectives', 'advanced', '/kəmˈpelɪŋ/', 'Persuasive', 'A compelling argument.', 'Um argumento convincente.'),
('comprehensive', 'abrangente', 'adjectives', 'advanced', '/ˌkɑːmprɪˈhensɪv/', 'Thorough', 'A comprehensive analysis.', 'Uma análise abrangente.'),
('concise', 'conciso', 'adjectives', 'advanced', '/kənˈsaɪs/', 'Brief', 'A concise summary.', 'Um resumo conciso.'),
('conducive', 'conducente', 'adjectives', 'advanced', '/kənˈduːsɪv/', 'Favorable', 'Conducive to learning.', 'Conducente à aprendizagem.'),
('conscientious', 'consciencioso', 'adjectives', 'advanced', '/ˌkɑːnʃiˈenʃəs/', 'Careful', 'A conscientious worker.', 'Um trabalhador consciencioso.'),
('conspicuous', 'conspícuo', 'adjectives', 'advanced', '/kənˈspɪkjuəs/', 'Noticeable', 'A conspicuous absence.', 'Uma ausência conspícua.'),
('contingent', 'contingente', 'adjectives', 'advanced', '/kənˈtɪndʒənt/', 'Dependent on', 'Contingent on approval.', 'Contingente à aprovação.'),
('convoluted', 'convolucionado', 'adjectives', 'advanced', '/ˈkɑːnvəluːtɪd/', 'Complex', 'A convoluted explanation.', 'Uma explicação convolucionada.'),
('copious', 'copioso', 'adjectives', 'advanced', '/ˈkoʊpiəs/', 'Abundant', 'Copious notes.', 'Notas copiosas.'),
('credible', 'credível', 'adjectives', 'advanced', '/ˈkredəbəl/', 'Believable', 'A credible source.', 'Uma fonte credível.'),
('definitive', 'definitivo', 'adjectives', 'advanced', '/dɪˈfɪnətɪv/', 'Final', 'The definitive answer.', 'A resposta definitiva.'),
('deliberate', 'deliberado', 'adjectives', 'advanced', '/dɪˈlɪbərət/', 'Intentional', 'A deliberate action.', 'Uma ação deliberada.'),
('detrimental', 'prejudicial', 'adjectives', 'advanced', '/ˌdetrɪˈmentəl/', 'Harmful', 'Detrimental effects.', 'Efeitos prejudiciais.'),
('discernible', 'discernível', 'adjectives', 'advanced', '/dɪˈsɜːrnəbəl/', 'Visible', 'A discernible pattern.', 'Um padrão discernível.'),
('discrete', 'discreto', 'adjectives', 'advanced', '/dɪˈskriːt/', 'Separate', 'Discrete categories.', 'Categorias discretas.'),
('disparate', 'díspar', 'adjectives', 'advanced', '/ˈdɪspərət/', 'Different', 'Disparate views.', 'Pontos de vista díspares.'),
('elusive', 'elusivo', 'adjectives', 'advanced', '/ɪˈluːsɪv/', 'Hard to find', 'An elusive goal.', 'Um objetivo elusivo.'),
('empirical', 'empírico', 'adjectives', 'advanced', '/ɪmˈpɪrɪkəl/', 'Based on observation', 'Empirical evidence.', 'Evidência empírica.'),
('erroneous', 'errôneo', 'adjectives', 'advanced', '/ɪˈroʊniəs/', 'Wrong', 'An erroneous assumption.', 'Uma suposição errônea.'),
('exacerbate', 'exacerbar', 'adjectives', 'advanced', '/ɪɡˈzæsərbeɪt/', 'To worsen', 'Exacerbate the problem.', 'Exacerbar o problema.'),
('explicit', 'explícito', 'adjectives', 'advanced', '/ɪkˈsplɪsɪt/', 'Clear', 'Explicit instructions.', 'Instruções explícitas.'),
('feasible', 'viável', 'adjectives', 'advanced', '/ˈfiːzəbəl/', 'Possible', 'A feasible plan.', 'Um plano viável.'),
('formidable', 'formidável', 'adjectives', 'advanced', '/ˈfɔːrmɪdəbəl/', 'Impressive', 'A formidable challenge.', 'Um desafio formidável.'),
('futile', 'fútil', 'adjectives', 'advanced', '/ˈfjuːtaɪl/', 'Pointless', 'A futile attempt.', 'Uma tentativa fútil.'),
('gratuitous', 'gratuito', 'adjectives', 'advanced', '/ɡrəˈtuːɪtəs/', 'Unnecessary', 'Gratuitous violence.', 'Violência gratuita.'),
('hypothetical', 'hipotético', 'adjectives', 'advanced', '/ˌhaɪpəˈθetɪkəl/', 'Supposed', 'A hypothetical scenario.', 'Um cenário hipotético.'),
('imminent', 'iminente', 'adjectives', 'advanced', '/ˈɪmɪnənt/', 'About to happen', 'Imminent danger.', 'Perigo iminente.'),
('implicit', 'implícito', 'adjectives', 'advanced', '/ɪmˈplɪsɪt/', 'Implied', 'Implicit meaning.', 'Significado implícito.'),
('inadvertent', 'inadvertido', 'adjectives', 'advanced', '/ˌɪnədˈvɜːrtənt/', 'Unintentional', 'An inadvertent error.', 'Um erro inadvertido.'),
('inherent', 'inerente', 'adjectives', 'advanced', '/ɪnˈhɪrənt/', 'Built-in', 'Inherent risks.', 'Riscos inerentes.'),
('instrumental', 'instrumental', 'adjectives', 'advanced', '/ˌɪnstrəˈmentəl/', 'Important', 'Instrumental in success.', 'Instrumental para o sucesso.'),
('integral', 'integral', 'adjectives', 'advanced', '/ˈɪntɪɡrəl/', 'Essential', 'An integral part.', 'Uma parte integral.'),
('intricate', 'intrincado', 'adjectives', 'advanced', '/ˈɪntrɪkət/', 'Complex', 'An intricate design.', 'Um design intrincado.'),
('intrinsic', 'intrínseco', 'adjectives', 'advanced', '/ɪnˈtrɪnsɪk/', 'Inherent', 'Intrinsic value.', 'Valor intrínseco.'),
('lucid', 'lúcido', 'adjectives', 'advanced', '/ˈluːsɪd/', 'Clear', 'A lucid explanation.', 'Uma explicação lúcida.'),
('meticulous', 'meticuloso', 'adjectives', 'advanced', '/məˈtɪkjələs/', 'Careful', 'Meticulous attention.', 'Atenção meticulosa.'),
('mitigate', 'mitigar', 'adjectives', 'advanced', '/ˈmɪtɪɡeɪt/', 'To reduce', 'Mitigate risks.', 'Mitigar riscos.'),
('negligible', 'negligenciável', 'adjectives', 'advanced', '/ˈneɡlɪdʒəbəl/', 'Tiny', 'A negligible amount.', 'Uma quantidade negligenciável.'),
('nuanced', 'matizado', 'adjectives', 'advanced', '/ˈnuːɑːnst/', 'Subtle', 'A nuanced view.', 'Uma visão matizada.'),
('obsolete', 'obsoleto', 'adjectives', 'advanced', '/ˌɑːbsəˈliːt/', 'Outdated', 'Obsolete technology.', 'Tecnologia obsoleta.'),
('ostensible', 'ostensivo', 'adjectives', 'advanced', '/ɑːˈstensəbəl/', 'Apparent', 'The ostensible reason.', 'A razão ostensiva.'),
('paramount', 'primordial', 'adjectives', 'advanced', '/ˈpærəmaʊnt/', 'Supreme', 'Of paramount importance.', 'De importância primordial.'),
('pervasive', 'pervasivo', 'adjectives', 'advanced', '/pərˈveɪsɪv/', 'Widespread', 'A pervasive problem.', 'Um problema pervasivo.'),
('plausible', 'plausível', 'adjectives', 'advanced', '/ˈplɔːzəbəl/', 'Reasonable', 'A plausible explanation.', 'Uma explicação plausível.'),
('pragmatic', 'pragmático', 'adjectives', 'advanced', '/præɡˈmætɪk/', 'Practical', 'A pragmatic approach.', 'Uma abordagem pragmática.'),
('precedent', 'precedente', 'adjectives', 'advanced', '/ˈpresɪdənt/', 'Earlier example', 'Set a precedent.', 'Estabelecer um precedente.'),
('preliminary', 'preliminar', 'adjectives', 'advanced', '/prɪˈlɪmɪneri/', 'Initial', 'Preliminary results.', 'Resultados preliminares.')

ON CONFLICT (word) DO UPDATE SET
  translation = EXCLUDED.translation,
  category = EXCLUDED.category,
  difficulty = EXCLUDED.difficulty,
  pronunciation = EXCLUDED.pronunciation,
  definition = EXCLUDED.definition,
  example_sentence = EXCLUDED.example_sentence,
  example_translation = EXCLUDED.example_translation,
  updated_at = now();
