-- Base Vocabulary - Advanced Level (Part 2: 250 words)
-- More Advanced Vocabulary - Verbs, Nouns, Connectors

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- Advanced Verbs
('abolish', 'abolir', 'verbs', 'advanced', '/əˈbɑːlɪʃ/', 'To end formally', 'Abolish slavery.', 'Abolir a escravatura.'),
('abstain', 'abster-se', 'verbs', 'advanced', '/əbˈsteɪn/', 'To refrain', 'Abstain from voting.', 'Abster-se de votar.'),
('accentuate', 'acentuar', 'verbs', 'advanced', '/əkˈsentʃueɪt/', 'To emphasize', 'Accentuate the positive.', 'Acentuar o positivo.'),
('alleviate', 'aliviar', 'verbs', 'advanced', '/əˈliːvieɪt/', 'To reduce', 'Alleviate pain.', 'Aliviar a dor.'),
('amalgamate', 'amalgamar', 'verbs', 'advanced', '/əˈmælɡəmeɪt/', 'To combine', 'Amalgamate companies.', 'Amalgamar empresas.'),
('ameliorate', 'melhorar', 'verbs', 'advanced', '/əˈmiːliəreɪt/', 'To make better', 'Ameliorate conditions.', 'Melhorar as condições.'),
('annihilate', 'aniquilar', 'verbs', 'advanced', '/əˈnaɪəleɪt/', 'To destroy', 'Annihilate the enemy.', 'Aniquilar o inimigo.'),
('appease', 'apaziguar', 'verbs', 'advanced', '/əˈpiːz/', 'To calm', 'Appease the critics.', 'Apaziguar os críticos.'),
('apprehend', 'apreender', 'verbs', 'advanced', '/ˌæprɪˈhend/', 'To arrest or understand', 'Apprehend the suspect.', 'Apreender o suspeito.'),
('ascribe', 'atribuir', 'verbs', 'advanced', '/əˈskraɪb/', 'To attribute', 'Ascribe blame to.', 'Atribuir a culpa a.'),
('assimilate', 'assimilar', 'verbs', 'advanced', '/əˈsɪməleɪt/', 'To absorb', 'Assimilate information.', 'Assimilar informação.'),
('attenuate', 'atenuar', 'verbs', 'advanced', '/əˈtenjueɪt/', 'To weaken', 'Attenuate the signal.', 'Atenuar o sinal.'),
('bequeath', 'legar', 'verbs', 'advanced', '/bɪˈkwiːð/', 'To leave in will', 'Bequeath a fortune.', 'Legar uma fortuna.'),
('circumvent', 'contornar', 'verbs', 'advanced', '/ˌsɜːrkəmˈvent/', 'To bypass', 'Circumvent the rules.', 'Contornar as regras.'),
('coalesce', 'fundir-se', 'verbs', 'advanced', '/ˌkoʊəˈles/', 'To merge', 'Ideas coalesce.', 'Ideias fundem-se.'),
('coerce', 'coagir', 'verbs', 'advanced', '/koʊˈɜːrs/', 'To force', 'Coerce into action.', 'Coagir à ação.'),
('cognizant', 'ciente', 'verbs', 'advanced', '/ˈkɑːɡnɪzənt/', 'Aware', 'Be cognizant of risks.', 'Estar ciente dos riscos.'),
('commend', 'elogiar', 'verbs', 'advanced', '/kəˈmend/', 'To praise', 'Commend their efforts.', 'Elogiar os seus esforços.'),
('commensurate', 'proporcional', 'verbs', 'advanced', '/kəˈmenʃərət/', 'Corresponding', 'Salary commensurate with experience.', 'Salário proporcional à experiência.'),
('compel', 'compelir', 'verbs', 'advanced', '/kəmˈpel/', 'To force', 'Compel action.', 'Compelir à ação.'),
('condone', 'tolerar', 'verbs', 'advanced', '/kənˈdoʊn/', 'To accept', 'Cannot condone violence.', 'Não posso tolerar violência.'),
('confound', 'confundir', 'verbs', 'advanced', '/kənˈfaʊnd/', 'To puzzle', 'Confound expectations.', 'Confundir expectativas.'),
('conjecture', 'conjeturar', 'verbs', 'advanced', '/kənˈdʒektʃər/', 'To guess', 'We can only conjecture.', 'Só podemos conjeturar.'),
('connote', 'conotar', 'verbs', 'advanced', '/kəˈnoʊt/', 'To imply', 'The word connotes.', 'A palavra conota.'),
('consolidate', 'consolidar', 'verbs', 'advanced', '/kənˈsɑːlɪdeɪt/', 'To strengthen', 'Consolidate power.', 'Consolidar o poder.'),
('construe', 'interpretar', 'verbs', 'advanced', '/kənˈstruː/', 'To interpret', 'Construe the meaning.', 'Interpretar o significado.'),
('contemplate', 'contemplar', 'verbs', 'advanced', '/ˈkɑːntəmpleɪt/', 'To consider', 'Contemplate the future.', 'Contemplar o futuro.'),
('contend', 'contestar', 'verbs', 'advanced', '/kənˈtend/', 'To argue', 'I contend that.', 'Defendo que.'),
('corroborate', 'corroborar', 'verbs', 'advanced', '/kəˈrɑːbəreɪt/', 'To confirm', 'Corroborate the story.', 'Corroborar a história.'),
('curtail', 'reduzir', 'verbs', 'advanced', '/kɜːrˈteɪl/', 'To cut short', 'Curtail expenses.', 'Reduzir despesas.'),
('debilitate', 'debilitar', 'verbs', 'advanced', '/dɪˈbɪləteɪt/', 'To weaken', 'A debilitating illness.', 'Uma doença debilitante.'),
('decipher', 'decifrar', 'verbs', 'advanced', '/dɪˈsaɪfər/', 'To decode', 'Decipher the message.', 'Decifrar a mensagem.'),
('delineate', 'delinear', 'verbs', 'advanced', '/dɪˈlɪnieɪt/', 'To describe', 'Delineate the plan.', 'Delinear o plano.'),
('demarcate', 'demarcar', 'verbs', 'advanced', '/ˈdiːmɑːrkeɪt/', 'To mark boundaries', 'Demarcate the area.', 'Demarcar a área.'),
('denigrate', 'denegrir', 'verbs', 'advanced', '/ˈdenɪɡreɪt/', 'To criticize unfairly', 'Denigrate rivals.', 'Denegrir os rivais.'),
('denote', 'denotar', 'verbs', 'advanced', '/dɪˈnoʊt/', 'To indicate', 'This denotes success.', 'Isto denota sucesso.'),
('deplete', 'esgotar', 'verbs', 'advanced', '/dɪˈpliːt/', 'To exhaust', 'Deplete resources.', 'Esgotar recursos.'),
('deprecate', 'depreciar', 'verbs', 'advanced', '/ˈdeprəkeɪt/', 'To disapprove', 'Deprecate the idea.', 'Depreciar a ideia.'),
('derive', 'derivar', 'verbs', 'advanced', '/dɪˈraɪv/', 'To obtain from', 'Derive pleasure from.', 'Derivar prazer de.'),
('designate', 'designar', 'verbs', 'advanced', '/ˈdezɪɡneɪt/', 'To appoint', 'Designate a leader.', 'Designar um líder.'),
('deter', 'dissuadir', 'verbs', 'advanced', '/dɪˈtɜːr/', 'To discourage', 'Deter crime.', 'Dissuadir o crime.'),
('deviate', 'desviar', 'verbs', 'advanced', '/ˈdiːvieɪt/', 'To stray', 'Deviate from the plan.', 'Desviar do plano.'),
('diminish', 'diminuir', 'verbs', 'advanced', '/dɪˈmɪnɪʃ/', 'To reduce', 'Diminish the impact.', 'Diminuir o impacto.'),
('discern', 'discernir', 'verbs', 'advanced', '/dɪˈsɜːrn/', 'To perceive', 'Discern the truth.', 'Discernir a verdade.'),
('disclose', 'divulgar', 'verbs', 'advanced', '/dɪsˈkloʊz/', 'To reveal', 'Disclose information.', 'Divulgar informação.'),
('discriminate', 'discriminar', 'verbs', 'advanced', '/dɪˈskrɪmɪneɪt/', 'To distinguish', 'Discriminate between.', 'Discriminar entre.'),
('disdain', 'desdenhar', 'verbs', 'advanced', '/dɪsˈdeɪn/', 'To scorn', 'Disdain authority.', 'Desdenhar a autoridade.'),
('dismantle', 'desmantelar', 'verbs', 'advanced', '/dɪsˈmæntl/', 'To take apart', 'Dismantle the system.', 'Desmantelar o sistema.'),
('disparage', 'menosprezar', 'verbs', 'advanced', '/dɪˈspærɪdʒ/', 'To belittle', 'Disparage achievements.', 'Menosprezar conquistas.'),
('dispel', 'dissipar', 'verbs', 'advanced', '/dɪˈspel/', 'To drive away', 'Dispel doubts.', 'Dissipar dúvidas.'),
('disseminate', 'disseminar', 'verbs', 'advanced', '/dɪˈseməneɪt/', 'To spread', 'Disseminate information.', 'Disseminar informação.'),
('dissuade', 'dissuadir', 'verbs', 'advanced', '/dɪˈsweɪd/', 'To deter', 'Dissuade from action.', 'Dissuadir da ação.'),
('distort', 'distorcer', 'verbs', 'advanced', '/dɪˈstɔːrt/', 'To twist', 'Distort the truth.', 'Distorcer a verdade.'),
('divulge', 'divulgar', 'verbs', 'advanced', '/daɪˈvʌldʒ/', 'To reveal', 'Divulge secrets.', 'Divulgar segredos.'),
('elucidate', 'elucidar', 'verbs', 'advanced', '/ɪˈluːsɪdeɪt/', 'To clarify', 'Elucidate the matter.', 'Elucidar a questão.'),
('emanate', 'emanar', 'verbs', 'advanced', '/ˈeməneɪt/', 'To issue from', 'Light emanates.', 'A luz emana.'),
('embark', 'embarcar', 'verbs', 'advanced', '/ɪmˈbɑːrk/', 'To begin', 'Embark on a journey.', 'Embarcar numa viagem.'),
('embody', 'personificar', 'verbs', 'advanced', '/ɪmˈbɑːdi/', 'To represent', 'Embody the values.', 'Personificar os valores.'),
('emulate', 'emular', 'verbs', 'advanced', '/ˈemjuleɪt/', 'To imitate', 'Emulate success.', 'Emular o sucesso.'),
('enact', 'promulgar', 'verbs', 'advanced', '/ɪˈnækt/', 'To make law', 'Enact legislation.', 'Promulgar legislação.'),

-- Advanced Nouns
('abundance', 'abundância', 'nouns', 'advanced', '/əˈbʌndəns/', 'Large quantity', 'An abundance of resources.', 'Uma abundância de recursos.'),
('acumen', 'perspicácia', 'nouns', 'advanced', '/əˈkjuːmən/', 'Sharpness', 'Business acumen.', 'Perspicácia para os negócios.'),
('adversity', 'adversidade', 'nouns', 'advanced', '/ədˈvɜːrsəti/', 'Hardship', 'Face adversity.', 'Enfrentar adversidade.'),
('affinity', 'afinidade', 'nouns', 'advanced', '/əˈfɪnəti/', 'Attraction', 'Natural affinity.', 'Afinidade natural.'),
('ambiguity', 'ambiguidade', 'nouns', 'advanced', '/ˌæmbɪˈɡjuːəti/', 'Uncertainty', 'Remove ambiguity.', 'Remover ambiguidade.'),
('anomaly', 'anomalia', 'nouns', 'advanced', '/əˈnɑːməli/', 'Irregularity', 'A statistical anomaly.', 'Uma anomalia estatística.'),
('antithesis', 'antítese', 'nouns', 'advanced', '/ænˈtɪθəsɪs/', 'Opposite', 'The antithesis of.', 'A antítese de.'),
('apprehension', 'apreensão', 'nouns', 'advanced', '/ˌæprɪˈhenʃən/', 'Anxiety', 'Feel apprehension.', 'Sentir apreensão.'),
('archetype', 'arquétipo', 'nouns', 'advanced', '/ˈɑːrkɪtaɪp/', 'Original model', 'The archetype of.', 'O arquétipo de.'),
('austerity', 'austeridade', 'nouns', 'advanced', '/ɔːˈsterəti/', 'Severity', 'Economic austerity.', 'Austeridade económica.'),
('autonomy', 'autonomia', 'nouns', 'advanced', '/ɔːˈtɑːnəmi/', 'Independence', 'Personal autonomy.', 'Autonomia pessoal.'),
('brevity', 'brevidade', 'nouns', 'advanced', '/ˈbrevəti/', 'Shortness', 'Brevity is key.', 'A brevidade é fundamental.'),
('bureaucracy', 'burocracia', 'nouns', 'advanced', '/bjʊˈrɑːkrəsi/', 'Official system', 'Government bureaucracy.', 'Burocracia governamental.'),
('catalyst', 'catalisador', 'nouns', 'advanced', '/ˈkætəlɪst/', 'Trigger', 'A catalyst for change.', 'Um catalisador de mudança.'),
('caveat', 'ressalva', 'nouns', 'advanced', '/ˈkæviæt/', 'Warning', 'With one caveat.', 'Com uma ressalva.'),
('coherence', 'coerência', 'nouns', 'advanced', '/koʊˈhɪrəns/', 'Logical connection', 'Maintain coherence.', 'Manter coerência.'),
('colloquialism', 'coloquialismo', 'nouns', 'advanced', '/kəˈloʊkwiəlɪzəm/', 'Informal expression', 'A common colloquialism.', 'Um coloquialismo comum.'),
('commencement', 'início', 'nouns', 'advanced', '/kəˈmensmənt/', 'Beginning', 'At the commencement.', 'No início.'),
('competence', 'competência', 'nouns', 'advanced', '/ˈkɑːmpɪtəns/', 'Ability', 'Professional competence.', 'Competência profissional.'),
('compliance', 'conformidade', 'nouns', 'advanced', '/kəmˈplaɪəns/', 'Obedience', 'Legal compliance.', 'Conformidade legal.'),
('connotation', 'conotação', 'nouns', 'advanced', '/ˌkɑːnəˈteɪʃən/', 'Implied meaning', 'Negative connotation.', 'Conotação negativa.'),
('constituent', 'constituinte', 'nouns', 'advanced', '/kənˈstɪtʃuənt/', 'Component', 'Key constituent.', 'Constituinte-chave.'),
('contingency', 'contingência', 'nouns', 'advanced', '/kənˈtɪndʒənsi/', 'Possibility', 'Contingency plan.', 'Plano de contingência.'),
('conundrum', 'enigma', 'nouns', 'advanced', '/kəˈnʌndrəm/', 'Puzzle', 'A moral conundrum.', 'Um enigma moral.'),
('cornerstone', 'pedra angular', 'nouns', 'advanced', '/ˈkɔːrnərstoʊn/', 'Foundation', 'The cornerstone of.', 'A pedra angular de.'),
('correlation', 'correlação', 'nouns', 'advanced', '/ˌkɔːrəˈleɪʃən/', 'Relationship', 'Strong correlation.', 'Correlação forte.'),
('credibility', 'credibilidade', 'nouns', 'advanced', '/ˌkredəˈbɪləti/', 'Believability', 'Lose credibility.', 'Perder credibilidade.'),
('detriment', 'detrimento', 'nouns', 'advanced', '/ˈdetrɪmənt/', 'Harm', 'To the detriment of.', 'Em detrimento de.'),
('dichotomy', 'dicotomia', 'nouns', 'advanced', '/daɪˈkɑːtəmi/', 'Division', 'A false dichotomy.', 'Uma falsa dicotomia.'),
('dilemma', 'dilema', 'nouns', 'advanced', '/dɪˈlemə/', 'Difficult choice', 'A moral dilemma.', 'Um dilema moral.'),
('discrepancy', 'discrepância', 'nouns', 'advanced', '/dɪˈskrepənsi/', 'Difference', 'A major discrepancy.', 'Uma discrepância maior.'),
('disparity', 'disparidade', 'nouns', 'advanced', '/dɪˈspærəti/', 'Inequality', 'Income disparity.', 'Disparidade de rendimentos.'),
('disposition', 'disposição', 'nouns', 'advanced', '/ˌdɪspəˈzɪʃən/', 'Temperament', 'A cheerful disposition.', 'Uma disposição alegre.'),
('divergence', 'divergência', 'nouns', 'advanced', '/daɪˈvɜːrdʒəns/', 'Difference', 'A divergence of opinion.', 'Uma divergência de opinião.'),
('efficacy', 'eficácia', 'nouns', 'advanced', '/ˈefɪkəsi/', 'Effectiveness', 'Proven efficacy.', 'Eficácia comprovada.'),
('elucidation', 'elucidação', 'nouns', 'advanced', '/ɪˌluːsɪˈdeɪʃən/', 'Clarification', 'Further elucidation.', 'Maior elucidação.'),
('embodiment', 'personificação', 'nouns', 'advanced', '/ɪmˈbɑːdimənt/', 'Representation', 'The embodiment of.', 'A personificação de.'),
('eminence', 'eminência', 'nouns', 'advanced', '/ˈemɪnəns/', 'High standing', 'A person of eminence.', 'Uma pessoa de eminência.'),
('endeavor', 'empreendimento', 'nouns', 'advanced', '/ɪnˈdevər/', 'Effort', 'A worthy endeavor.', 'Um empreendimento digno.'),
('enigma', 'enigma', 'nouns', 'advanced', '/ɪˈnɪɡmə/', 'Mystery', 'An unsolved enigma.', 'Um enigma não resolvido.'),

-- Linking Words & Connectors
('notwithstanding', 'não obstante', 'connectors', 'advanced', '/ˌnɑːtwɪθˈstændɪŋ/', 'Despite', 'Notwithstanding the difficulties.', 'Não obstante as dificuldades.'),
('hitherto', 'até agora', 'connectors', 'advanced', '/ˌhɪðərˈtuː/', 'Until now', 'Hitherto unknown.', 'Até agora desconhecido.'),
('whereby', 'pelo qual', 'connectors', 'advanced', '/werˈbaɪ/', 'By which', 'A system whereby.', 'Um sistema pelo qual.'),
('wherein', 'em que', 'connectors', 'advanced', '/werˈɪn/', 'In which', 'A situation wherein.', 'Uma situação em que.'),
('thereof', 'do mesmo', 'connectors', 'advanced', '/ðerˈʌv/', 'Of that', 'And derivatives thereof.', 'E derivados do mesmo.'),
('inasmuch', 'na medida em que', 'connectors', 'advanced', '/ˌɪnəzˈmʌtʃ/', 'Since', 'Inasmuch as it is true.', 'Na medida em que é verdade.'),
('forthwith', 'imediatamente', 'connectors', 'advanced', '/ˌfɔːrθˈwɪθ/', 'Immediately', 'Act forthwith.', 'Agir imediatamente.'),
('heretofore', 'até aqui', 'connectors', 'advanced', '/ˌhɪrtəˈfɔːr/', 'Before now', 'Heretofore unseen.', 'Até aqui não visto.'),
('henceforth', 'doravante', 'connectors', 'advanced', '/ˌhensˈfɔːrθ/', 'From now on', 'Henceforth known as.', 'Doravante conhecido como.'),
('insofar', 'na medida em que', 'connectors', 'advanced', '/ˌɪnsəˈfɑːr/', 'To the extent', 'Insofar as possible.', 'Na medida do possível.')

ON CONFLICT (word) DO UPDATE SET
  translation = EXCLUDED.translation,
  category = EXCLUDED.category,
  difficulty = EXCLUDED.difficulty,
  pronunciation = EXCLUDED.pronunciation,
  definition = EXCLUDED.definition,
  example_sentence = EXCLUDED.example_sentence,
  example_translation = EXCLUDED.example_translation,
  updated_at = now();
