-- Base Vocabulary - Advanced Level (Part 3: 250 words)
-- Legal, Medical, Scientific, Business Vocabulary

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- Legal & Formal Terms
('adjudicate', 'adjudicar', 'legal', 'advanced', '/əˈdʒuːdɪkeɪt/', 'To judge', 'Adjudicate disputes.', 'Adjudicar disputas.'),
('affidavit', 'declaração juramentada', 'legal', 'advanced', '/ˌæfɪˈdeɪvɪt/', 'Sworn statement', 'Sign an affidavit.', 'Assinar uma declaração juramentada.'),
('allegation', 'alegação', 'legal', 'advanced', '/ˌæləˈɡeɪʃən/', 'Claim', 'Serious allegations.', 'Alegações sérias.'),
('arbitration', 'arbitragem', 'legal', 'advanced', '/ˌɑːrbɪˈtreɪʃən/', 'Dispute resolution', 'Go to arbitration.', 'Ir para arbitragem.'),
('breach', 'violação', 'legal', 'advanced', '/briːtʃ/', 'Breaking of rule', 'Breach of contract.', 'Violação de contrato.'),
('clause', 'cláusula', 'legal', 'advanced', '/klɔːz/', 'Section of document', 'A confidentiality clause.', 'Uma cláusula de confidencialidade.'),
('claimant', 'requerente', 'legal', 'advanced', '/ˈkleɪmənt/', 'Person making claim', 'The claimant argued.', 'O requerente argumentou.'),
('compliance', 'conformidade', 'legal', 'advanced', '/kəmˈplaɪəns/', 'Following rules', 'Regulatory compliance.', 'Conformidade regulamentar.'),
('defendant', 'réu', 'legal', 'advanced', '/dɪˈfendənt/', 'Accused person', 'The defendant pleaded.', 'O réu declarou-se.'),
('disclosure', 'divulgação', 'legal', 'advanced', '/dɪsˈkloʊʒər/', 'Revealing information', 'Full disclosure.', 'Divulgação total.'),
('dispute', 'disputa', 'legal', 'advanced', '/dɪˈspjuːt/', 'Disagreement', 'Legal dispute.', 'Disputa legal.'),
('enforcement', 'aplicação', 'legal', 'advanced', '/ɪnˈfɔːrsmənt/', 'Making people obey', 'Law enforcement.', 'Aplicação da lei.'),
('entitlement', 'direito', 'legal', 'advanced', '/ɪnˈtaɪtəlmənt/', 'Right to something', 'Legal entitlement.', 'Direito legal.'),
('exemption', 'isenção', 'legal', 'advanced', '/ɪɡˈzempʃən/', 'Being excused', 'Tax exemption.', 'Isenção fiscal.'),
('grievance', 'queixa', 'legal', 'advanced', '/ˈɡriːvəns/', 'Complaint', 'File a grievance.', 'Apresentar uma queixa.'),
('indemnity', 'indemnização', 'legal', 'advanced', '/ɪnˈdemnəti/', 'Protection from loss', 'Insurance indemnity.', 'Indemnização do seguro.'),
('jurisdiction', 'jurisdição', 'legal', 'advanced', '/ˌdʒʊrɪsˈdɪkʃən/', 'Legal authority', 'Within jurisdiction.', 'Dentro da jurisdição.'),
('liability', 'responsabilidade', 'legal', 'advanced', '/ˌlaɪəˈbɪləti/', 'Legal responsibility', 'Limited liability.', 'Responsabilidade limitada.'),
('litigation', 'litígio', 'legal', 'advanced', '/ˌlɪtɪˈɡeɪʃən/', 'Legal process', 'Avoid litigation.', 'Evitar litígio.'),
('mandate', 'mandato', 'legal', 'advanced', '/ˈmændeɪt/', 'Official order', 'Government mandate.', 'Mandato governamental.'),
('negligence', 'negligência', 'legal', 'advanced', '/ˈneɡlɪdʒəns/', 'Carelessness', 'Professional negligence.', 'Negligência profissional.'),
('ordinance', 'decreto', 'legal', 'advanced', '/ˈɔːrdɪnəns/', 'Local law', 'City ordinance.', 'Decreto municipal.'),
('plaintiff', 'queixoso', 'legal', 'advanced', '/ˈpleɪntɪf/', 'Person who sues', 'The plaintiff claims.', 'O queixoso alega.'),
('precedent', 'precedente', 'legal', 'advanced', '/ˈpresɪdənt/', 'Earlier case', 'Set a precedent.', 'Estabelecer um precedente.'),
('provision', 'disposição', 'legal', 'advanced', '/prəˈvɪʒən/', 'Clause', 'Contract provisions.', 'Disposições contratuais.'),
('ratify', 'ratificar', 'legal', 'advanced', '/ˈrætɪfaɪ/', 'To approve formally', 'Ratify the treaty.', 'Ratificar o tratado.'),
('restitution', 'restituição', 'legal', 'advanced', '/ˌrestɪˈtuːʃən/', 'Compensation', 'Demand restitution.', 'Exigir restituição.'),
('sanction', 'sanção', 'legal', 'advanced', '/ˈsæŋkʃən/', 'Penalty', 'Economic sanctions.', 'Sanções económicas.'),
('statute', 'estatuto', 'legal', 'advanced', '/ˈstætʃuːt/', 'Written law', 'By statute.', 'Por estatuto.'),
('stipulate', 'estipular', 'legal', 'advanced', '/ˈstɪpjuleɪt/', 'To specify', 'The contract stipulates.', 'O contrato estipula.'),
('subpoena', 'intimação', 'legal', 'advanced', '/səˈpiːnə/', 'Legal summons', 'Issue a subpoena.', 'Emitir uma intimação.'),
('testimony', 'testemunho', 'legal', 'advanced', '/ˈtestɪmoʊni/', 'Evidence given', 'Give testimony.', 'Prestar testemunho.'),
('tribunal', 'tribunal', 'legal', 'advanced', '/traɪˈbjuːnəl/', 'Court', 'International tribunal.', 'Tribunal internacional.'),
('verdict', 'veredicto', 'legal', 'advanced', '/ˈvɜːrdɪkt/', 'Decision', 'Guilty verdict.', 'Veredicto de culpa.'),
('waiver', 'renúncia', 'legal', 'advanced', '/ˈweɪvər/', 'Giving up right', 'Sign a waiver.', 'Assinar uma renúncia.'),

-- Medical & Scientific
('acute', 'agudo', 'medical', 'advanced', '/əˈkjuːt/', 'Severe but short', 'Acute pain.', 'Dor aguda.'),
('benign', 'benigno', 'medical', 'advanced', '/bɪˈnaɪn/', 'Not harmful', 'A benign tumor.', 'Um tumor benigno.'),
('chronic', 'crónico', 'medical', 'advanced', '/ˈkrɑːnɪk/', 'Long-lasting', 'Chronic illness.', 'Doença crónica.'),
('diagnosis', 'diagnóstico', 'medical', 'advanced', '/ˌdaɪəɡˈnoʊsɪs/', 'Identification of illness', 'Early diagnosis.', 'Diagnóstico precoce.'),
('prognosis', 'prognóstico', 'medical', 'advanced', '/prɑːɡˈnoʊsɪs/', 'Forecast of outcome', 'A positive prognosis.', 'Um prognóstico positivo.'),
('syndrome', 'síndrome', 'medical', 'advanced', '/ˈsɪndroʊm/', 'Set of symptoms', 'A rare syndrome.', 'Uma síndrome rara.'),
('pathology', 'patologia', 'medical', 'advanced', '/pəˈθɑːlədʒi/', 'Study of disease', 'Clinical pathology.', 'Patologia clínica.'),
('etiology', 'etiologia', 'medical', 'advanced', '/ˌiːtiˈɑːlədʒi/', 'Cause of disease', 'Unknown etiology.', 'Etiologia desconhecida.'),
('epidemiology', 'epidemiologia', 'medical', 'advanced', '/ˌepɪˌdiːmiˈɑːlədʒi/', 'Study of disease spread', 'Epidemiological research.', 'Investigação epidemiológica.'),
('pharmaceutical', 'farmacêutico', 'medical', 'advanced', '/ˌfɑːrməˈsuːtɪkəl/', 'Drug-related', 'Pharmaceutical industry.', 'Indústria farmacêutica.'),
('hypothesis', 'hipótese', 'scientific', 'advanced', '/haɪˈpɑːθəsɪs/', 'Proposed explanation', 'Test the hypothesis.', 'Testar a hipótese.'),
('methodology', 'metodologia', 'scientific', 'advanced', '/ˌmeθəˈdɑːlədʒi/', 'System of methods', 'Research methodology.', 'Metodologia de investigação.'),
('phenomenon', 'fenómeno', 'scientific', 'advanced', '/fəˈnɑːmɪnən/', 'Observable fact', 'A natural phenomenon.', 'Um fenómeno natural.'),
('paradigm', 'paradigma', 'scientific', 'advanced', '/ˈpærədaɪm/', 'Model or pattern', 'A new paradigm.', 'Um novo paradigma.'),
('quantitative', 'quantitativo', 'scientific', 'advanced', '/ˈkwɑːntɪteɪtɪv/', 'Measurable', 'Quantitative data.', 'Dados quantitativos.'),
('qualitative', 'qualitativo', 'scientific', 'advanced', '/ˈkwɑːlɪteɪtɪv/', 'Descriptive', 'Qualitative analysis.', 'Análise qualitativa.'),
('synthesis', 'síntese', 'scientific', 'advanced', '/ˈsɪnθəsɪs/', 'Combination', 'A synthesis of ideas.', 'Uma síntese de ideias.'),
('variable', 'variável', 'scientific', 'advanced', '/ˈveriəbəl/', 'Changeable factor', 'Independent variable.', 'Variável independente.'),
('correlation', 'correlação', 'scientific', 'advanced', '/ˌkɔːrəˈleɪʃən/', 'Relationship', 'Positive correlation.', 'Correlação positiva.'),
('causation', 'causalidade', 'scientific', 'advanced', '/kɔːˈzeɪʃən/', 'Causing', 'Correlation is not causation.', 'Correlação não é causalidade.'),

-- Business & Economics
('acquisition', 'aquisição', 'business', 'advanced', '/ˌækwɪˈzɪʃən/', 'Purchase', 'Corporate acquisition.', 'Aquisição corporativa.'),
('amalgamation', 'fusão', 'business', 'advanced', '/əˌmælɡəˈmeɪʃən/', 'Merger', 'Company amalgamation.', 'Fusão de empresas.'),
('amortization', 'amortização', 'business', 'advanced', '/əˌmɔːrtɪˈzeɪʃən/', 'Paying off debt', 'Loan amortization.', 'Amortização do empréstimo.'),
('appreciation', 'valorização', 'business', 'advanced', '/əˌpriːʃiˈeɪʃən/', 'Increase in value', 'Asset appreciation.', 'Valorização do ativo.'),
('collateral', 'garantia', 'business', 'advanced', '/kəˈlætərəl/', 'Security for loan', 'Collateral damage.', 'Danos colaterais.'),
('commodity', 'mercadoria', 'business', 'advanced', '/kəˈmɑːdəti/', 'Tradable good', 'Commodity prices.', 'Preços das mercadorias.'),
('conglomerate', 'conglomerado', 'business', 'advanced', '/kənˈɡlɑːmərət/', 'Large corporation', 'A media conglomerate.', 'Um conglomerado de média.'),
('consortium', 'consórcio', 'business', 'advanced', '/kənˈsɔːrtiəm/', 'Group of companies', 'Form a consortium.', 'Formar um consórcio.'),
('depreciation', 'depreciação', 'business', 'advanced', '/dɪˌpriːʃiˈeɪʃən/', 'Decrease in value', 'Asset depreciation.', 'Depreciação do ativo.'),
('divestiture', 'desinvestimento', 'business', 'advanced', '/daɪˈvestɪtʃər/', 'Selling assets', 'Strategic divestiture.', 'Desinvestimento estratégico.'),
('dividend', 'dividendo', 'business', 'advanced', '/ˈdɪvɪdend/', 'Profit share', 'Pay dividends.', 'Pagar dividendos.'),
('downturn', 'recessão', 'business', 'advanced', '/ˈdaʊntɜːrn/', 'Decline', 'Economic downturn.', 'Recessão económica.'),
('equity', 'capital próprio', 'business', 'advanced', '/ˈekwəti/', 'Ownership value', 'Home equity.', 'Capital próprio da casa.'),
('expenditure', 'despesa', 'business', 'advanced', '/ɪkˈspendɪtʃər/', 'Spending', 'Capital expenditure.', 'Despesa de capital.'),
('fiscal', 'fiscal', 'business', 'advanced', '/ˈfɪskəl/', 'Financial', 'Fiscal policy.', 'Política fiscal.'),
('fluctuation', 'flutuação', 'business', 'advanced', '/ˌflʌktʃuˈeɪʃən/', 'Variation', 'Price fluctuations.', 'Flutuações de preço.'),
('franchise', 'franquia', 'business', 'advanced', '/ˈfræntʃaɪz/', 'License', 'Open a franchise.', 'Abrir uma franquia.'),
('gross', 'bruto', 'business', 'advanced', '/ɡroʊs/', 'Total before deductions', 'Gross income.', 'Rendimento bruto.'),
('hedge', 'cobertura', 'business', 'advanced', '/hedʒ/', 'Risk protection', 'Hedge against risk.', 'Cobertura contra risco.'),
('incentive', 'incentivo', 'business', 'advanced', '/ɪnˈsentɪv/', 'Motivation', 'Financial incentives.', 'Incentivos financeiros.'),
('inflation', 'inflação', 'business', 'advanced', '/ɪnˈfleɪʃən/', 'Price increase', 'High inflation.', 'Inflação alta.'),
('infrastructure', 'infraestrutura', 'business', 'advanced', '/ˈɪnfrəstrʌktʃər/', 'Basic systems', 'Transport infrastructure.', 'Infraestrutura de transportes.'),
('insolvency', 'insolvência', 'business', 'advanced', '/ɪnˈsɑːlvənsi/', 'Inability to pay debts', 'Face insolvency.', 'Enfrentar insolvência.'),
('leverage', 'alavancagem', 'business', 'advanced', '/ˈlevərɪdʒ/', 'Using borrowed money', 'Financial leverage.', 'Alavancagem financeira.'),
('liquidation', 'liquidação', 'business', 'advanced', '/ˌlɪkwɪˈdeɪʃən/', 'Selling all assets', 'Company liquidation.', 'Liquidação da empresa.'),
('liquidity', 'liquidez', 'business', 'advanced', '/lɪˈkwɪdəti/', 'Cash availability', 'Liquidity crisis.', 'Crise de liquidez.'),
('monopoly', 'monopólio', 'business', 'advanced', '/məˈnɑːpəli/', 'Exclusive control', 'Market monopoly.', 'Monopólio de mercado.'),
('mortgage', 'hipoteca', 'business', 'advanced', '/ˈmɔːrɡɪdʒ/', 'Loan for property', 'Pay the mortgage.', 'Pagar a hipoteca.'),
('outsourcing', 'externalização', 'business', 'advanced', '/ˈaʊtsɔːrsɪŋ/', 'Using external services', 'Outsourcing strategy.', 'Estratégia de externalização.'),
('portfolio', 'portfólio', 'business', 'advanced', '/pɔːrtˈfoʊlioʊ/', 'Collection of investments', 'Investment portfolio.', 'Portfólio de investimentos.'),
('procurement', 'aquisição', 'business', 'advanced', '/proʊˈkjʊrmənt/', 'Obtaining supplies', 'Procurement process.', 'Processo de aquisição.'),
('revenue', 'receita', 'business', 'advanced', '/ˈrevənuː/', 'Income', 'Increase revenue.', 'Aumentar receitas.'),
('scalability', 'escalabilidade', 'business', 'advanced', '/ˌskeɪləˈbɪləti/', 'Ability to grow', 'System scalability.', 'Escalabilidade do sistema.'),
('stakeholder', 'parte interessada', 'business', 'advanced', '/ˈsteɪkhoʊldər/', 'Person with interest', 'Key stakeholders.', 'Partes interessadas principais.'),
('subsidiary', 'subsidiária', 'business', 'advanced', '/səbˈsɪdieri/', 'Owned company', 'A wholly-owned subsidiary.', 'Uma subsidiária totalmente controlada.'),
('sustainability', 'sustentabilidade', 'business', 'advanced', '/səˌsteɪnəˈbɪləti/', 'Long-term viability', 'Environmental sustainability.', 'Sustentabilidade ambiental.'),
('synergy', 'sinergia', 'business', 'advanced', '/ˈsɪnərdʒi/', 'Combined effect', 'Create synergy.', 'Criar sinergia.'),
('tariff', 'tarifa', 'business', 'advanced', '/ˈtærɪf/', 'Tax on imports', 'Import tariffs.', 'Tarifas de importação.'),
('turnover', 'volume de negócios', 'business', 'advanced', '/ˈtɜːrnoʊvər/', 'Business volume', 'Annual turnover.', 'Volume de negócios anual.'),
('venture', 'empreendimento', 'business', 'advanced', '/ˈventʃər/', 'Business project', 'Joint venture.', 'Empreendimento conjunto.'),
('yield', 'rendimento', 'business', 'advanced', '/jiːld/', 'Return on investment', 'High yield.', 'Alto rendimento.')

ON CONFLICT (word) DO NOTHING;
