-- Base Vocabulary - Advanced Level (Part 4: 250 words)
-- Philosophy, Psychology, Arts, Literature

INSERT INTO base_vocabulary (word, translation, category, difficulty, pronunciation, definition, example_sentence, example_translation) VALUES
-- Philosophy & Abstract Concepts
('aesthetic', 'estético', 'philosophy', 'advanced', '/esˈθetɪk/', 'Related to beauty', 'Aesthetic value.', 'Valor estético.'),
('altruism', 'altruísmo', 'philosophy', 'advanced', '/ˈæltruːɪzəm/', 'Selfless concern', 'An act of altruism.', 'Um ato de altruísmo.'),
('ambivalence', 'ambivalência', 'philosophy', 'advanced', '/æmˈbɪvələns/', 'Mixed feelings', 'Feel ambivalence.', 'Sentir ambivalência.'),
('consciousness', 'consciência', 'philosophy', 'advanced', '/ˈkɑːnʃəsnəs/', 'Awareness', 'Lose consciousness.', 'Perder a consciência.'),
('cynicism', 'cinismo', 'philosophy', 'advanced', '/ˈsɪnɪsɪzəm/', 'Distrust of motives', 'Growing cynicism.', 'Cinismo crescente.'),
('determinism', 'determinismo', 'philosophy', 'advanced', '/dɪˈtɜːrmɪnɪzəm/', 'All events are predetermined', 'Believe in determinism.', 'Acreditar no determinismo.'),
('dialectic', 'dialética', 'philosophy', 'advanced', '/ˌdaɪəˈlektɪk/', 'Logical discussion', 'Dialectic approach.', 'Abordagem dialética.'),
('dualism', 'dualismo', 'philosophy', 'advanced', '/ˈduːəlɪzəm/', 'Two opposed principles', 'Mind-body dualism.', 'Dualismo mente-corpo.'),
('empiricism', 'empirismo', 'philosophy', 'advanced', '/ɪmˈpɪrɪsɪzəm/', 'Knowledge from experience', 'Philosophical empiricism.', 'Empirismo filosófico.'),
('epistemology', 'epistemologia', 'philosophy', 'advanced', '/ɪˌpɪstəˈmɑːlədʒi/', 'Theory of knowledge', 'Questions of epistemology.', 'Questões de epistemologia.'),
('existentialism', 'existencialismo', 'philosophy', 'advanced', '/ˌeɡzɪˈstenʃəlɪzəm/', 'Philosophy of existence', 'Existentialist philosophy.', 'Filosofia existencialista.'),
('hedonism', 'hedonismo', 'philosophy', 'advanced', '/ˈhiːdənɪzəm/', 'Pursuit of pleasure', 'Embrace hedonism.', 'Abraçar o hedonismo.'),
('idealism', 'idealismo', 'philosophy', 'advanced', '/aɪˈdiːəlɪzəm/', 'Pursuit of ideals', 'Youthful idealism.', 'Idealismo juvenil.'),
('materialism', 'materialismo', 'philosophy', 'advanced', '/məˈtɪriəlɪzəm/', 'Focus on material things', 'Reject materialism.', 'Rejeitar o materialismo.'),
('metaphysics', 'metafísica', 'philosophy', 'advanced', '/ˌmetəˈfɪzɪks/', 'Nature of reality', 'Study metaphysics.', 'Estudar metafísica.'),
('nihilism', 'niilismo', 'philosophy', 'advanced', '/ˈnaɪəlɪzəm/', 'Rejection of meaning', 'Philosophical nihilism.', 'Niilismo filosófico.'),
('objectivity', 'objetividade', 'philosophy', 'advanced', '/ˌɑːbdʒekˈtɪvəti/', 'Unbiased view', 'Maintain objectivity.', 'Manter objetividade.'),
('ontology', 'ontologia', 'philosophy', 'advanced', '/ɑːnˈtɑːlədʒi/', 'Study of being', 'Ontological questions.', 'Questões ontológicas.'),
('paradox', 'paradoxo', 'philosophy', 'advanced', '/ˈpærədɑːks/', 'Seeming contradiction', 'A logical paradox.', 'Um paradoxo lógico.'),
('phenomenology', 'fenomenologia', 'philosophy', 'advanced', '/fɪˌnɑːməˈnɑːlədʒi/', 'Study of experience', 'Phenomenological approach.', 'Abordagem fenomenológica.'),
('pragmatism', 'pragmatismo', 'philosophy', 'advanced', '/ˈpræɡmətɪzəm/', 'Practical approach', 'Political pragmatism.', 'Pragmatismo político.'),
('rationalism', 'racionalismo', 'philosophy', 'advanced', '/ˈræʃənəlɪzəm/', 'Reason as source of knowledge', 'Philosophical rationalism.', 'Racionalismo filosófico.'),
('relativism', 'relativismo', 'philosophy', 'advanced', '/ˈrelətɪvɪzəm/', 'Truth is relative', 'Moral relativism.', 'Relativismo moral.'),
('skepticism', 'ceticismo', 'philosophy', 'advanced', '/ˈskeptɪsɪzəm/', 'Doubtful attitude', 'Healthy skepticism.', 'Ceticismo saudável.'),
('stoicism', 'estoicismo', 'philosophy', 'advanced', '/ˈstoʊɪsɪzəm/', 'Enduring hardship', 'Practice stoicism.', 'Praticar estoicismo.'),
('subjectivity', 'subjetividade', 'philosophy', 'advanced', '/ˌsʌbdʒekˈtɪvəti/', 'Personal view', 'Embrace subjectivity.', 'Abraçar a subjetividade.'),
('transcendence', 'transcendência', 'philosophy', 'advanced', '/trænˈsendəns/', 'Going beyond', 'Spiritual transcendence.', 'Transcendência espiritual.'),
('utilitarianism', 'utilitarismo', 'philosophy', 'advanced', '/ˌjuːtɪlɪˈteriənɪzəm/', 'Greatest good for most', 'Utilitarian ethics.', 'Ética utilitária.'),

-- Psychology & Mind
('catharsis', 'catarse', 'psychology', 'advanced', '/kəˈθɑːrsɪs/', 'Emotional release', 'Experience catharsis.', 'Experienciar catarse.'),
('cognition', 'cognição', 'psychology', 'advanced', '/kɑːɡˈnɪʃən/', 'Mental processes', 'Cognitive development.', 'Desenvolvimento cognitivo.'),
('conditioning', 'condicionamento', 'psychology', 'advanced', '/kənˈdɪʃənɪŋ/', 'Learning through association', 'Classical conditioning.', 'Condicionamento clássico.'),
('delusion', 'ilusão', 'psychology', 'advanced', '/dɪˈluːʒən/', 'False belief', 'Suffer from delusions.', 'Sofrer de ilusões.'),
('dissonance', 'dissonância', 'psychology', 'advanced', '/ˈdɪsənəns/', 'Conflict of beliefs', 'Cognitive dissonance.', 'Dissonância cognitiva.'),
('empathy', 'empatia', 'psychology', 'advanced', '/ˈempəθi/', 'Understanding feelings', 'Show empathy.', 'Mostrar empatia.'),
('fixation', 'fixação', 'psychology', 'advanced', '/fɪkˈseɪʃən/', 'Obsessive attachment', 'Unhealthy fixation.', 'Fixação não saudável.'),
('hallucination', 'alucinação', 'psychology', 'advanced', '/həˌluːsɪˈneɪʃən/', 'False perception', 'Visual hallucinations.', 'Alucinações visuais.'),
('inhibition', 'inibição', 'psychology', 'advanced', '/ˌɪnhɪˈbɪʃən/', 'Restraint', 'Social inhibitions.', 'Inibições sociais.'),
('introspection', 'introspeção', 'psychology', 'advanced', '/ˌɪntrəˈspekʃən/', 'Self-examination', 'Practice introspection.', 'Praticar introspeção.'),
('narcissism', 'narcisismo', 'psychology', 'advanced', '/ˈnɑːrsɪsɪzəm/', 'Self-obsession', 'Narcissistic behavior.', 'Comportamento narcisista.'),
('neurosis', 'neurose', 'psychology', 'advanced', '/nʊˈroʊsɪs/', 'Mental disorder', 'Suffer from neurosis.', 'Sofrer de neurose.'),
('obsession', 'obsessão', 'psychology', 'advanced', '/əbˈseʃən/', 'Persistent thought', 'Develop an obsession.', 'Desenvolver uma obsessão.'),
('paranoia', 'paranoia', 'psychology', 'advanced', '/ˌpærəˈnɔɪə/', 'Irrational suspicion', 'Suffer from paranoia.', 'Sofrer de paranoia.'),
('perception', 'perceção', 'psychology', 'advanced', '/pərˈsepʃən/', 'How we see things', 'Change perception.', 'Mudar a perceção.'),
('phobia', 'fobia', 'psychology', 'advanced', '/ˈfoʊbiə/', 'Intense fear', 'Social phobia.', 'Fobia social.'),
('projection', 'projeção', 'psychology', 'advanced', '/prəˈdʒekʃən/', 'Attributing to others', 'Psychological projection.', 'Projeção psicológica.'),
('psychoanalysis', 'psicanálise', 'psychology', 'advanced', '/ˌsaɪkoʊəˈnæləsɪs/', 'Mind analysis', 'Undergo psychoanalysis.', 'Submeter-se a psicanálise.'),
('psychosis', 'psicose', 'psychology', 'advanced', '/saɪˈkoʊsɪs/', 'Severe mental disorder', 'Acute psychosis.', 'Psicose aguda.'),
('regression', 'regressão', 'psychology', 'advanced', '/rɪˈɡreʃən/', 'Return to earlier state', 'Emotional regression.', 'Regressão emocional.'),
('repression', 'repressão', 'psychology', 'advanced', '/rɪˈpreʃən/', 'Suppressing thoughts', 'Emotional repression.', 'Repressão emocional.'),
('resilience', 'resiliência', 'psychology', 'advanced', '/rɪˈzɪliəns/', 'Ability to recover', 'Build resilience.', 'Construir resiliência.'),
('subconscious', 'subconsciente', 'psychology', 'advanced', '/ˌsʌbˈkɑːnʃəs/', 'Below awareness', 'Subconscious mind.', 'Mente subconsciente.'),
('sublimation', 'sublimação', 'psychology', 'advanced', '/ˌsʌblɪˈmeɪʃən/', 'Redirecting impulses', 'Artistic sublimation.', 'Sublimação artística.'),
('trauma', 'trauma', 'psychology', 'advanced', '/ˈtraʊmə/', 'Psychological wound', 'Childhood trauma.', 'Trauma de infância.'),

-- Arts & Literature
('allegory', 'alegoria', 'literature', 'advanced', '/ˈæləɡɔːri/', 'Symbolic story', 'A political allegory.', 'Uma alegoria política.'),
('alliteration', 'aliteração', 'literature', 'advanced', '/əˌlɪtəˈreɪʃən/', 'Repeated sounds', 'Use of alliteration.', 'Uso de aliteração.'),
('allusion', 'alusão', 'literature', 'advanced', '/əˈluːʒən/', 'Indirect reference', 'A biblical allusion.', 'Uma alusão bíblica.'),
('ambiguity', 'ambiguidade', 'literature', 'advanced', '/ˌæmbɪˈɡjuːəti/', 'Double meaning', 'Deliberate ambiguity.', 'Ambiguidade deliberada.'),
('anthology', 'antologia', 'literature', 'advanced', '/ænˈθɑːlədʒi/', 'Collection of works', 'Poetry anthology.', 'Antologia de poesia.'),
('archetype', 'arquétipo', 'literature', 'advanced', '/ˈɑːrkɪtaɪp/', 'Original pattern', 'The hero archetype.', 'O arquétipo do herói.'),
('catharsis', 'catarse', 'literature', 'advanced', '/kəˈθɑːrsɪs/', 'Emotional purging', 'Tragic catharsis.', 'Catarse trágica.'),
('connotation', 'conotação', 'literature', 'advanced', '/ˌkɑːnəˈteɪʃən/', 'Implied meaning', 'Negative connotations.', 'Conotações negativas.'),
('denotation', 'denotação', 'literature', 'advanced', '/ˌdiːnoʊˈteɪʃən/', 'Literal meaning', 'The denotation of.', 'A denotação de.'),
('dystopia', 'distopia', 'literature', 'advanced', '/dɪsˈtoʊpiə/', 'Nightmare society', 'A dystopian future.', 'Um futuro distópico.'),
('elegy', 'elegia', 'literature', 'advanced', '/ˈelədʒi/', 'Mournful poem', 'Write an elegy.', 'Escrever uma elegia.'),
('epigram', 'epigrama', 'literature', 'advanced', '/ˈepɪɡræm/', 'Witty saying', 'A clever epigram.', 'Um epigrama inteligente.'),
('epitome', 'epítome', 'literature', 'advanced', '/ɪˈpɪtəmi/', 'Perfect example', 'The epitome of.', 'O epítome de.'),
('euphemism', 'eufemismo', 'literature', 'advanced', '/ˈjuːfəmɪzəm/', 'Mild expression', 'Use a euphemism.', 'Usar um eufemismo.'),
('fable', 'fábula', 'literature', 'advanced', '/ˈfeɪbəl/', 'Moral story', 'Aesops fables.', 'As fábulas de Esopo.'),
('genre', 'género', 'literature', 'advanced', '/ˈʒɑːnrə/', 'Category of art', 'Literary genre.', 'Género literário.'),
('hyperbole', 'hipérbole', 'literature', 'advanced', '/haɪˈpɜːrbəli/', 'Exaggeration', 'Use hyperbole.', 'Usar hipérbole.'),
('imagery', 'imagética', 'literature', 'advanced', '/ˈɪmɪdʒəri/', 'Visual language', 'Vivid imagery.', 'Imagética vívida.'),
('irony', 'ironia', 'literature', 'advanced', '/ˈaɪrəni/', 'Opposite meaning', 'Dramatic irony.', 'Ironia dramática.'),
('juxtaposition', 'justaposição', 'literature', 'advanced', '/ˌdʒʌkstəpəˈzɪʃən/', 'Side by side', 'Striking juxtaposition.', 'Justaposição marcante.'),
('metaphor', 'metáfora', 'literature', 'advanced', '/ˈmetəfɔːr/', 'Comparison', 'Extended metaphor.', 'Metáfora prolongada.'),
('motif', 'motivo', 'literature', 'advanced', '/moʊˈtiːf/', 'Recurring element', 'A recurring motif.', 'Um motivo recorrente.'),
('narrative', 'narrativa', 'literature', 'advanced', '/ˈnærətɪv/', 'Story structure', 'First-person narrative.', 'Narrativa na primeira pessoa.'),
('ode', 'ode', 'literature', 'advanced', '/oʊd/', 'Lyric poem', 'An ode to joy.', 'Uma ode à alegria.'),
('oxymoron', 'oxímoro', 'literature', 'advanced', '/ˌɑːksɪˈmɔːrɑːn/', 'Contradictory terms', 'A beautiful oxymoron.', 'Um belo oxímoro.'),
('parable', 'parábola', 'literature', 'advanced', '/ˈpærəbəl/', 'Teaching story', 'Biblical parable.', 'Parábola bíblica.'),
('parody', 'paródia', 'literature', 'advanced', '/ˈpærədi/', 'Humorous imitation', 'A clever parody.', 'Uma paródia inteligente.'),
('personification', 'personificação', 'literature', 'advanced', '/pərˌsɑːnɪfɪˈkeɪʃən/', 'Giving human traits', 'Use personification.', 'Usar personificação.'),
('prose', 'prosa', 'literature', 'advanced', '/proʊz/', 'Ordinary writing', 'Write in prose.', 'Escrever em prosa.'),
('protagonist', 'protagonista', 'literature', 'advanced', '/proʊˈtæɡənɪst/', 'Main character', 'The storys protagonist.', 'O protagonista da história.'),
('rhetoric', 'retórica', 'literature', 'advanced', '/ˈretərɪk/', 'Art of persuasion', 'Political rhetoric.', 'Retórica política.'),
('satire', 'sátira', 'literature', 'advanced', '/ˈsætaɪər/', 'Mocking criticism', 'Political satire.', 'Sátira política.'),
('simile', 'símile', 'literature', 'advanced', '/ˈsɪməli/', 'Comparison with like', 'Use a simile.', 'Usar um símile.'),
('soliloquy', 'solilóquio', 'literature', 'advanced', '/səˈlɪləkwi/', 'Speaking alone', 'Hamlets soliloquy.', 'O solilóquio de Hamlet.'),
('sonnet', 'soneto', 'literature', 'advanced', '/ˈsɑːnɪt/', 'Fourteen-line poem', 'Shakespearean sonnet.', 'Soneto shakespeariano.'),
('subplot', 'subtrama', 'literature', 'advanced', '/ˈsʌbplɑːt/', 'Secondary story', 'A romantic subplot.', 'Uma subtrama romântica.'),
('symbolism', 'simbolismo', 'literature', 'advanced', '/ˈsɪmbəlɪzəm/', 'Use of symbols', 'Rich symbolism.', 'Simbolismo rico.'),
('syntax', 'sintaxe', 'literature', 'advanced', '/ˈsɪntæks/', 'Sentence structure', 'Complex syntax.', 'Sintaxe complexa.'),
('theme', 'tema', 'literature', 'advanced', '/θiːm/', 'Central idea', 'The main theme.', 'O tema principal.'),
('tragedy', 'tragédia', 'literature', 'advanced', '/ˈtrædʒədi/', 'Sad story', 'Greek tragedy.', 'Tragédia grega.'),
('verse', 'verso', 'literature', 'advanced', '/vɜːrs/', 'Poetry line', 'Write in verse.', 'Escrever em verso.')

ON CONFLICT (word) DO UPDATE SET
  translation = EXCLUDED.translation,
  category = EXCLUDED.category,
  difficulty = EXCLUDED.difficulty,
  pronunciation = EXCLUDED.pronunciation,
  definition = EXCLUDED.definition,
  example_sentence = EXCLUDED.example_sentence,
  example_translation = EXCLUDED.example_translation,
  updated_at = now();
